### ISSUE TITLE
Espresso TImeout with SDK Upgrade to 34

### ISSUE THREAD

**Issue by jagansekar-93** [appium/appium-espresso-driver#1002]
While trying to connect to Appium with espresso driver after SDK upgrade, I am getting the below error,
 
Espresso:
 
Changes made in espresso-server/app/build.gradle.kts  as part of the Espresso SDK upgrade are as follow,

minSdk = getIntProperty("appiumMinSdk", 29)
targetSdk = getIntProperty("appiumTargetSdk", 34)
buildToolsVersion = getStringProperty("appiumBuildTools", "34.0.0")
 
dependencies {
    implementation(fileTree(mapOf("dir" to "libs", "include" to listOf("*.jar"))))
    // additionalAppDependencies placeholder (don't change or delete this line)
    implementation ("androidx.core:core:1.13.1")
    implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.7.0")
    androidTestImplementation("com.google.guava:guava:31.1-android")
}
 

After complete cleanup of .appium binaries and reinstalling espresso server, we can work with emulator. Whereas with real device, the attached error persists.
 
Kindly assist. Thanks!
 
java.lang.NoSuchMethodError: No static method findIgnoreUnknownProperties(LgetErrorReporter;)LgetErrorReporter; in class Lcom/google/common/base/Suppliers; or its super classes (declaration of 'com.google.common.base.Suppliers' appears in /data/app/~~F2cF_ZzgQv2PhYgzG3qgCA==/io.appium.espressoserver.test-yMpHwvXUulgLpWkr40G7fA==/base.apk)
[EspressoDriver@5b63 (5d0ba363)]   at com.google.android.gms.internal.measurement.zzhg.zzb(SourceFile:129)
[EspressoDriver@5b63 (5d0ba363)]   at com.google.android.gms.measurement.internal.zzho.<init>(SourceFile:168)
[EspressoDriver@5b63 (5d0ba363)]   at com.google.android.gms.measurement.internal.zzho.zza(SourceFile:66)
[EspressoDriver@5b63 (5d0ba363)]   at com.google.android.gms.measurement.internal.AppMeasurementDynamiteService.initialize(SourceFile:94)
[EspressoDriver@5b63 (5d0ba363)]   at com.google.android.gms.internal.measurement.zzdr.zza(SourceFile:25)
[EspressoDriver@5b63 (5d0ba363)]   at com.google.android.gms.internal.measurement.zzds$zzb.run(SourceFile:12)
[EspressoDriver@5b63 (5d0ba363)]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
[EspressoDriver@5b63 (5d0ba363)]   at java.util.c
[sample.log](https://github.com/appium/appium-espresso-driver/files/15243944/sample.log)
oncurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
[EspressoDriver@5b63 (5d0ba363)]   at java.lang.Thread.run(Thread.java:1012)
[EspressoDriver@5b63 (5d0ba363)] [Instrumentation] INSTRUMENTATION_RESULT: shortMsg=Process crashed.

Attached the logs[
[sample.log](https://github.com/appium/appium-espresso-driver/files/15243950/sample.log)
](url)

**Comment by jagansekar-93** [comment]
@KazuCocoa  @mykola-mokhnach  @jlipps  @all - Please advice
