### ISSUE TITLE
android.content.res.Resources$NotFoundException: String resource ID #0x7f0a0000

### ISSUE THREAD

**Issue by Zolix11** [appium/appium-espresso-driver#1037]
I got the following error when I try to connect to my dummy app with the espresso driver. 

android.content.res.Resources$NotFoundException: String resource ID #0x7f0a0000
        at android.content.res.Resources.getText(Resources.java:511)
        at android.content.res.Resources.getString(Resources.java:604)
        at android.content.Context.getString(Context.java:904)
        at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:216)
        at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:206)
        at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:45)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2700)

This is my capability set to start the session: 
{
  "platformName": "Android",
  "appium:automationName": "Espresso",
  "appium:appPackage": "hu.bme.appiumtest",
  "appium:driver": "compose",
  "appium:appActivity": "hu.bme.appiumtest.MainActivity",
  "appium:noReset": false,
  "appium:showGradleLog": true,
  "appium:forceEspressoRebuild": true,
  "appium:useKeystore": true,
  "appium:keystorePath": "C:/Programming/android/Appiumtest/app/keystore/debug.keystore",
  "appium:keystorePassword": "android",
  "appium:keyAlias": "androiddebugkey",
  "appium:keyPassword": "android",
  "appium:useCompose": true,
  "appium:espressoBuildConfig": "{\"toolsVersion\": {\"compileSdk\": 35}, \"additionalAndroidTestDependencies\": [\"androidx.test:runner:1.5.2\",\"androidx.test:rules:1.5.0\",\"androidx.core:core-ktx:1.12.0\",\"androidx.test.ext:junit:1.2.1\",\"androidx.test.espresso:espresso-core:3.6.1\",\"androidx.lifecycle:lifecycle-runtime-ktx:2.8.7\",\"androidx.activity:activity-compose:1.9.3\",\"androidx.compose:compose-bom:2024.12.01\",\"androidx.compose.ui:ui:1.7.6\",\"androidx.compose.ui:ui-graphics:1.7.6\",\"androidx.compose.ui:ui-tooling:1.7.6\",\"androidx.compose.ui:ui-tooling-preview:1.7.6\",\"androidx.compose.ui:ui-test-manifest:1.7.6\",\"androidx.compose.ui:ui-test-junit4:1.7.6\",\"androidx.compose.foundation:foundation:1.7.6\",\"androidx.compose.material3:material3:1.3.1\",\"androidx.fragment:fragment-ktx:1.6.2\",\"androidx.compose.runtime:runtime:1.7.6\"]}"
}

Any Idea how can I start a session ?

**Comment by mmartosdev-wkl** [comment]
I'm experiencing the same issue. @Zolix11  were you able to resolve it?
