### ISSUE TITLE
DragNDrop fails with null object reference

### ISSUE THREAD

**Issue by saikrishna321** [appium/appium-espresso-driver#213]
@dpgraham @mykola-mokhnach 

Appium Server: Latest Master 
Java-Client: 6.1.0

```
MobileElement dragMe = (MobileElement) new WebDriverWait(driver, 30).until(ExpectedConditions
                .elementToBeClickable(MobileBy.AccessibilityId("dragMe")));
 WebElement source = dragMe;
WebElement target = driver.findElementByAccessibilityId("dropzone");
Actions actionBuilder = new Actions(driver);
Action dragAndDropAction = actionBuilder.clickAndHold(source).moveToElement(target, 1, 1)                .release(target).build();
dragAndDropAction.perform();
```

Server logs: https://gist.github.com/saikrishna321/e0681990382ccde8d6fbc9635170d063

**Comment by dpgraham** [comment]
@saikrishna321 Are you able to share the logcat logs for the point when that happens?

**Comment by dpgraham** [comment]
I just noticed it's using `mouse`.... is it on a device that supports `mouse` actions?

**Comment by mykola-mokhnach** [comment]
@dpgraham Selenium actions can only generate mouse gestures. In uia2 and xcuitest I do the pointer type replacement on driver layer.

**Comment by dpgraham** [comment]
I'll use [.getSources](https://developer.android.com/reference/android/view/InputDevice#getSources()) to check if MOUSE is available. If it isn't, we'll just use touch

**Comment by mykola-mokhnach** [comment]
I would assume if the action is done on a touch screen then there is 99% probability that the client wants to use `touch` action type. Selenium API is optimized to work with browsers/mouse controller, so they don't really care about touch screens

**Comment by dpgraham** [comment]
I suppose. I would like users to have the ability to test mouse movements in the future though, if there's ever a demand for Android laptop testing. I'll leave a note about it in the source code explaining it.

**Comment by dpgraham** [comment]
@saikrishna321 does that app crash at any point during the test?

Your bug means that this function is returning `null`:

```java
/**
     * Returns a list of application processes that are running on the device.
     *
     * <p><b>Note: this method is only intended for debugging or building
     * a user-facing process management UI.</b></p>
     *
     * @return Returns a list of RunningAppProcessInfo records, or null if there are no
     * running processes (it will not return an empty list).  This list ordering is not
     * specified.
     */
    public List<RunningAppProcessInfo> getRunningAppProcesses() {
        try {
            return ActivityManagerNative.getDefault().getRunningAppProcesses();
        } catch (RemoteException e) {
            throw e.rethrowFromSystemServer();
        }
    }
```

**Comment by saikrishna321** [comment]
yup, the app crashes once .perform() is completed 

will update the adb logs soon .. I'm on device

**Comment by saikrishna321** [comment]
@dpgraham this is adb crash logs https://gist.github.com/saikrishna321/ad5007a0896e5d52c35ebf7c5c90717b

**Comment by dpgraham** [comment]
Thanks @saikrishna321 I think I should have a fix in shortly.

**Comment by saikrishna321** [comment]
@dpgraham i believe this https://github.com/appium/appium-espresso-driver/pull/215 fixes the issue

**Comment by saikrishna321** [comment]
@dpgraham i tried with latest master and original error is fixed and app does not crash, but with some other exception now. Refer logs 

```
08-24 06:24:29.278  2520  2615 I appium  : Responding to server with error: io.appium.espressoserver.lib.handlers.exceptions.AppiumException: Could not complete pointer operation
08-24 06:24:29.278  2520  2615 I appium  : 	at io.appium.espressoserver.lib.helpers.w3c.adapter.espresso.MotionEventBuilder$MotionEventRunner.run(MotionEventBuilder.java:198)
08-24 06:24:29.278  2520  2615 I appium  : 	at io.appium.espressoserver.lib.helpers.w3c.adapter.espresso.AndroidMotionEvent.pointerEvent(AndroidMotionEvent.java:53)
08-24 06:24:29.278  2520  2615 I appium  : 	at io.appium.espressoserver.lib.helpers.w3c.adapter.espresso.EspressoW3CActionAdapter.pointerUp(EspressoW3CActionAdapter.java:314)
08-24 06:24:29.278  2520  2615 I appium  : 	at io.appium.espressoserver.lib.helpers.w3c.dispatcher.PointerDispatch.dispatchPointerEvent(PointerDispatch.java:72)
08-24 06:24:29.278  2520  2615 I appium  : 	at io.appium.espressoserver.lib.helpers.w3c.dispatcher.PointerDispatch.dispatchPointerUp(PointerDispatch.java:116)
08-24 06:24:29.278  2520  2615 I appium  : 	at io.appium.espressoserver.lib.helpers.w3c.models.ActionObject.dispatch(ActionObject.java:127)
08-24 06:24:29.278  2520  2615 I appium  : 	at io.appium.espressoserver.lib.helpers.w3c.models.Tick.dispatchAll(Tick.java:72)
08-24 06:24:29.278  2520  2615 I appium  : 	at io.appium.espressoserver.lib.helpers.w3c.models.ActionSequence.dispatch(ActionSequence.java:86)
08-24 06:24:29.278  2520  2615 I appium  : 	at io.appium.espressoserver.lib.helpers.w3c.models.Actions.perform(Actions.java:56)
08-24 06:24:29.278  2520  2615 I appium  : 	at io.appium.espressoserver.lib.handlers.PeformActions$1.run(PeformActions.java:21)
08-24 06:24:29.278  2520  2615 I appium  : 	at io.appium.espressoserver.lib.handlers.PeformActions$1.run(PeformActions.java:17)
08-24 06:24:29.278  2520  2615 I appium  : 	at io.appium.espressoserver.lib.viewaction.UiControllerPerformer.perform(UiControllerPerformer.java:43)
08-24 06:24:29.278  2520  2615 I appium  : 	at android.support.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:356)
08-24 06:24:29.278  2520  2615 I appium  : 	at android.support.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:241)
08-24 06:24:29.278  2520  2615 I appium  : 	at android.support.test.espresso.ViewInteraction.access$100(ViewInteraction.java:62)
08-24 06:24:29.278  2520  2615 I appium  : 	at android.support.test.espresso.ViewInteraction$1.call(ViewInteraction.java:149)
08-24 06:24:29.278  2520  2615 I appium  : 	at android.support.test.espresso.ViewInteraction$1.call(ViewInteraction.java:146)
08-24 06:24:29.278  2520  2615 I appium  : 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
08-24 06:24:29.278  2520  2615 I appium  : 	at android.os.Handler.handleCallback(Handler.java:739)
08-24 06:24:29.278  2520  2615 I appium  : 	at android.os.Handler.dispatchMessage(Handler.java:95)
08-24 06:24:29.278  2520  2615 I appium  : 	at android.os.Looper.loop(Looper.java:148)
08-24 06:24:29.278  2520  2615 I appium  : 	at android.app.ActivityThread.main(ActivityThread.java:5417)
08-24 06:24:29.278  2520  2615 I appium  : 	at java.lang.reflect.Method.invoke(Native Method)
08-24 06:24:29.278  2520  2615 I appium  : 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
08-24 06:24:29.278  2520  2615 I appium  : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
08-24 06:24:29.298  2520  2615 D appium  : Started processing DELETE request for '/session/9bcb4ec5-13ae-4d8a-8202-5b9cef094b5e'
08-24 06:24:29.298  2520  2615 D appium  : Matched route definition: class io.appium.espressoserver.lib.http.RouteDefinition
08-24 06:24:29.298  2520  2615 D appium  : Matched route handler: class io.appium.espressoserver.lib.handlers.DeleteSession
08-24 06:24:29.299  2520  2615 D appium  : Finished processing DELETE request for '/session/9bcb4ec5-13ae-4d8a-8202-5b9cef094b5e'
```
ADB logs: https://gist.github.com/saikrishna321/47831b3a0b0649837acc32e9f6f20de9
Server logs: https://gist.github.com/saikrishna321/31d92b7d964d0ea6872fc3f28164c10a

**Comment by mykola-mokhnach** [comment]
The chain is for sure not the one, which is supposed to work. Try the approach proposed by @jlipps in https://appiumpro.com/editions/29

**Comment by saikrishna321** [comment]
@mykola-mokhnach then we need to change the docs examples 

http://appium.io/docs/en/commands/interactions/actions/

**Comment by saikrishna321** [comment]
@dpgraham Fixes works well.. 


```
        Point source = dragMe.getCenter();
        Point target = driver.findElementByAccessibilityId("dropzone").getCenter();
        PointerInput finger = new PointerInput(PointerInput.Kind.TOUCH, "finger");
        Sequence dragNDrop = new Sequence(finger, 1);
        dragNDrop.addAction(finger.createPointerMove(Duration.ofSeconds(1),
                PointerInput.Origin.viewport(), source.x, source.y));
        dragNDrop.addAction(finger.createPointerDown(PointerInput.MouseButton.MIDDLE.asArg()));
        dragNDrop.addAction(finger.createPointerMove(Duration.ofSeconds(1),
                PointerInput.Origin.viewport(),
                target.x, target.y));
        dragNDrop.addAction(finger.createPointerUp(PointerInput.MouseButton.MIDDLE.asArg()));
        driver.perform(Arrays.asList(dragNDrop));
```

**Comment by dpgraham** [comment]
Awesome!
