### ISSUE TITLE
Unable to scroll/swipe

### ISSUE THREAD

**Issue by ania-s** [appium/appium-espresso-driver#227]
I started to use Appium: 1.9.0 with appium-espresso-driver for the testing with webdriver. However, I cannot get scrolling/swiping working.

I tried below:

```
browser.touchDown(10, 900);
browser.touchMove(10, 10);
browser.touchUp(10,10);
```
It doesn't give any error, but it doesn't do anything on the page (the same happens if I use "`browser.touchPerform`" or "`browser.touchAction`").

`browser.performTouchAction([{
          action: 'press',
          options: {
              x: 1945,
              y: 1255
          }
        }]);
        browser.performTouchAction([{
          action: 'moveTo',
          options: {
              x: 66,
              y: 470
          }
        }]);
        browser.performTouchAction([{
          action: 'release',
          options: {}
        }]);`
Gives the following error:

> An unknown server-side error occurred while processing the command. Original error: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 2 path $
> 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
> 	at com.google.gson.Gson.fromJson(Gson.java:888)
> 	at com.google.gson.Gson.fromJson(Gson.java:853)
> 	at com.google.gson.Gson.fromJson(Gson.java:802)
> 	at com.google.gson.Gson.fromJson(Gson.java:774)
> 	at io.appium.espressoserver.lib.http.Router.route(Router.java:240)
> 	at io.appium.espressoserver.lib.http.Server.serve(Server.java:62)
> 	at fi.iki.elonen.NanoHTTPD.serve(NanoHTTPD.java:2244)
> 	at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:945)
> 	at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
> 	at java.lang.Thread.run(Thread.java:764)
> Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 2 path $
> 	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
> 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213)
> 	... 10 more

Using `browser.scroll(element_selector, 50, 900);` gives me the following error:

> An unknown server-side error occurred while processing the command. Original error: java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
> 	at io.appium.espressoserver.lib.handlers.PointerEventHandler.handleTouchScroll(PointerEventHandler.java:217)
> 	at io.appium.espressoserver.lib.handlers.PointerEventHandler.handle(PointerEventHandler.java:92)
> 	at io.appium.espressoserver.lib.handlers.PointerEventHandler.handle(PointerEventHandler.java:35)
> 	at io.appium.espressoserver.lib.http.Router.route(Router.java:251)
> 	at io.appium.espressoserver.lib.http.Server.serve(Server.java:62)
> 	at fi.iki.elonen.NanoHTTPD.serve(NanoHTTPD.java:2244)
> 	at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:945)
> 	at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
> 	at java.lang.Thread.run(Thread.java:764)
> 

I tried few more methods to scroll vertically or swipe horizontally but pretty much all of them give me one of the above results. I would like to use this driver for our testing as it gives us an easy way to access elements. However, I need to have the scrolling.swiping functionality and I cannot get it working. Is there a way to do it with the current version of the driver?

**Comment by dpgraham** [comment]
Thanks for reporting this. Can you provide me with the Appium logs, too?

**Comment by mykola-mokhnach** [comment]
I assume that request arguments are wrong here. Valid actions object should look like https://github.com/appium/WebDriverAgent/blob/7fc54afc858c94b061d5983cbef02aca92c0a933/WebDriverAgentTests/IntegrationTests/FBW3CTouchActionsIntegrationTests.m#L270

**Comment by nichotined** [comment]
Hi, is there any way to pass this?

**Comment by nichotined** [comment]
Hi @dpgraham, I can run the command without any error, but It doesn't swipe actually.
`action.press(x=start_x, y=start_y).move_to(x=end_x, y=end_y).perform()`
Below the log
```
[HTTP]
[HTTP] --> POST /wd/hub/session/13c024e3-0e54-434c-9532-957efb6b120a/element
[HTTP] {"using":"xpath","value":"//*","sessionId":"13c024e3-0e54-434c-9532-957efb6b120a"}
[MJSONWP (13c024e3)] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Matched '/wd/hub/session/13c024e3-0e54-434c-9532-957efb6b120a/element' to command name 'findElement'
[debug] [JSONWP Proxy] Proxying [POST /wd/hub/session/13c024e3-0e54-434c-9532-957efb6b120a/element] to [POST http://localhost:8300/session/4e2d95b9-1890-4cfb-8179-ec79ea544d12/element] with body: {"using":"xpath","value":"//*","sessionId":"13c024e3-0e54-434c-9532-957efb6b120a"}
[debug] [JSONWP Proxy] Got response with status 200: {"id":"1862669f-9e3d-40c0-936a-aed6a2ba2148","sessionId":"4e2d95b9-1890-4cfb-8179-ec79ea544d12","status":0,"value":{"ELEMENT":"1d3071cc-6f7d-4542-adae-a25ba7c4a5aa"}}
[JSONWP Proxy] Replacing sessionId 4e2d95b9-1890-4cfb-8179-ec79ea544d12 with 13c024e3-0e54-434c-9532-957efb6b120a
[HTTP] <-- POST /wd/hub/session/13c024e3-0e54-434c-9532-957efb6b120a/element 200 30 ms - 166
[HTTP]
[HTTP] --> GET /wd/hub/session/13c024e3-0e54-434c-9532-957efb6b120a/element/1d3071cc-6f7d-4542-adae-a25ba7c4a5aa/location
[HTTP] {"id":"1d3071cc-6f7d-4542-adae-a25ba7c4a5aa","sessionId":"13c024e3-0e54-434c-9532-957efb6b120a"}
[MJSONWP (13c024e3)] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Matched '/wd/hub/session/13c024e3-0e54-434c-9532-957efb6b120a/element/1d3071cc-6f7d-4542-adae-a25ba7c4a5aa/location' to command name 'getLocation'
[debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/13c024e3-0e54-434c-9532-957efb6b120a/element/1d3071cc-6f7d-4542-adae-a25ba7c4a5aa/location] to [GET http://localhost:8300/session/4e2d95b9-1890-4cfb-8179-ec79ea544d12/element/1d3071cc-6f7d-4542-adae-a25ba7c4a5aa/location] with body: {"id":"1d3071cc-6f7d-4542-adae-a25ba7c4a5aa","sessionId":"13c024e3-0e54-434c-9532-957efb6b120a"}
[debug] [JSONWP Proxy] Got response with status 200: "{\"id\":\"3085de54-6f3f-4604-911e-1b10858703c5\",\"sessionId\":\"4e2d95b9-1890-4cfb-8179-ec79ea544d12\",\"status\":0,\"value\":{\"x\":0,\"y\":0,\"uriParams\":{}}}"
[JSONWP Proxy] Replacing sessionId 4e2d95b9-1890-4cfb-8179-ec79ea544d12 with 13c024e3-0e54-434c-9532-957efb6b120a
[HTTP] <-- GET /wd/hub/session/13c024e3-0e54-434c-9532-957efb6b120a/element/1d3071cc-6f7d-4542-adae-a25ba7c4a5aa/location 200 9 ms - 144
[HTTP]
[HTTP] --> GET /wd/hub/session/13c024e3-0e54-434c-9532-957efb6b120a/element/1d3071cc-6f7d-4542-adae-a25ba7c4a5aa/location
[HTTP] {"id":"1d3071cc-6f7d-4542-adae-a25ba7c4a5aa","sessionId":"13c024e3-0e54-434c-9532-957efb6b120a"}
[MJSONWP (13c024e3)] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Matched '/wd/hub/session/13c024e3-0e54-434c-9532-957efb6b120a/element/1d3071cc-6f7d-4542-adae-a25ba7c4a5aa/location' to command name 'getLocation'
[debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/13c024e3-0e54-434c-9532-957efb6b120a/element/1d3071cc-6f7d-4542-adae-a25ba7c4a5aa/location] to [GET http://localhost:8300/session/4e2d95b9-1890-4cfb-8179-ec79ea544d12/element/1d3071cc-6f7d-4542-adae-a25ba7c4a5aa/location] with body: {"id":"1d3071cc-6f7d-4542-adae-a25ba7c4a5aa","sessionId":"13c024e3-0e54-434c-9532-957efb6b120a"}
[debug] [JSONWP Proxy] Got response with status 200: "{\"id\":\"58971f80-b479-4778-866f-1974cee85166\",\"sessionId\":\"4e2d95b9-1890-4cfb-8179-ec79ea544d12\",\"status\":0,\"value\":{\"x\":0,\"y\":0,\"uriParams\":{}}}"
[JSONWP Proxy] Replacing sessionId 4e2d95b9-1890-4cfb-8179-ec79ea544d12 with 13c024e3-0e54-434c-9532-957efb6b120a
[HTTP] <-- GET /wd/hub/session/13c024e3-0e54-434c-9532-957efb6b120a/element/1d3071cc-6f7d-4542-adae-a25ba7c4a5aa/location 200 10 ms - 144
[HTTP]
[HTTP] --> GET /wd/hub/session/13c024e3-0e54-434c-9532-957efb6b120a/element/1d3071cc-6f7d-4542-adae-a25ba7c4a5aa/size
[HTTP] {"id":"1d3071cc-6f7d-4542-adae-a25ba7c4a5aa","sessionId":"13c024e3-0e54-434c-9532-957efb6b120a"}
[MJSONWP (13c024e3)] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Matched '/wd/hub/session/13c024e3-0e54-434c-9532-957efb6b120a/element/1d3071cc-6f7d-4542-adae-a25ba7c4a5aa/size' to command name 'getSize'
[debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/13c024e3-0e54-434c-9532-957efb6b120a/element/1d3071cc-6f7d-4542-adae-a25ba7c4a5aa/size] to [GET http://localhost:8300/session/4e2d95b9-1890-4cfb-8179-ec79ea544d12/element/1d3071cc-6f7d-4542-adae-a25ba7c4a5aa/size] with body: {"id":"1d3071cc-6f7d-4542-adae-a25ba7c4a5aa","sessionId":"13c024e3-0e54-434c-9532-957efb6b120a"}
[debug] [JSONWP Proxy] Got response with status 200: "{\"id\":\"0cef000b-5271-4494-8a0c-e1bf9eb20dc7\",\"sessionId\":\"4e2d95b9-1890-4cfb-8179-ec79ea544d12\",\"status\":0,\"value\":{\"height\":1920,\"width\":1080,\"uriParams\":{}}}"
[JSONWP Proxy] Replacing sessionId 4e2d95b9-1890-4cfb-8179-ec79ea544d12 with 13c024e3-0e54-434c-9532-957efb6b120a
[HTTP] <-- GET /wd/hub/session/13c024e3-0e54-434c-9532-957efb6b120a/element/1d3071cc-6f7d-4542-adae-a25ba7c4a5aa/size 200 10 ms - 159
[HTTP]
[HTTP] --> GET /wd/hub/session/13c024e3-0e54-434c-9532-957efb6b120a/element/1d3071cc-6f7d-4542-adae-a25ba7c4a5aa/size
[HTTP] {"id":"1d3071cc-6f7d-4542-adae-a25ba7c4a5aa","sessionId":"13c024e3-0e54-434c-9532-957efb6b120a"}
[MJSONWP (13c024e3)] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Matched '/wd/hub/session/13c024e3-0e54-434c-9532-957efb6b120a/element/1d3071cc-6f7d-4542-adae-a25ba7c4a5aa/size' to command name 'getSize'
[debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/13c024e3-0e54-434c-9532-957efb6b120a/element/1d3071cc-6f7d-4542-adae-a25ba7c4a5aa/size] to [GET http://localhost:8300/session/4e2d95b9-1890-4cfb-8179-ec79ea544d12/element/1d3071cc-6f7d-4542-adae-a25ba7c4a5aa/size] with body: {"id":"1d3071cc-6f7d-4542-adae-a25ba7c4a5aa","sessionId":"13c024e3-0e54-434c-9532-957efb6b120a"}
[debug] [JSONWP Proxy] Got response with status 200: "{\"id\":\"51d5d37f-2f67-4125-9382-4c0e9c54aff4\",\"sessionId\":\"4e2d95b9-1890-4cfb-8179-ec79ea544d12\",\"status\":0,\"value\":{\"height\":1920,\"width\":1080,\"uriParams\":{}}}"
[JSONWP Proxy] Replacing sessionId 4e2d95b9-1890-4cfb-8179-ec79ea544d12 with 13c024e3-0e54-434c-9532-957efb6b120a
[HTTP] <-- GET /wd/hub/session/13c024e3-0e54-434c-9532-957efb6b120a/element/1d3071cc-6f7d-4542-adae-a25ba7c4a5aa/size 200 10 ms - 159
[HTTP]
[HTTP] --> POST /wd/hub/session/13c024e3-0e54-434c-9532-957efb6b120a/touch/perform
[HTTP] {"actions":[{"action":"press","options":{"x":540,"y":1152}},{"action":"moveTo","options":{"x":540,"y":768}}],"sessionId":"13c024e3-0e54-434c-9532-957efb6b120a"}
[MJSONWP (13c024e3)] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Matched '/wd/hub/session/13c024e3-0e54-434c-9532-957efb6b120a/touch/perform' to command name 'performTouch'
[debug] [JSONWP Proxy] Proxying [POST /wd/hub/session/13c024e3-0e54-434c-9532-957efb6b120a/touch/perform] to [POST http://localhost:8300/session/4e2d95b9-1890-4cfb-8179-ec79ea544d12/touch/perform] with body: {"actions":[{"action":"press","options":{"x":540,"y":1152}},{"action":"moveTo","options":{"x":540,"y":768}}],"sessionId":"13c024e3-0e54-434c-9532-957efb6b120a"}
[debug] [JSONWP Proxy] Got response with status 200: {"id":"ddd5a779-02cf-4a38-afe6-83ed623cabc9","sessionId":"4e2d95b9-1890-4cfb-8179-ec79ea544d12","status":0,"value":null}
[JSONWP Proxy] Replacing sessionId 4e2d95b9-1890-4cfb-8179-ec79ea544d12 with 13c024e3-0e54-434c-9532-957efb6b120a
[HTTP] <-- POST /wd/hub/session/13c024e3-0e54-434c-9532-957efb6b120a/touch/perform 200 286 ms - 120
[HTTP]

```
I am using appium beta 1.9.2 beta 2
