### ISSUE TITLE
Implement (or fix) response to `/alert/text` for manipulating Alert Dialog 

### ISSUE THREAD

**Issue by juandg** [appium/appium-espresso-driver#260]
Calls to `/alert/text` using the Espresso Driver are returning `NotYetImplementedError: Method has not yet been implemented` when trying to act on an Alert Dialog. This call works as expected on other drivers like UIAutomator2 or XCUITest.

I see code [here](https://github.com/appium/appium-espresso-driver/blob/master/espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetAlertText.java) that seems to handle this case, so I'm not sure if this is scheduled for a future release or the functionality broke (or isn't finished)

I've tried the following 2 strategies and they both fail with the same error:
```python
wait = WebDriverWait(driver, 10)
wait.until(expected_conditions.alert_is_present())
```
```python
alert = driver.switch_to.alert
```
Both strategies work fine on UIAutomator2 or XCUITest and I can access the Alert Dialog and act on it.

This is the Appium log output with the error:
```java
[HTTP] --> GET /wd/hub/session/9bf22539-7bcf-4743-aa19-556b18932e89/alert/text
[HTTP] {"sessionId":"9bf22539-7bcf-4743-aa19-556b18932e89"}
[debug] [W3C] Calling AppiumDriver.getAlertText() with args: ["9bf22539-7bcf-4743-aa19-556b18932e89"]
[debug] [W3C] Encountered internal error running command: NotYetImplementedError: Method has not yet been implemented
[debug] [W3C]     at EspressoDriver.callee$0$0$ (/Users/test/.nvm/versions/node/v7.3.0/lib/node_modules/appium/node_modules/appium-android-driver/lib/commands/alert.js:6:9)
[debug] [W3C]     at tryCatch (/Users/test/.nvm/versions/node/v7.3.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[debug] [W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/test/.nvm/versions/node/v7.3.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[debug] [W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/test/.nvm/versions/node/v7.3.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[debug] [W3C]     at invoke (/Users/test/.nvm/versions/node/v7.3.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[debug] [W3C]     at enqueueResult (/Users/test/.nvm/versions/node/v7.3.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
[debug] [W3C]     at F (/Users/test/.nvm/versions/node/v7.3.0/lib/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
[debug] [W3C]     at AsyncIterator.enqueue (/Users/test/.nvm/versions/node/v7.3.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
[debug] [W3C]     at AsyncIterator.prototype.(anonymous function) [as next] (/Users/test/.nvm/versions/node/v7.3.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[debug] [W3C]     at Object.runtime.async (/Users/test/.nvm/versions/node/v7.3.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
[debug] [W3C]     at EspressoDriver.callee$0$0 [as getAlertText] (/Users/test/.nvm/versions/node/v7.3.0/lib/node_modules/appium/node_modules/appium-android-driver/build/lib/commands/alert.js:18:30)
[debug] [W3C]     at /Users/test/.nvm/versions/node/v7.3.0/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:296:26
[debug] [W3C]     at tryCatcher (/Users/test/.nvm/versions/node/v7.3.0/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/util.js:26:23)
[debug] [W3C]     at Promise._settlePromiseFromHandler (/Users/test/.nvm/versions/node/v7.3.0/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/promise.js:510:31)
[debug] [W3C]     at Promise._settlePromiseAt (/Users/test/.nvm/versions/node/v7.3.0/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/promise.js:584:18)
[debug] [W3C]     at Promise._settlePromiseAtPostResolution (/Users/test/.nvm/versions/node/v7.3.0/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/promise.js:248:10)
[debug] [W3C]     at Async._drainQueue (/Users/test/.nvm/versions/node/v7.3.0/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/async.js:128:12)
[debug] [W3C]     at Async._drainQueues (/Users/test/.nvm/versions/node/v7.3.0/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/async.js:133:10)
[debug] [W3C]     at Immediate.Async.drainQueues (/Users/test/.nvm/versions/node/v7.3.0/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/async.js:15:14)
[debug] [W3C]     at runCallback (timers.js:651:20)
[debug] [W3C]     at tryOnImmediate (timers.js:624:5)
[debug] [W3C]     at processImmediate [as _immediateCallback] (timers.js:596:5)
[HTTP] <-- GET /wd/hub/session/9bf22539-7bcf-4743-aa19-556b18932e89/alert/text 404 9 ms - 3472
```
And the relevant part of the stack trace on the client side

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/switch_to.py", line 55, in alert
    alert.text
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/common/alert.py", line 67, in text
    return self.driver.execute(Command.W3C_GET_ALERT_TEXT)["value"]
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/appium/webdriver/errorhandler.py", line 29, in check_response
    raise wde
  File "/usr/local/lib/python3.7/site-packages/appium/webdriver/errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Method has not yet been implemented
```

This is the log output when the call is successful using the other 2 drivers (UIAutomator2, XCUITest)
```java
[HTTP] --> GET /wd/hub/session/00396cdd-8018-4ce5-b1c7-05766bb12097/alert/text
[HTTP] {"sessionId":"00396cdd-8018-4ce5-b1c7-05766bb12097"}
[W3C] Calling AppiumDriver.getAlertText() with args: ["00396cdd-8018-4ce5-b1c7-05766bb12097"]
[XCUITest] Executing command 'getAlertText'
[JSONWP Proxy] Matched '/alert/text' to command name 'getAlertText'
[JSONWP Proxy] Proxying [GET /alert/text] to [GET http://localhost:8100/session/AAB0251F-2DFB-4049-8E12-CC1AF99081C2/alert/text] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"My Title\\n My Alert Text\",\n  \"sessionId\" : \"AAB0251F-2DFB-4049-8E12-CC1AF99081C2\",\n  \"status\" : 0\n}"
[W3C] Responding to client with driver.getAlertText() result: "Mt Title\nMy Alert Text"
[HTTP] <-- GET /wd/hub/session/00396cdd-8018-4ce5-b1c7-05766bb12097/alert/text 200 773 ms - 74
[HTTP] 
[HTTP] --> POST /wd/hub/session/00396cdd-8018-4ce5-b1c7-05766bb12097/alert/accept
[HTTP] {"sessionId":"00396cdd-8018-4ce5-b1c7-05766bb12097"}
[W3C] Calling AppiumDriver.postAcceptAlert() with args: ["00396cdd-8018-4ce5-b1c7-05766bb12097"]
[XCUITest] Executing command 'postAcceptAlert'
[JSONWP Proxy] Matched '/alert/accept' to command name 'postAcceptAlert'
[JSONWP Proxy] Proxying [POST /alert/accept] to [POST http://localhost:8100/session/AAB0251F-2DFB-4049-8E12-CC1AF99081C2/alert/accept] with body: {}
[JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"AAB0251F-2DFB-4049-8E12-CC1AF99081C2","status":0}
[W3C] Responding to client with driver.postAcceptAlert() result: {}
[HTTP] <-- POST /wd/hub/session/00396cdd-8018-4ce5-b1c7-05766bb12097/alert/accept 200 1163 ms - 12
```

**Comment by dpgraham** [comment]
Closing as fixed. Will re-open if this still doesn't work.
