### ISSUE TITLE
Swipe throws an error java.lang.NullPointerException

### ISSUE THREAD

**Issue by nichotined** [appium/appium-espresso-driver#310]
**ENV**
```
Appium Beta 1.10.0-beta.0
```
**With Wait**
*POST*
`http://localhost:4798/wd/hub/session/9932a90d-f9f6-4198-99a0-d3e1255330af/touch/perform`
```
{
  "actions": [
    { "action": "press", "options": { "x": 540, "y": 1000 } },
    { "action": "wait", "options": { "ms": "500" } },
    { "action": "moveTo", "options": { "x": 540, "y": 700 } },
    { "action": "release", "options": {} }
  ],
  "sessionId": "9932a90d-f9f6-4198-99a0-d3e1255330af"
}
```
RETURN 500
```
{
    "status": 13,
    "value": {
        "message": "An unknown server-side error occurred while processing the command. Original error: java.lang.NullPointerException: Attempt to invoke virtual method 'float java.lang.Float.floatValue()' on a null object reference\n\tat io.appium.espressoserver.lib.helpers.w3c.models.Tick.calculateTickDuration(Tick.java:52)\n\tat io.appium.espressoserver.lib.helpers.w3c.models.ActionSequence.dispatch(ActionSequence.java:79)\n\tat io.appium.espressoserver.lib.helpers.w3c.models.Actions.perform(Actions.java:56)\n\tat io.appium.espressoserver.lib.handlers.TouchAction$1.run(TouchAction.java:30)\n\tat io.appium.espressoserver.lib.handlers.TouchAction$1.run(TouchAction.java:22)\n\tat io.appium.espressoserver.lib.viewaction.UiControllerPerformer.perform(UiControllerPerformer.java:43)\n\tat android.support.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:356)\n\tat android.support.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:241)\n\tat android.support.test.espresso.ViewInteraction.access$100(ViewInteraction.java:62)\n\tat android.support.test.espresso.ViewInteraction$1.call(ViewInteraction.java:149)\n\tat android.support.test.espresso.ViewInteraction$1.call(ViewInteraction.java:146)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat android.os.Handler.handleCallback(Handler.java:873)\n\tat android.os.Handler.dispatchMessage(Handler.java:99)\n\tat android.os.Looper.loop(Looper.java:193)\n\tat android.app.ActivityThread.main(ActivityThread.java:6669)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)\n"
    },
    "sessionId": "9932a90d-f9f6-4198-99a0-d3e1255330af"
}
```

**Without Wait**
*POST* 
`http://localhost:4798/wd/hub/session/9932a90d-f9f6-4198-99a0-d3e1255330af/touch/perform`
```
{
  "actions": [
    { "action": "press", "options": { "x": 540, "y": 1000 } },
    { "action": "moveTo", "options": { "x": 540, "y": 700 } },
    { "action": "release", "options": {} }
  ],
  "sessionId": "9932a90d-f9f6-4198-99a0-d3e1255330af"
}
```
RETURN 200
```
{
    "id": "a6c40812-ebd8-4c2f-b5c3-949994acb08c",
    "sessionId": "03350a1e-0199-4e74-aabd-f42d1c96f950",
    "status": 0,
    "value": null
}
```
**But**
Without "Wait" I can't perform swipe correctly.
I was able to do it in previous version.

**Comment by nichotined** [comment]
@dpgraham do you think it is expected?

**Comment by dpgraham** [comment]
@nichotined definitely not. Null pointer is always a mistake. I'll have a look today. Thanks for opening this.

**Comment by dpgraham** [comment]
@nichotined Can you update to the latest beta? `npm install -g appium@beta`... the latest currently is `1.10.0-beta.5`.

There's a fix that changed this line:

`if (duration != null && (type == POINTER && subType == POINTER_MOVE) || subType == PAUSE)`

to this:

`if (duration != null && ((type == POINTER && subType == POINTER_MOVE) || subType == PAUSE))`

I'm pretty certain that this will fix it.

**Comment by nichotined** [comment]
@dpgraham will update after trying. Thanks!!

**Comment by nichotined** [comment]
@dpgraham I have updated to appium `1.10-beta 5`
but still encountering this error
```
WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: java.lang.NullPointerException: Attempt to invoke virtual method 'float java.lang.Float.floatValue()' on a null object reference
	at io.appium.espressoserver.lib.helpers.w3c.models.Tick.calculateTickDuration(Tick.java:52)
	at io.appium.espressoserver.lib.helpers.w3c.models.ActionSequence.dispatch(ActionSequence.java:79)
	at io.appium.espressoserver.lib.helpers.w3c.models.Actions.perform(Actions.java:56)
	at io.appium.espressoserver.lib.handlers.TouchAction$1.run(TouchAction.java:30)
	at io.appium.espressoserver.lib.handlers.TouchAction$1.run(TouchAction.java:22)
	at io.appium.espressoserver.lib.viewaction.UiControllerPerformer.perform(UiControllerPerformer.java:43)
	at android.support.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:356)
	at android.support.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:241)
	at android.support.test.espresso.ViewInteraction.access$100(ViewInteraction.java:62)
	at android.support.test.espresso.ViewInteraction$1.call(ViewInteraction.java:149)
	at android.support.test.espresso.ViewInteraction$1.call(ViewInteraction.java:146)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

log [https://gist.github.com/nichotined/c050244144239edcaf9df487045f09e5](url)

**Comment by dpgraham** [comment]
This doesn't link to the gist: https://github.com/appium/appium-espresso-driver/issues/url

**Comment by dpgraham** [comment]
Could you also check the contents of the Espresso Driver package.json to verify that it's 1.2.3....

Path to package.json is: `$(npm -g appium)/appium/node_modules/appium-espresso-driver/package.json`

**Comment by nichotined** [comment]
> Could you also check the contents of the Espresso Driver package.json to verify that it's 1.2.3....
> 
> Path to package.json is: `$(npm -g appium)/appium/node_modules/appium-espresso-driver/package.json`

yes it is v1.2.3
```
{
  "_from": "appium-espresso-driver@^1.2.3",
  "_id": "appium-espresso-driver@1.2.3",
  "_inBundle": false,
  "_integrity": "sha512-Nz6iON6ZgCWKES1xYszgAwyXN8t6mDdrbA7KpbpcOnDGnFn1ONtIoWgtLFEGITLRyDXGCGmpGUo3BCQujAib8g==",
  "_location": "/appium/appium-espresso-driver",
  "_phantomChildren": {},
  "_requested": {
    "type": "range",
    "registry": true,
    "raw": "appium-espresso-driver@^1.2.3",
    "name": "appium-espresso-driver",
    "escapedName": "appium-espresso-driver",
    "rawSpec": "^1.2.3",
    "saveSpec": null,
    "fetchSpec": "^1.2.3"
  },
  "_requiredBy": [
    "/appium"
  ],
  "_resolved": "https://registry.npmjs.org/appium-espresso-driver/-/appium-espresso-driver-1.2.3.tgz",
  "_shasum": "4830016a7bf4f2156ae8ec9f80a0d05a32c6fcbb",
  "_spec": "appium-espresso-driver@^1.2.3",
  "_where": "/Users/nicholaslagaunne/.nvm/versions/node/v9.11.2/lib/node_modules/appium",
  "author": {
    "name": "appium"
  },
  "bin": {},
  "bugs": {
    "url": "https://github.com/appium/appium-espresso-driver/issues"
  },
  "bundleDependencies": false,
  "dependencies": {
    "@babel/runtime": "^7.0.0",
    "appium-adb": "^6.25.0",
    "appium-android-driver": "^4.0.0",
    "appium-base-driver": "^3.5.0",
    "appium-support": "^2.20.0",
    "asyncbox": "^2.3.1",
    "bluebird": "^3.5.0",
    "lodash": "^4.17.11",
    "portscanner": "^2.1.1",
    "request": "^2.88.0",
    "request-promise": "^4.2.1",
    "source-map-support": "^0.5.8",
    "yargs": "^12.0.1"
  },
  "deprecated": false,
  "description": "Espresso integration for Appium",
  "devDependencies": {
    "ajv": "^6.5.3",
    "android-apidemos": "^3.0.0",
    "appium-chromedriver": "^4.7.0",
    "appium-gulp-plugins": "^3.1.0",
    "appium-test-support": "^1.0.0",
    "babel-eslint": "^10.0.0",
    "chai": "^4.1.2",
    "chai-as-promised": "^7.1.1",
    "eslint": "^5.2.0",
    "eslint-config-appium": "^3.1.0",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-mocha": "^5.0.0",
    "eslint-plugin-promise": "^4.0.0",
    "gps-demo-app": "^2.1.1",
    "gulp": "^4.0.0",
    "mocha": "^5.1.1",
    "pre-commit": "^1.2.2",
    "sinon": "^6.0.0",
    "wd": "^1.10.3",
    "xmldom": "^0.1.27",
    "xpath": "0.0.27"
  },
  "directories": {
    "lib": "lib"
  },
  "engines": [
    "node"
  ],
  "files": [
    "index.js",
    "lib",
    "build/index.js",
    "build/lib",
    "espresso-server/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk",
    "espresso-server/AndroidManifest-test.xml"
  ],
  "greenkeeper": {
    "ignore": []
  },
  "homepage": "https://github.com/appium/appium-espresso-driver#readme",
  "keywords": [
    "appium",
    "espresso",
    "automated testing",
    "android"
  ],
  "license": "Apache-2.0",
  "main": "./build/index.js",
  "name": "appium-espresso-driver",
  "pre-commit": [
    "precommit-msg",
    "precommit-test"
  ],
  "repository": {
    "type": "git",
    "url": "git+https://github.com/appium/appium-espresso-driver.git"
  },
  "scripts": {
    "build": "npm run build:node && npm run build:server",
    "build:node": "gulp transpile",
    "build:server": "cd espresso-server && ./gradlew clean assembleAndroidTest && cd ..",
    "clean": "rm -rf node_modules && rm -f package-lock.json && npm install",
    "coverage": "gulp coveralls",
    "e2e-test": "gulp transpile && mocha --timeout 600000 build/test/functional/",
    "lint": "gulp eslint",
    "lint:fix": "gulp eslint --fix",
    "mocha": "mocha",
    "precommit-msg": "echo 'Pre-commit checks...' && exit 0",
    "precommit-test": "REPORTER=dot gulp once",
    "prepare": "gulp prepublish && npm run build:server",
    "test": "npm run test:server && npm run test:node",
    "test:node": "gulp once",
    "test:server": "echo 'TODO: Add gradle unit tests'",
    "watch": "gulp watch"
  },
  "version": "1.2.3"
}

```

**Comment by nichotined** [comment]
> This doesn't link to the gist: https://github.com/appium/appium-espresso-driver/issues/url

updated link

**Comment by mykola-mokhnach** [comment]
Of course you can and you are welcome to.
Here is the documentation we have https://github.com/appium/appium/tree/master/docs/en/contributing-to-appium

**Comment by dpgraham** [comment]
@nichotined I'd be very happy to have contributions! You can get started by just checking out this repo and running it on your machine. You need to have NodeJS installed and you need to have Android SDK installed (installing Android Studio will do the trick). There's some documentation on how to do this in the README.md.

Feel free to have a look at the issues and let me know if any of them interest you. There's definitely going to be a lot of work to be done on this in the foreseeable future.

**Comment by nichotined** [comment]
@dpgraham my latest test (1.3 release), it didn't throw any error anymore.
but it didn't wait at all.

**Comment by dpgraham** [comment]
There's the mobile swipe command

**Comment by dpgraham** [comment]
When you say that it didn't "wait" are you saying it didn't wait the 500ms?

That seems like a pretty low wait time and wouldn't be very noticeable. Have you tried waiting for a longer time, like 5000ms?

(p.s.: closing is resolved, but can still discuss)

**Comment by nichotined** [comment]
I did @dpgraham
It didn't wait at all

**Comment by dpgraham** [comment]
@nichotined How long was the wait?

**Comment by dpgraham** [comment]
Wait...  I just noticed the problem.

The actions json is: `{ "action": "wait", "options": { "ms": "500" } }`

It should be: `{ "action": "wait", "duration": 500 }`
