### ISSUE TITLE
is there way to find the edittext error message

### ISSUE THREAD

**Issue by mgmanikandan87** [appium/appium-espresso-driver#355]
<img width="385" alt="screen shot 2018-12-16 at 9 22 03 am" src="https://user-images.githubusercontent.com/3031178/50049870-64957180-0114-11e9-83fc-e7384081691e.png">

I was trying to add this appium-epresso-driver code locally and I am getting below error

Dec 16, 2018 9:26:25 AM io.appium.java_client.remote.AppiumCommandExecutor$1 lambda$0
INFO: Detected dialect: W3C

org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: No such route /session/a2a3fb21-ace7-4b6f-b408-d94b85b89845/appium/execute_mobile/error_text:_displayed
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: 'Manikandans-MacBook-Pro.local', ip: '192.168.1.9', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.5', java.version: '9.0.1'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities {app: /Users/manikandan.mg/Docume..., automationName: Espresso, deviceName: Android Emulator, forceEspressoRebuild: true, javascriptEnabled: true, platform: ANDROID, platformName: Android}
Session ID: 981525b3-abd3-4230-9885-3dad4911d77c

	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:231)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:480)
	at com.test.appiumTest.AppiumTest.testLogin_Espresso(AppiumTest.java:65)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

Process finished with exit code 255

Appium error : 

[HTTP] {"script":"mobile: errorText","args":[{"text":"Field cannot be left blank."}]}
[debug] [W3C] Calling AppiumDriver.execute() with args: ["mobile: errorText",[{"text":"Field cannot be left blank."}],"981525b3-abd3-4230-9885-3dad4911d77c"]
[debug] [JSONWP Proxy] Proxying [POST /appium/execute_mobile/error_text:_displayed] to [POST http://localhost:8300/session/a2a3fb21-ace7-4b6f-b408-d94b85b89845/appium/execute_mobile/error_text:_displayed] with body: {"text":"Field cannot be left blank."}
[debug] [MJSONWP] Matched JSONWP error code 13 to UnknownError
[debug] [W3C] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: No such route /session/a2a3fb21-ace7-4b6f-b408-d94b85b89845/appium/execute_mobile/error_text:_displayed
[debug] [W3C]     at errorFromMJSONWPStatusCode (/Users/manikandan.mg/Documents/appiumCode/appium/node_modules/appium-base-driver/lib/protocol/errors.js:787:10)
[debug] [W3C]     at ProxyRequestError.getActualError (/Users/manikandan.mg/Documents/appiumCode/appium/node_modules/appium-base-driver/lib/protocol/errors.js:681:14)
[debug] [W3C]     at JWProxy.command$ (/Users/manikandan.mg/Documents/appiumCode/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:236:19)
[debug] [W3C]     at tryCatch (/Users/manikandan.mg/Documents/appiumCode/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[debug] [W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/manikandan.mg/Documents/appiumCode/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[debug] [W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Users/manikandan.mg/Documents/appiumCode/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[debug] [W3C]     at GeneratorFunctionPrototype.invoke (/Users/manikandan.mg/Documents/appiumCode/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[debug] [W3C]     at <anonymous>
[HTTP] <-- POST /wd/hub/session/981525b3-abd3-4230-9885-3dad4911d77c/execute/sync 500 100 ms - 1537
[HTTP] 
[HTTP] --> DELETE /wd/hub/session/981525b3-abd3-4230-9885-3dad4911d77c
[HTTP] {}
[debug] [W3C] Calling AppiumDriver.deleteSession() with args: ["981525b3-abd3-4230-9885-3dad4911d77c"]
[debug] [BaseDriver] Event 'quitSessionRequested' logged at 1544932586145 (09:26:26 GMT+0530 (IST))
[Appium] Removing session 981525b3-abd3-4230-9885-3dad4911d77c from our master session list
[debug] [Espresso] Deleting espresso session
[debug] [Espresso] Deleting Espresso server session
[debug] [JSONWP Proxy] Matched '/' to command name 'deleteSession'
[debug] [JSONWP Proxy] Proxying [DELETE /] to [DELETE http://localhost:8300/session/a2a3fb21-ace7-4b6f-b408-d94b85b89845] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\"id\":\"91d66def-d93f-4257-9b14-8c3113dba8c1\",\"sessionId\":\"a2a3fb21-ace7-4b6f-b408-d94b85b89845\",\"status\":0,\"value\":{\"id\":\"1d61cbfb-cd38-42ea-b4fe-b94392af7a12\",\"sessionId\":null,\"status\":0,\"value\":null}}"
[debug] [Espresso] [Instrumentation][STDOUT] io.appium.espressoserver.EspressoServerRunnerTest:
[Espresso] Instrumentation process exited with code null from signal SIGTERM
[debug] [ADB] Running '/Users/manikandan.mg/Library/Android/sdk/platform-tools/adb -P 5037 -s ZY223W5MN4 shell am force-stop com.example.manikandanmg.testapp'
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Device API level: 24
[debug] [ADB] Removing forwarded port socket connection: 8300 
[debug] [ADB] Running '/Users/manikandan.mg/Library/Android/sdk/platform-tools/adb -P 5037 -s ZY223W5MN4 forward --remove tcp\:8300'
[debug] [BaseDriver] Event 'quitSessionFinished' logged at 1544932586945 (09:26:26 GMT+0530 (IST))
[debug] [W3C] Received response: null
[debug] [W3C] But deleting session, so not returning
[debug] [W3C] Responding to client with driver.deleteSession() result: null
[HTTP] <-- DELETE /wd/hub/session/981525b3-abd3-4230-9885-3dad4911d77c 200 802 ms - 14
[HTTP] 

Please help me where I am going wrong, I am planning to add more features to appium-espresso

**Comment by rajdeepv** [comment]
If you can get hold of the internal id of the element, you can do it easily using view functions as shown below:
```
ref = @driver.find_element({id: '<id_of_textview>'}).ref
error_text = @driver.execute_script("mobile: backdoor", {target: "element", elementId: ref, methods: [{name: "getError"}]})
```

Note that above is in ruby. if you are using Java, you need to check how to find element ref

**Comment by mgmanikandan87** [comment]
@rajdeepv  -  Awesome! it worked thank you so much 

` MobileElement el = (MobileElement) driver.findElement(MobileBy.id("com.example.manikandanmg.testapp:id/editText1"));
            JavascriptExecutor js = (JavascriptExecutor) driver;
            Object o = js.executeScript("mobile: backdoor", ImmutableMap.of("target", "element", "elementId", el.getId(), "methods", Arrays.asList(ImmutableMap.of("name", "getError"))));

            System.out.println(String.valueOf(o));`

**Comment by mgmanikandan87** [comment]
Closing this, hence this can achieve through backdoor

**Comment by jlipps** [comment]
@rajdeepv it would be nice to make this available as an element attribute, so people could just do `element.getAttribute('errorText')` and the backdoor script would run under the hood.

**Comment by rajdeepv** [comment]
@jlipps yes, it is a common use case and makes sense to add as an attribute. will raise a PR soon

**Comment by mgmanikandan87** [comment]
@rajdeepv - Once you done with your changes, let me know I will update my script too

**Comment by NoelOmo** [comment]
The mobile: backdoor script is not available for those of us that are using  UiAutomator2 instead of Espresso as our AutomationName. Is there any work around?
