### ISSUE TITLE
Instrumentation Failure After Updating APK SDK to API Level 28 

### ISSUE THREAD

**Issue by FerdinandNell** [appium/appium-espresso-driver#432]
Desired Caps: 

{
  "app": "/Users/[redacted]/PycharmProjects/[redacted]/APPS/Android/QA/base.apk",
  "platformName": "Android",
  "automationName": "Espresso",
  "platformVersion": "8.0",
  "deviceName": "device",
  "udid": "23687718740b7ece",
  "disableAndroidWatchers": "true",
  "autoGrantPermissions" : "true",
  "ignoreUnimportantViews" : "true",
  "androidInstallTimeout" : 900000,
  "forceEspressoRebuild": "true",
  "appWaitActivity": "com.[redacted].[redacted].*",
  "adbExecTimeout" : 900000,
  "appActivity": "com.[redacted].[redacted].presentation.landingpage.LandingPageActivity"
}

Logs

```
Proxying [POST /session] to [POST http://localhost:8300/session] with body: {"desiredCapabilities":{"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"platformName":"Android","adbExecTimeout":900000,"ignoreUnimportantViews":"true","disableAndroidWatchers":"true","androidInstallTimeout":900000,"autoGrantPermissions":true,"platformVersion":"8.0","appActivity":"com.[redacted].[redacted].presentation.landingpage.LandingPageActivity","appWaitActivity":"com.[redacted].[redacted].*","udid":"23687718740b7ece","deviceName":"device","forceEspressoRebuild":true,"app":"/Users/[redacted]/PycharmProjects/[redacted]_TestAutomation_Web/APPS/Android/QA/base.apk","automationName":"Espresso"},"platformName":"Android","adbExecTimeout":900000,"ignoreUnimportantViews":"true","disableAndroidWatchers":"true","androidInstallTimeout":900000,"autoGrantPermissions":true,"platformVersion":"8.0","appActivity":"com.[redacted].[redacted].presentation.landingpage.LandingPageActivity","appWaitActivity":...
[Espresso] [Instrumentation][STDOUT] io.appium.espressoserver.EspressoServerRunnerTest:
[Espresso] [Instrumentation][STDOUT] Process crashed while executing startEspressoServer(io.appium.espressoserver.EspressoServerRunnerTest):
[Espresso] [Instrumentation][STDOUT] android.content.res.Resources$NotFoundException: Drawable com.[redacted].[redacted].qa:dimen/com_appboy_card_background_border_left with resource ID #0x7f070059
[Espresso] [Instrumentation][STDOUT] Caused by: android.content.res.Resources$NotFoundException: Resource "com.[redacted].[redacted].qa:dimen/com_appboy_card_background_border_left" (7f070059) is not a Drawable (color or path): TypedValue{t=0x5/d=0x101 a=3 r=0x7f070059}
[Espresso] [Instrumentation][STDOUT] 	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:832)
[Espresso] [Instrumentation][STDOUT] 	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:677)
[Espresso] [Instrumentation][STDOUT] 	at android.content.res.Resources.getDrawableForDensity(Resources.java:903)
[Espresso] [Instrumentation][STDOUT] 	at android.content.res.Resources.getDrawable(Resources.java:842)
[Espresso] [Instrumentation][STDOUT] 	at android.content.Context.getDrawable(Context.java:628)
[Espresso] [Instrumentation][STDOUT] 	at androidx.core.content.ContextCompat.getDrawable(ContextCompat.java:463)
[Espresso] [Instrumentation][STDOUT] 	at androidx.appcompat.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:203)
[Espresso] [Instrumentation][STDOUT] 	at androidx.appcompat.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:191)
[Espresso] [Instrumentation][STDOUT] 	at androidx.appcompat.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:753)
[Espresso] [Instrumentation][STDOUT] 	at androidx.appcompat.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:196)
[Espresso] [Instrumentation][STDOUT] 	at androidx.appcompat.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:86)
[Espresso] [Instrumentation][STDOUT] 	at androidx.appcompat.app.AppCompatDelegateImpl.(AppCompatDelegateImpl.java:260)
[Espresso] [Instrumentation][STDOUT] 	at androidx.appcompat.app.AppCompatDelegate.create(AppCompatDelegate.java:182)
[Espresso] [Instrumentation][STDOUT] 	at androidx.appcompat.app.AppCompatActivity.getDelegate(AppCompatActivity.java:520)
[Espresso] [Instrumentation][STDOUT] 	at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:71)
[Espresso] [Instrumentation][STDOUT] 	at com.[redacted].[redacted].presentation.ABaseActivity.onCreate(ABaseActivity.java:127)
[Espresso] [Instrumentation][STDOUT] 	at com.[redacted].[redacted].presentation.landingpage.LandingPageActivity.onCreate(LandingPageActivity.java:94)
[Espresso] [Instrumentation][STDOUT] 	at android.app.Activity.performCreate(Activity.java:7326)
[Espresso] [Instrumentation][STDOUT] 	at android.app.Activity.performCreate(Activity.java:7317)
[Espresso] [Instrumentation][STDOUT] 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
[Espresso] [Instrumentation][STDOUT] 	at androidx.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:674)
[Espresso] [Instrumentation][STDOUT] 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3066)
[Espresso] [Instrumentation][STDOUT] 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3229)
[Espresso] [Instrumentation][STDOUT] 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
[Espresso] [Instrumentation][STDOUT] 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
[Espresso] [Instrumentation][STDOUT] 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
[Espresso] [Instrumentation][STDOUT] 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1926)
[Espresso] [Instrumentation][STDOUT] 	at android.os.Handler.dispatchMessage(Handler.java:106)
[Espresso] [Instrumentation][STDOUT] 	at android.os.Looper.loop(Looper.java:214)
[Espresso] [Instrumentation][STDOUT] 	at android.app.ActivityThread.main(ActivityThread.java:6981)
[Espresso] [Instrumentation][STDOUT] 	at java.lang.reflect.Method.invoke(Native Method)
[Espresso] [Instrumentation][STDOUT] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
[Espresso] [Instrumentation][STDOUT] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
[Espresso] [Instrumentation][STDOUT]
[Espresso] [Instrumentation][STDOUT] Process crashed while executing startEspressoServer(io.appium.espressoserver.EspressoServerRunnerTest):
[Espresso] [Instrumentation][STDOUT] java.lang.RuntimeException: Unable to start activity ComponentInfo{com.[redacted].[redacted].qa/com.[redacted].[redacted].presentation.landingpage.LandingPageActivity}: android.content.res.Resources$NotFoundException: Drawable com.[redacted].[redacted].qa:dimen/com_appboy_card_background_border_left with resource ID #0x7f070059
[Espresso] [Instrumentation][STDOUT] 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3086)
[Espresso] [Instrumentation][STDOUT] 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3229)
[Espresso] [Instrumentation][STDOUT] 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
[Espresso] [Instrumentation][STDOUT] 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
[Espresso] [Instrumentation][STDOUT] 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
[Espresso] [Instrumentation][STDOUT] 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1926)
[Espresso] [Instrumentation][STDOUT] 	at android.os.Handler.dispatchMessage(Handler.java:106)
[Espresso] [Instrumentation][STDOUT] 	at android.os.Looper.loop(Looper.java:214)
[Espresso] [Instrumentation][STDOUT] 	at android.app.ActivityThread.main(ActivityThread.java:6981)
[Espresso] [Instrumentation][STDOUT] 	at java.lang.reflect.Method.invoke(Native Method)
[Espresso] [Instrumentation][STDOUT] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
[Espresso] [Instrumentation][STDOUT] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
[Espresso] [Instrumentation][STDOUT] Caused by: android.content.res.Resources$NotFoundException: Drawable com.[redacted].[redacted].qa:dimen/com_appboy_card_background_border_left with resource ID #0x7f070059
[Espresso] [Instrumentation][STDOUT] Caused by: android.content.res.Resources$NotFoundException: Resource "com.[redacted].[redacted].qa:dimen/com_appboy_card_background_border_left" (7f070059) is not a Drawable (color or path): TypedValue{t=0x5/d=0x101 a=3 r=0x7f070059}
[Espresso] [Instrumentation][STDOUT] 	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:832)
[Espresso] [Instrumentation][STDOUT] 	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:677)
[Espresso] [Instrumentation][STDOUT] 	at android.content.res.Resources.getDrawableForDensity(Resources.java:903)
[Espresso] [Instrumentation][STDOUT] 	at android.content.res.Resources.getDrawable(Resources.java:842)
[Espresso] [Instrumentation][STDOUT] 	at android.content.Context.getDrawable(Context.java:628)
[Espresso] [Instrumentation][STDOUT] 	at androidx.core.content.ContextCompat.getDrawable(ContextCompat.java:463)
[Espresso] [Instrumentation][STDOUT] 	at androidx.appcompat.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:203)
[Espresso] [Instrumentation][STDOUT] 	at androidx.appcompat.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:191)
[Espresso] [Instrumentation][STDOUT] 	at androidx.appcompat.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:753)
[Espresso] [Instrumentation][STDOUT] 	at androidx.appcompat.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:196)
[Espresso] [Instrumentation][STDOUT] 	at androidx.appcompat.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:86)
[Espresso] [Instrumentation][STDOUT] 	at androidx.appcompat.app.AppCompatDelegateImpl.(AppCompatDelegateImpl.java:260)
[Espresso] [Instrumentation][STDOUT] 	at androidx.appcompat.app.AppCompatDelegate.create(AppCompatDelegate.java:182)
[Espresso] [Instrumentation][STDOUT] 	at androidx.appcompat.app.AppCompatActivity.getDelegate(AppCompatActivity.java:520)
[Espresso] [Instrumentation][STDOUT] 	at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:71)
[Espresso] [Instrumentation][STDOUT] 	at com.[redacted].[redacted].presentation.ABaseActivity.onCreate(ABaseActivity.java:127)
[Espresso] [Instrumentation][STDOUT] 	at com.[redacted].[redacted].presentation.landingpage.LandingPageActivity.onCreate(LandingPageActivity.java:94)
[Espresso] [Instrumentation][STDOUT] 	at android.app.Activity.performCreate(Activity.java:7326)
[Espresso] [Instrumentation][STDOUT] 	at android.app.Activity.performCreate(Activity.java:7317)
[Espresso] [Instrumentation][STDOUT] 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
[Espresso] [Instrumentation][STDOUT] 	at androidx.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:674)
[Espresso] [Instrumentation][STDOUT] 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3066)
[Espresso] [Instrumentation][STDOUT] 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3229)
[Espresso] [Instrumentation][STDOUT] 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
[Espresso] [Instrumentation][STDOUT] 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
[Espresso] [Instrumentation][STDOUT] 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
[Espresso] [Instrumentation][STDOUT] 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1926)
[Espresso] [Instrumentation][STDOUT] 	at android.os.Handler.dispatchMessage(Handler.java:106)
[Espresso] [Instrumentation][STDOUT] 	at android.os.Looper.loop(Looper.java:214)
[Espresso] [Instrumentation][STDOUT] 	at android.app.ActivityThread.main(ActivityThread.java:6981)
[Espresso] [Instrumentation][STDOUT] 	at java.lang.reflect.Method.invoke(Native Method)
[Espresso] [Instrumentation][STDOUT] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
[Espresso] [Instrumentation][STDOUT] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
[JSONWP Proxy] Got an unexpected response: {"code":"ECONNRESET"}
[Espresso] Deleting espresso session
[ADB] Running '/Users/[redacted]/Library/Android/sdk/platform-tools/adb -P 5037 -s 23687718740b7ece shell am force-stop com.[redacted].[redacted].qa'
[Espresso] [Instrumentation][STDOUT] INSTRUMENTATION_RESULT: shortMsg=Process crashed.
[Espresso] [Instrumentation][STDOUT] INSTRUMENTATION_CODE: 0
[Espresso] Instrumentation process exited with code 0 from signal null
[Logcat] Stopping logcat capture
[ADB] Device API level: 28
[Espresso] Restoring hidden api policy to the device default configuration
[ADB] Running '/Users/[redacted]/Library/Android/sdk/platform-tools/adb -P 5037 -s 23687718740b7ece shell settings delete global hidden_api_policy_pre_p_apps'
[ADB] Running '/Users/[redacted]/Library/Android/sdk/platform-tools/adb -P 5037 -s 23687718740b7ece shell settings delete global hidden_api_policy_p_apps'
[ADB] Removing forwarded port socket connection: 8300 
[ADB] Running '/Users/[redacted]/Library/Android/sdk/platform-tools/adb -P 5037 -s 23687718740b7ece forward --remove tcp\:8300'
[BaseDriver] Event 'newSessionStarted' logged at 1554363699733 (09:41:39 GMT+0200 (SAST))
[W3C] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up
[W3C]     at JWProxy.command (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:236:13)
[HTTP] <-- POST /wd/hub/session 500 46981 ms - 543
[HTTP] 
```

**Comment by mykola-mokhnach** [comment]
https://stackoverflow.com/questions/29095063/resourcesnotfoundexception-resource-is-not-a-drawable-color-or-path

**Comment by FerdinandNell** [comment]
Thanks, gone through that one already with no luck. Could you provide more info around what the Instrumentation is doing that might be affected by updating SDK version on our side?

**Comment by jumois** [comment]
I'm facing this same issue. App launch fails to resource not found exception. App target SDK is also 28.

@FerdinandNell which version was it working before?

**Comment by FerdinandNell** [comment]
Seems to be resolved in the latest BETA, the version that was working before was v1.12.0 I believe. Now I have a different issue resolving app launch activities...

**Comment by mykola-mokhnach** [comment]
Closed as fixed
