### ISSUE TITLE
swipe:mobile for espresso driver not working.

### ISSUE THREAD

**Issue by poojachoudhary13** [appium/appium-espresso-driver#438]
I am trying to do swipe a button left to right using below script 
           ` browser.execute("mobile:swipe", {
                "element": "appPackage:id/swipe_btn", 
                "swiper": "SLOW",
                "startCoordinates": "BOTTOM_LEFT",
                "endCoordinates": "TOP_RIGHT",
                "precisionDescriber": "FINGER"
            })`
I tried using `elementId` too in `element` but no success as i can see in appium inspector the elementId for the button keeps changing. How to make this work?

**Errors** : `An unknown server-side error occurred while processing the command. Original error: No such route /session/7134a21e-92d8-457c-a845-7d2de5d7e3aa/appium/execute_mobile/appPackage:id/swipe_btn/swipe` 

OR  An unknown server-side error occurred while processing the command. Original error: java.util.NoSuchElementException: No such element with ID 'swipe_btn'
        at io.appium.espressoserver.lib.model.Element$Companion.getViewById(Element.kt:104)
        at io.appium.espressoserver.lib.model.Element$Companion.getViewInteractionById(Element.kt:64)
        at io.appium.espressoserver.lib.handlers.MobileSwipe.handle(MobileSwipe.kt:35)
        at io.appium.espressoserver.lib.handlers.MobileSwipe.handle(MobileSwipe.kt:30)
        at io.appium.espressoserver.lib.http.Router.route(Router.java:335)
        at io.appium.espressoserver.lib.http.Server.serve(Server.java:69)
        at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:945)
        at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
        at java.lang.Thread.run(Thread.java:764)

**Comment by poojachoudhary13** [comment]
not a bug

**Comment by ania-s** [comment]
@poojachoudhary13 how did you get it working?
