### ISSUE TITLE
POST `/alert/accept` fails for accepting Alert Dialogs

### ISSUE THREAD

**Issue by juandg** [appium/appium-espresso-driver#442]
So now that #414 has been fixed, I can use `GET /alert/text` to check for an alert being present but now if I try to accept the alert with `POST /alert/accept` then the call is failing with an exception.

This is the code I'm using on the client:

```python
wait = WebDriverWait(driver, 10)
alert = wait.until(expected_conditions.alert_is_present())
if alert:
    alert.accept()
```
Which works well with UIAutomator2 and XCUITest but with the Espresso driver I get this Java exception:

```java
java.lang.ClassCastException: io.appium.espressoserver.lib.model.AppiumParams cannot be cast to io.appium.espressoserver.lib.model.AlertParams
	at io.appium.espressoserver.lib.handlers.AcceptAlert.handle(AcceptAlert.kt:23)
	at io.appium.espressoserver.lib.http.Router.route(Router.java:335)
	at io.appium.espressoserver.lib.http.Server.serve(Server.java:69)
	at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:945)
	at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
	at java.lang.Thread.run(Thread.java:764)
```
Here's the relevant log with `alert/text` first and then `alert/accept`

```java
[HTTP] --> GET /wd/hub/session/e4c9634a-3172-41a3-9e91-619cd879dfcc/alert/text
[HTTP] {}
[W3C (e4c9634a)] Driver proxy active, passing request on via HTTP proxy
[debug] [WD Proxy] Matched '/wd/hub/session/e4c9634a-3172-41a3-9e91-619cd879dfcc/alert/text' to command name 'getAlertText'
[debug] [WD Proxy] Proxying [GET /wd/hub/session/e4c9634a-3172-41a3-9e91-619cd879dfcc/alert/text] to [GET http://localhost:8300/session/77b211b0-bded-4bdd-ae3a-8462ef933e5c/alert/text] with body: {}
[debug] [WD Proxy] Got response with status 200: "{\"id\":\"b1df9683-52ec-4d4e-8c30-5895c62fd23c\",\"sessionId\":\"77b211b0-bded-4bdd-ae3a-8462ef933e5c\",\"status\":0,\"value\":\"alert text"}"
[WD Proxy] Replacing sessionId 77b211b0-bded-4bdd-ae3a-8462ef933e5c with e4c9634a-3172-41a3-9e91-619cd879dfcc
[HTTP] <-- GET /wd/hub/session/e4c9634a-3172-41a3-9e91-619cd879dfcc/alert/text 200 1126 ms - 480
[HTTP]
[HTTP] --> POST /wd/hub/session/e4c9634a-3172-41a3-9e91-619cd879dfcc/alert/accept
[HTTP] {"sessionId":"e4c9634a-3172-41a3-9e91-619cd879dfcc"}
[W3C (e4c9634a)] Driver proxy active, passing request on via HTTP proxy
[debug] [WD Proxy] Matched '/wd/hub/session/e4c9634a-3172-41a3-9e91-619cd879dfcc/alert/accept' to command name 'postAcceptAlert'
[debug] [WD Proxy] Proxying [POST /wd/hub/session/e4c9634a-3172-41a3-9e91-619cd879dfcc/alert/accept] to [POST http://localhost:8300/session/77b211b0-bded-4bdd-ae3a-8462ef933e5c/alert/accept] with body: {"sessionId":"e4c9634a-3172-41a3-9e91-619cd879dfcc"}
[WD Proxy] Got an unexpected response: {"id":"3c1c8ece-c071-4561-b104-4dc9e6283c95","sessionId":null,"status":13,"value":"java.lang.ClassCastException: io.appium.espressoserver.lib.model.AppiumParams cannot be cast to io.appium.espressoserver.lib.model.AlertParams\n\tat io.appium.espressoserver.lib.handlers.AcceptAlert.handle(AcceptAl...
[debug] [W3C (e4c9634a)] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: 500 - {"id":"3c1c8ece-c071-4561-b104-4dc9e6283c95","sessionId":null,"status":13,"value":"java.lang.ClassCastException: io.appium.espressoserver.lib.model.AppiumParams cannot be cast to io.appium.espressoserver.lib.model.AlertParams\n\tat io.appium.espressoserver.lib.handlers.AcceptAlert.handle(AcceptAlert.kt:23)\n\tat io.appium.espressoserver.lib.http.Router.route(Router.java:335)\n\tat io.appium.espressoserver.lib.http.Server.serve(Server.java:69)\n\tat fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:945)\n\tat fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)\n\tat java.lang.Thread.run(Thread.java:764)\n"}
[debug] [W3C (e4c9634a)]     at JWProxy.proxy (/Users/gomezju/git/appium-espresso-driver/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:181:13)
[debug] [W3C (e4c9634a)]     at <anonymous>
[debug] [MJSONWP] Matched JSONWP error code 13 to UnknownError
[HTTP] <-- POST /wd/hub/session/e4c9634a-3172-41a3-9e91-619cd879dfcc/alert/accept 500 29 ms - 1795
```

and here's an example of the same calls succeeding on UIAutomator2:

```java
[HTTP] --> GET /wd/hub/session/09969315-1987-4d81-b1e1-cd5441b81167/alert/text
[HTTP] {}
[debug] [W3C (09969315)] Calling AppiumDriver.getAlertText() with args: ["09969315-1987-4d81-b1e1-cd5441b81167"]
[debug] [WD Proxy] Matched '/alert/text' to command name 'getAlertText'
[debug] [WD Proxy] Proxying [GET /alert/text] to [GET http://localhost:8201/wd/hub/session/66ea72bb-1c5e-4354-b29b-537acf0046e4/alert/text] with body: {}
[debug] [WD Proxy] Got response with status 200: "{\"sessionId\":\"66ea72bb-1c5e-4354-b29b-537acf0046e4\",\"status\":0,\"value\":\"alert text"}"
[debug] [W3C (09969315)] Responding to client with driver.getAlertText() result: "alert text"
[HTTP] <-- GET /wd/hub/session/09969315-1987-4d81-b1e1-cd5441b81167/alert/text 200 378 ms - 374
[HTTP]
[HTTP] --> POST /wd/hub/session/09969315-1987-4d81-b1e1-cd5441b81167/alert/accept
[HTTP] {"sessionId":"09969315-1987-4d81-b1e1-cd5441b81167"}
[debug] [W3C (09969315)] Calling AppiumDriver.postAcceptAlert() with args: ["09969315-1987-4d81-b1e1-cd5441b81167"]
[debug] [WD Proxy] Matched '/alert/accept' to command name 'postAcceptAlert'
[debug] [WD Proxy] Proxying [POST /alert/accept] to [POST http://localhost:8201/wd/hub/session/66ea72bb-1c5e-4354-b29b-537acf0046e4/alert/accept] with body: {}
[debug] [WD Proxy] Got response with status 200: {"sessionId":"66ea72bb-1c5e-4354-b29b-537acf0046e4","status":0,"value":"The command executed successfully."}
[debug] [W3C (09969315)] Responding to client with driver.postAcceptAlert() result: "The command executed successfully."
[HTTP] <-- POST /wd/hub/session/09969315-1987-4d81-b1e1-cd5441b81167/alert/accept 200 78 ms - 46
```

**Comment by mykola-mokhnach** [comment]
Please check if https://github.com/appium/appium-espresso-driver/pull/443 resolves the problem for you

**Comment by juandg** [comment]
Thanks @mykola-mokhnach for jumping in on this so quickly. You're a rockstar 🎉

This indeed fixed the issue with `POST /alert/accept` and everything works now. Here's the log just in case:

```java
[HTTP] --> GET /wd/hub/session/1a0080d8-f9a2-4127-bc83-78e148bc7f4b/alert/text
[HTTP] {}
[W3C (1a0080d8)] Driver proxy active, passing request on via HTTP proxy
[debug] [WD Proxy] Matched '/wd/hub/session/1a0080d8-f9a2-4127-bc83-78e148bc7f4b/alert/text' to command name 'getAlertText'
[debug] [WD Proxy] Proxying [GET /wd/hub/session/1a0080d8-f9a2-4127-bc83-78e148bc7f4b/alert/text] to [GET http://localhost:8300/session/4c4e274c-4aaa-4676-8566-1a83b71c36e1/alert/text] with body: {}
[debug] [WD Proxy] Got response with status 200: "{\"id\":\"fad99a9c-b991-4fc8-945f-1a7b9b3b550f\",\"sessionId\":\"4c4e274c-4aaa-4676-8566-1a83b71c36e1\",\"status\":0,\"value\":\"alert text"}"
[WD Proxy] Replacing sessionId 4c4e274c-4aaa-4676-8566-1a83b71c36e1 with 1a0080d8-f9a2-4127-bc83-78e148bc7f4b
[HTTP] <-- GET /wd/hub/session/1a0080d8-f9a2-4127-bc83-78e148bc7f4b/alert/text 200 1196 ms - 480
[HTTP]
[HTTP] --> POST /wd/hub/session/1a0080d8-f9a2-4127-bc83-78e148bc7f4b/alert/accept
[HTTP] {"sessionId":"1a0080d8-f9a2-4127-bc83-78e148bc7f4b"}
[W3C (1a0080d8)] Driver proxy active, passing request on via HTTP proxy
[debug] [WD Proxy] Matched '/wd/hub/session/1a0080d8-f9a2-4127-bc83-78e148bc7f4b/alert/accept' to command name 'postAcceptAlert'
[debug] [WD Proxy] Proxying [POST /wd/hub/session/1a0080d8-f9a2-4127-bc83-78e148bc7f4b/alert/accept] to [POST http://localhost:8300/session/4c4e274c-4aaa-4676-8566-1a83b71c36e1/alert/accept] with body: {"sessionId":"1a0080d8-f9a2-4127-bc83-78e148bc7f4b"}
[debug] [WD Proxy] Got response with status 200: {"id":"b601a89e-7dfb-4a82-bba0-d26dab0f173d","sessionId":"4c4e274c-4aaa-4676-8566-1a83b71c36e1","status":0,"value":null}
[WD Proxy] Replacing sessionId 4c4e274c-4aaa-4676-8566-1a83b71c36e1 with 1a0080d8-f9a2-4127-bc83-78e148bc7f4b
[HTTP] <-- POST /wd/hub/session/1a0080d8-f9a2-4127-bc83-78e148bc7f4b/alert/accept 200 121 ms - 120
[HTTP]
[HTTP] --> POST /wd/hub/session/1a0080d8-f9a2-4127-bc83-78e148bc7f4b/element
```
