### ISSUE TITLE
Espresso selectors don't return expected values

### ISSUE THREAD

**Issue by Ludobaka** [appium/appium-espresso-driver#445]
# Software
* appium 1.12.1
* appium-espresso-driver 1.11.0

# Problem presentation

When using native Espresso tests for my mobile application, I'm calling `onData` and `onView` like :
```
onData(withId(myViewId))
onView(withId(myViewId))
```
with `myViewId` either equals to `R.id.viewId` or `"com.mynamespace.myapp:id/viewId"`

When trying to send an Espresso request to the Appium server, I'm never able to get a response from the server.

I've read the [Espresso datamatcher Selector](https://appium.io/docs/en/writing-running-appium/android/espresso-datamatcher-selector/) and followed the instruction by using the following Java calls that leads to the followed exceptions on the client :
```
driver.findElementByAndroidDataMatcher(
    "{" +
        "'name': 'withId'," +
        "'args': 'com.mynamespace.myapp:id/viewId' +
    "}"
); /* org.openqa.selenium.InvalidSelectorException:
io.appium.espressoserver.lib.handlers.exceptions.InvalidStrategyException:
Not a valid selector '{'name': 'withId','args': 'com.mynamespace.myapp:id/viewId'}'.
Reason: 'null' */
driver.findElementByAndroidViewMatcher(
    "{" +
        "'name': 'withId'," +
        "'args': 'com.mynamespace.myapp:id/viewId' +
    "}"
); /* org.openqa.selenium.NoSuchElementException:
io.appium.espressoserver.lib.handlers.exceptions.NoSuchElementException:
Could not find element with strategy VIEW_TAG and selector
{'name': 'withId','args': 'com.mynamespace.myapp:id/viewId'} */
```

I assumed after reading the documentation and some PR here that only `DataMatcher` was implemented on the Espresso drivers, however, the `DataMatcher` selector is not working and the `ViewMatcher` selector is send to the server but the driver is not able to find the view with the specified ID.

I just started using Appium and those Espresso drivers, but I'm available for more details or even for contribution if someone can lead me a bit.

Thanks !

**Comment by dpgraham** [comment]
Which client are you using? Can I see the logs? Looks like the client isn't setting the correct selector strategy (for the data matcher)

As for the view matcher, we haven't actually implemented an `onView` selector.... what that does is it selects element by VIEW_TAG.

**Comment by Ludobaka** [comment]
I'm using java-client on the commit 5a17759b05d6fda8ef425b3ab6e766c73ed2e8df (previously HEAD of master, a new commit was added yesterday). I've also tried with v7.0.0.

Here are the logs from the server :
```
[HTTP] --> POST /wd/hub/session/42e62538-8e54-40c8-903b-1494e369f8ca/element
[HTTP] {"using":"-android datamatcher","value":"{'name': 'withId','args': '2131297055'}"}
[W3C (42e62538)] Driver proxy active, passing request on via HTTP proxy
[debug] [WD Proxy] Matched '/wd/hub/session/42e62538-8e54-40c8-903b-1494e369f8ca/element' to command name 'findElement'
[debug] [WD Proxy] Proxying [POST /wd/hub/session/42e62538-8e54-40c8-903b-1494e369f8ca/element] to [POST http://localhost:8300/session/852af457-359a-4cfc-a1f5-3c59801d3af6/element] with body: {"using":"-android datamatcher","value":"{'name': 'withId','args': '2131297055'}"}
[WD Proxy] Got an unexpected response: {"id":"fe696534-de0e-40eb-86fd-bfef19f79f2f","sessionId":null,"status":32,"value":"io.appium.espressoserver.lib.handlers.exceptions.InvalidStrategyException: Not a valid selector '{'name': 'withId','args': '2131297055'}'. Reason: 'null'\n\tat io.appium.espressoserver.lib.model.DataMatcherJson$Com...
[debug] [W3C (42e62538)] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: 500 - {"id":"fe696534-de0e-40eb-86fd-bfef19f79f2f","sessionId":null,"status":32,"value":"io.appium.espressoserver.lib.handlers.exceptions.InvalidStrategyException: Not a valid selector '{'name': 'withId','args': '2131297055'}'. Reason: 'null'\n\tat io.appium.espressoserver.lib.model.DataMatcherJson$Companion.fromJson(DataMatcherJson.kt:26)\n\tat io.appium.espressoserver.lib.helpers.ViewFinder.findAllBy(ViewFinder.java:196)\n\tat io.appium.espressoserver.lib.helpers.ViewFinder.findBy(ViewFinder.java:93)\n\tat io.appium.espressoserver.lib.handlers.FindElement.handle(FindElement.kt:45)\n\tat io.appium.espressoserver.lib.handlers.FindElement.handle(FindElement.kt:31)\n\tat io.appium.espressoserver.lib.http.Router.route(Router.java:335)\n\tat io.appium.espressoserver.lib.http.Server.serve(Server.java:69)\n\tat fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:945)\n\tat fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)\n\tat java.lang.Thread.run(Thread.java:762)\n"}
[debug] [W3C (42e62538)]     at JWProxy.proxy (/home/ludovic/.npm-global/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:180:13)
[debug] [MJSONWP] Matched JSONWP error code 32 to InvalidSelectorError
[HTTP] <-- POST /wd/hub/session/42e62538-8e54-40c8-903b-1494e369f8ca/element 400 448 ms - 2374
```
Here are the logs from the client :
```
May 07, 2019 10:30:49 AM io.appium.java_client.remote.AppiumCommandExecutor$1 lambda$0
INFO: Detected dialect: W3C

org.openqa.selenium.InvalidSelectorException: io.appium.espressoserver.lib.handlers.exceptions.InvalidStrategyException: Not a valid selector '{'name': 'withId','args': '2131297055'}'. Reason: 'null'
	at io.appium.espressoserver.lib.model.DataMatcherJson$Companion.fromJson(DataMatcherJson.kt:26)
	at io.appium.espressoserver.lib.helpers.ViewFinder.findAllBy(ViewFinder.java:196)
	at io.appium.espressoserver.lib.helpers.ViewFinder.findBy(ViewFinder.java:93)
	at io.appium.espressoserver.lib.handlers.FindElement.handle(FindElement.kt:45)
	at io.appium.espressoserver.lib.handlers.FindElement.handle(FindElement.kt:31)
	at io.appium.espressoserver.lib.http.Router.route(Router.java:335)
	at io.appium.espressoserver.lib.http.Server.serve(Server.java:69)
	at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:945)
	at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
	at java.lang.Thread.run(Thread.java:762)

For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/invalid_selector_exception.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'sun-tzu', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-48-generic', java.version: '11.0.2'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities {app: /home/ludovic/Dev/myAppiumT..., appActivity: activities.welcome.SplashSc..., appPackage: com.mynamespace.myapp, autoGrantPermissions: true, automationName: Espresso, deviceName: Android, javascriptEnabled: true, platform: ANDROID, platformName: Android, resetKeyboard: true, unicodeKeyboard: true}
Session ID: 42e62538-8e54-40c8-903b-1494e369f8ca
*** Element info: {Using=-android datamatcher, value={'name': 'withId','args': '2131297055'}}

	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:323)
	at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:61)
	at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.findElement(AndroidDriver.java:1)
	at io.appium.java_client.FindsByAndroidDataMatcher.findElementByAndroidDataMatcher(FindsByAndroidDataMatcher.java:26)
	at pages.LoginPage.enterInvalidEmailTest(LoginPage.java:62)
	at scenarios.AppiumTest.test(AppiumTest.java:30)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
```

**Comment by dpgraham** [comment]
This looks like a bug. Thanks for submitting this. I'll try to find time to look at it. 

Something is happening at `DataMatcherJson.kt:` that's causing it not parse the selector correctly.... I'd be curious if this is happening with other clients (Webdriver.IO perhaps?)

**Comment by mykola-mokhnach** [comment]
> driver.findElementByAndroidDataMatcher(
>     "{" +
>         "'name': 'withId'," +
>         "'args': 'com.mynamespace.myapp:id/viewId' +
>     "}"
> );

This JSON is incorrect. Use JSONObject's toString method in order to properly convert objects to string representation

**Comment by dpgraham** [comment]
Closing. Will re-open if problem persists.
