### ISSUE TITLE
Backdoor on target element fails: Cannot find 'null' element

### ISSUE THREAD

**Issue by TomBAMU** [appium/appium-espresso-driver#453]
I'm using the current appium beta version. 

I tried to retrieve the text color of a textview by using "mobile:backdoor" script with the espresso driver. Unfortunately I am running into a InvalidArgumentException.

I'm not sure why, since the arguments contain an elementId.

Code to reproduce
```
Map<String, Object> args = new HashMap<String, Object>() {{
            put("target", "element");
            put("elementId", element.getId());
            put("methods", Collections.singletonList(ImmutableMap.of(
                    "name", "hasTextColor"
            )));
        }};
androidDriver.executeScript("mobile:backdoor", args);
```

The server log:
```
debug] [WD Proxy] Matched '/wd/hub/session/f3b2c06c-ea39-49d6-a6a0-8fd4ed985c4a/element' to command name 'findElement'
[debug] [WD Proxy] Proxying [POST /wd/hub/session/f3b2c06c-ea39-49d6-a6a0-8fd4ed985c4a/element] to [POST http://localhost:8012/session/1203e6be-db68-4b6d-95f5-efa5bb869c49/element] with body: {"using":"xpath","value":"//*[@text='74162103620129']"}
[debug] [WD Proxy] Got response with status 200: {"id":"d0da4986-163c-4e55-ad75-f46b5ae9a47e","sessionId":"1203e6be-db68-4b6d-95f5-efa5bb869c49","status":0,"value":{"ELEMENT":"03dfa766-a73d-44bd-81a6-d81c809a4791"}}
[WD Proxy] Replacing sessionId 1203e6be-db68-4b6d-95f5-efa5bb869c49 with f3b2c06c-ea39-49d6-a6a0-8fd4ed985c4a
[HTTP] <-- POST /wd/hub/session/f3b2c06c-ea39-49d6-a6a0-8fd4ed985c4a/element 200 740 ms - 166
[HTTP]
[HTTP] --> GET /wd/hub/session/f3b2c06c-ea39-49d6-a6a0-8fd4ed985c4a/element/03dfa766-a73d-44bd-81a6-d81c809a4791/location
[HTTP] {}
[W3C (f3b2c06c)] Driver proxy active, passing request on via HTTP proxy
[debug] [WD Proxy] Matched '/wd/hub/session/f3b2c06c-ea39-49d6-a6a0-8fd4ed985c4a/element/03dfa766-a73d-44bd-81a6-d81c809a4791/location' to command name 'getLocation'
[debug] [WD Proxy] Proxying [GET /wd/hub/session/f3b2c06c-ea39-49d6-a6a0-8fd4ed985c4a/element/03dfa766-a73d-44bd-81a6-d81c809a4791/location] to [GET http://localhost:8012/session/1203e6be-db68-4b6d-95f5-efa5bb869c49/element/03dfa766-a73d-44bd-81a6-d81c809a4791/location] with body: {}
[debug] [WD Proxy] Got response with status 200: "{\"id\":\"3bca167b-6bfc-43e4-989f-8453443a78e4\",\"sessionId\":\"1203e6be-db68-4b6d-95f5-efa5bb869c49\",\"status\":0,\"value\":{\"x\":98,\"y\":483,\"uriParams\":null}}"
[WD Proxy] Replacing sessionId 1203e6be-db68-4b6d-95f5-efa5bb869c49 with f3b2c06c-ea39-49d6-a6a0-8fd4ed985c4a
[HTTP] <-- GET /wd/hub/session/f3b2c06c-ea39-49d6-a6a0-8fd4ed985c4a/element/03dfa766-a73d-44bd-81a6-d81c809a4791/location 200 30 ms - 149
[HTTP]
[HTTP] --> GET /wd/hub/session/f3b2c06c-ea39-49d6-a6a0-8fd4ed985c4a/element/03dfa766-a73d-44bd-81a6-d81c809a4791/size
[HTTP] {}
[W3C (f3b2c06c)] Driver proxy active, passing request on via HTTP proxy
[debug] [WD Proxy] Matched '/wd/hub/session/f3b2c06c-ea39-49d6-a6a0-8fd4ed985c4a/element/03dfa766-a73d-44bd-81a6-d81c809a4791/size' to command name 'getSize'
[debug] [WD Proxy] Proxying [GET /wd/hub/session/f3b2c06c-ea39-49d6-a6a0-8fd4ed985c4a/element/03dfa766-a73d-44bd-81a6-d81c809a4791/size] to [GET http://localhost:8012/session/1203e6be-db68-4b6d-95f5-efa5bb869c49/element/03dfa766-a73d-44bd-81a6-d81c809a4791/size] with body: {}
[debug] [WD Proxy] Got response with status 200: "{\"id\":\"8e4086db-7428-4dcf-bff5-82220165678a\",\"sessionId\":\"1203e6be-db68-4b6d-95f5-efa5bb869c49\",\"status\":0,\"value\":{\"height\":49,\"width\":378,\"uriParams\":null}}"
[WD Proxy] Replacing sessionId 1203e6be-db68-4b6d-95f5-efa5bb869c49 with f3b2c06c-ea39-49d6-a6a0-8fd4ed985c4a
[HTTP] <-- GET /wd/hub/session/f3b2c06c-ea39-49d6-a6a0-8fd4ed985c4a/element/03dfa766-a73d-44bd-81a6-d81c809a4791/size 200 28 ms - 158
[HTTP]
[HTTP] --> POST /wd/hub/session/f3b2c06c-ea39-49d6-a6a0-8fd4ed985c4a/execute/sync
[HTTP] {"script":"mobile:backdoor","args":[{"elementId":"03dfa766-a73d-44bd-81a6-d81c809a4791","methods":[{"name":"getTypeface"}],"target":"element"}]}
[debug] [W3C (f3b2c06c)] Calling AppiumDriver.execute() with args: ["mobile:backdoor",[{"elementId":"03dfa766-a73d-44bd-81a6-d81c809a4791","methods":[{"name":"getTypeface"}],"target":"element"}],"f3b2c06c-ea39-49d6-a6a0-8fd4ed985c4a"]
[AndroidDriver] Executing native command 'mobile:backdoor'
[debug] [WD Proxy] Proxying [POST /appium/execute_mobile/backdoor] to [POST http://localhost:8012/session/1203e6be-db68-4b6d-95f5-efa5bb869c49/appium/execute_mobile/backdoor] with body: {"target":"element","methods":[{"name":"getTypeface"}],"elementId":"03dfa766-a73d-44bd-81a6-d81c809a4791"}
[WD Proxy] Got an unexpected response: {"id":"88af0a9e-6d91-4033-9e2d-d6a9ec0d01fb","sessionId":null,"status":61,"value":"io.appium.espressoserver.lib.handlers.exceptions.InvalidArgumentException: Cannot find 'null' element\n\tat io.appium.espressoserver.lib.model.Element$Companion.getViewById(Element.kt:102)\n\tat io.appium.espressos...
[debug] [MJSONWP] Matched JSONWP error code 61 to InvalidArgumentError
[debug] [W3C (f3b2c06c)] Encountered internal error running command: InvalidArgumentError: io.appium.espressoserver.lib.handlers.exceptions.InvalidArgumentException: Cannot find 'null' element
[debug] [W3C (f3b2c06c)]        at io.appium.espressoserver.lib.model.Element$Companion.getViewById(Element.kt:102)
[debug] [W3C (f3b2c06c)]        at io.appium.espressoserver.lib.handlers.MobileBackdoor.handle(MobileBackdoor.kt:24)
[debug] [W3C (f3b2c06c)]        at io.appium.espressoserver.lib.handlers.MobileBackdoor.handle(MobileBackdoor.kt:12)
[debug] [W3C (f3b2c06c)]        at io.appium.espressoserver.lib.http.Router.route(Router.java:335)
[debug] [W3C (f3b2c06c)]        at io.appium.espressoserver.lib.http.Server.serve(Server.java:69)
[debug] [W3C (f3b2c06c)]        at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:945)
[debug] [W3C (f3b2c06c)]        at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
[debug] [W3C (f3b2c06c)]        at java.lang.Thread.run(Thread.java:818)
[debug] [W3C (f3b2c06c)]
[debug] [W3C (f3b2c06c)]     at errorFromMJSONWPStatusCode (...\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:786:12)
[debug] [W3C (f3b2c06c)]     at ProxyRequestError.errorFromMJSONWPStatusCode [as getActualError] (...\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:683:14)
[debug] [W3C (f3b2c06c)]     at JWProxy.getActualError [as command] (...\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\jsonwp-proxy\proxy.js:237:19)
[HTTP] <-- POST /wd/hub/session/f3b2c06c-ea39-49d6-a6a0-8fd4ed985c4a/execute/sync 400 55 ms - 2035
```

Would be great if someone could give me a hint on the "null" element here ;-) Do I execute it with the wrong arguments?

**Comment by rajdeepv** [comment]
Looks like a bug. @dpgraham looks like its regression due to renaming "elementId" to "targetElement" 
It works fine with old espresso driver
