### ISSUE TITLE
[RN 0.59] New Session fails with error: socket hang up

### ISSUE THREAD

**Issue by juandg** [appium/appium-espresso-driver#461]
**UPDATE:** _I triaged this a little better and this coincided with our app's move to react-native 0.59 so I went back and re-tested our old app with the espresso driver 1.13.0 and it works fine so this issue is not related to the changes between 1.12.0 and 1.13.0 but rather on our move to RN 0.59 and I've updated the issue description accordingly_

~~There seems to have been a change between 1.12.0 when #441 was merged and 1.13.0 that broke our ability to install our app and create a new session.~~

~~I tried running my suite that was working fine on version 1.12.0 after issue #439 was resolved and I find that it now fails with this error:~~

Ever since we upgraded our react-native app from RN 0.56 to RN 0.59 our Appium test suite using the espresso driver is failing to start a new session.

Everything works fine with `UIAutomator` and `UIAutomator2` but as soon as I switch to Espresso then I get this error:

```java
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1560989726037 (17:15:26 GMT-0700 (PDT))
[debug] [W3C] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up
[debug] [W3C]     at JWProxy.command (/Users/someuser/git/appium-espresso-driver/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:239:13)
[debug] [W3C]     at <anonymous>
[HTTP] <-- POST /wd/hub/session 500 7865 ms - 557
```
These are the capabilities I'm using:

```python
caps = {
  "platformName": "Android",
  "appActivity": "com.example.MyApp.MainActivity",
  "appPackage": "com.example.enterpriseapp",
  "app": "https://server.example.com/MobileApp/job/build/MyTestApp.apk",
  "avd": "Pixel_2_API_28",
  "deviceName": "Android Emulator",
  "automationName": "espresso"
}
```
I've tried using ``` 'forceEspressoRebuild': 'true'``` as well as uninstalling the app beforehand but nothing seems to make a difference and I keep getting this error.

Here's the full appium log:

```java
[Appium] Welcome to Appium v1.14.0-beta.1 (REV dba3a87c54b0507bd40fc9dba759949978381ce3)
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"capabilities":{"firstMatch":[{"platformName":"Android","appium:appActivity":"com.example.MyApp.MainActivity","appium:appPackage":"com.example.enterpriseapp","appium:app":"https://server.example.com/MobileApp/job/build/MyTestApp.apk","appium:avd":"Pixel_2_API_28","appium:deviceName":"Android Emulator","appium:platformVersion":"9.0","appium:automationName":"espresso"}]},"desiredCapabilities":{"platformName":"Android","appActivity":"com.example.MyApp.MainActivity","appPackage":"com.example.enterpriseapp","app":"https://server.example.com/MobileApp/job/build/MyTestApp.apk","avd":"Pixel_2_API_28","deviceName":"Android Emulator","platformVersion":"9.0","automationName":"espresso"}}
[debug] [W3C] Calling AppiumDriver.createSession() with args: [{"platformName":"Android","appActivity":"com.example.MyApp.MainActivity","appPackage":"com.example.enterpriseapp","app":"https://server.example.com/MobileApp/job/build/MyTestApp.apk","avd":"Pixel_2_API_28","deviceName":"Android Emulator","platformVersion":"9.0","automationName":"espresso"},null,{"firstMatch":[{"platformName":"Android","appium:appActivity":"com.example.MyApp.MainActivity","appium:appPackage":"com.example.enterpriseapp","appium:app":"https://server.example.com/MobileApp/job/build/MyTestApp.apk","appium:avd":"Pixel_2_API_28","appium:deviceName":"Android Emulator","appium:platformVersion":"9.0","appium:automationName":"espresso"}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1560989718175 (17:15:18 GMT-0700 (PDT))
[Appium] Appium v1.14.0-beta.1 creating new EspressoDriver (v1.13.0) session
[Appium] Capabilities:
[Appium]   platformName: Android
[Appium]   appActivity: com.example.MyApp.MainActivity
[Appium]   appPackage: com.example.enterpriseapp
[Appium]   app: https://server.example.com/MobileApp/job/build/MyTestApp.apk
[Appium]   avd: Pixel_2_API_28
[Appium]   deviceName: Android Emulator
[Appium]   platformVersion: 9.0
[Appium]   automationName: espresso
[debug] [BaseDriver] W3C capabilities {"alwaysMatch":{"platformNa... and MJSONWP desired capabilities {"platformName":"Android","... were provided
[debug] [BaseDriver] Creating session with W3C capabilities: {"alwaysMatch":{"platformNa...
[BaseDriver] Session created with session id: 257df611-9579-4327-8931-9ab7775835ea
[BaseDriver] Using downloadable app 'https://server.example.com/MobileApp/job/build/MyTestApp.apk'
[debug] [BaseDriver] Last-Modified: Wed, 19 Jun 2019 09:33:27 GMT
[debug] [BaseDriver] Reusing already downloaded application at '/var/folders/h9/c658z4xs62v1zjkymcxq5dwh15hrn3/T/2019519-20710-1n4bxof.de6c/MyTestApp.apk'
[BaseDriver] Reusing the previously downloaded application at '/var/folders/h9/c658z4xs62v1zjkymcxq5dwh15hrn3/T/2019519-20710-1n4bxof.de6c/MyTestApp.apk'
[debug] [Espresso] Checking whether app is actually present
[Espresso] EspressoDriver version: 1.13.0
[ADB] Using 'adb' from '/Users/someuser/Library/Android/sdk/platform-tools/adb'
[debug] [ADB] Trying to find 'Pixel_2_API_28' emulator
[debug] [ADB] Getting connected emulators
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] 1 emulator(s) connected
[debug] [ADB] Sending telnet command to device: avd name
[debug] [ADB] Getting running emulator port
[debug] [ADB] Socket connection to device created
[debug] [ADB] Socket connection to device ready
[debug] [ADB] Telnet command got response: Pixel_2_API_28
[debug] [ADB] Found emulator 'Pixel_2_API_28' on port 5554
[debug] [ADB] Setting device id to emulator-5554
[debug] [AndroidDriver] Not launching AVD because it is already running.
[AndroidDriver] Using device: emulator-5554
[ADB] Using 'adb' from '/Users/someuser/Library/Android/sdk/platform-tools/adb' 
[debug] [ADB] Setting device id to emulator-5554
[debug] [ADB] Running '/Users/someuser/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell getprop ro.build.version.sdk'
[debug] [ADB] Current device property 'ro.build.version.sdk': 28
[debug] [ADB] Running '/Users/someuser/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell getprop ro.build.version.release'
[debug] [ADB] Current device property 'ro.build.version.release': 9
[debug] [ADB] Device API level: 28
[Espresso] Relaxing hidden api policy
[debug] [ADB] Running '/Users/someuser/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell settings put global hidden_api_policy_pre_p_apps 1'
[debug] [ADB] Running '/Users/someuser/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell settings put global hidden_api_policy_p_apps 1'
[debug] [ADB] Running '/Users/someuser/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell settings put global hidden_api_policy 1'
[debug] [ADB] Running '/Users/someuser/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 wait-for-device'
[debug] [ADB] Running '/Users/someuser/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell echo ping'
[debug] [AndroidDriver] Pushing settings apk to device...
[debug] [ADB] Getting install status for io.appium.settings
[debug] [ADB] Running '/Users/someuser/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys package io.appium.settings'
[debug] [ADB] 'io.appium.settings' is installed
[debug] [ADB] Getting package info for 'io.appium.settings'
[debug] [ADB] Running '/Users/someuser/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys package io.appium.settings'
[ADB] Using 'aapt' from '/Users/someuser/Library/Android/sdk/build-tools/28.0.3/aapt'
[debug] [ADB] The version name of the installed 'io.appium.settings' is greater or equal to the application version name ('2.14.0' >= '2.14.0')
[debug] [ADB] There is no need to install/upgrade '/Users/someuser/git/appium-espresso-driver/node_modules/io.appium.settings/apks/settings_apk-debug.apk'
[debug] [ADB] Getting IDs of all 'io.appium.settings' processes
[debug] [ADB] Running '/Users/someuser/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell 'pgrep --help; echo $?''
[debug] [ADB] Running '/Users/someuser/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell pgrep -f io\\.appium\\.settings'
[debug] [AndroidDriver] io.appium.settings is already running. There is no need to reset its permissions.
[debug] [Logcat] Starting logcat capture
[debug] [ADB] Running '/Users/someuser/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell settings get global animator_duration_scale'
[debug] [ADB] Running '/Users/someuser/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell settings get global transition_animation_scale'
[debug] [ADB] Running '/Users/someuser/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell settings get global window_animation_scale'
[debug] [Espresso] Forwarding Espresso Server port 6791 to 8301
[debug] [ADB] Forwarding system: 8301 to device: 6791
[debug] [ADB] Running '/Users/someuser/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 forward tcp\:8301 tcp\:6791'
[debug] [ADB] Running '/Users/someuser/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys window'
[AndroidDriver] Screen already unlocked, doing nothing
[debug] [ADB] Checking app cert for /var/folders/h9/c658z4xs62v1zjkymcxq5dwh15hrn3/T/2019519-20710-1n4bxof.de6c/MyTestApp.apk
[ADB] Using 'apksigner' from '/Users/someuser/Library/Android/sdk/build-tools/28.0.3/apksigner'
[debug] [ADB] Starting '/Users/someuser/Library/Android/sdk/build-tools/28.0.3/apksigner' with args '["verify","--print-certs","/var/folders/h9/c658z4xs62v1zjkymcxq5dwh15hrn3/T/2019519-20710-1n4bxof.de6c/MyTestApp.apk"]'
[debug] [ADB] apksigner stdout: Signer #1 certificate DN: EMAILADDRESS=android@android.com, CN=Android, OU=Android, O=Android, L=Mountain View, ST=California, C=US
[debug] [ADB] Signer #1 certificate SHA-256 digest: a40da80a59d170caa950cf15c18c454d47a39b26989d8b640ecd745ba71bf5dc
[debug] [ADB] Signer #1 certificate SHA-1 digest: 61ed377e85d386a8dfee6b864bd85b0bfaa5af81
[debug] [ADB] Signer #1 certificate MD5 digest: e89b158e4bcf988ebd09eb83f5378e87
[debug] [ADB]
[debug] [ADB] '/var/folders/h9/c658z4xs62v1zjkymcxq5dwh15hrn3/T/2019519-20710-1n4bxof.de6c/MyTestApp.apk' is already signed.
[debug] [ADB] Getting install status for com.example.enterpriseapp
[debug] [ADB] Running '/Users/someuser/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys package com.example.enterpriseapp'
[debug] [ADB] 'com.example.enterpriseapp' is installed
[debug] [ADB] Getting install status for com.example.enterpriseapp
[debug] [ADB] Running '/Users/someuser/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys package com.example.enterpriseapp'
[debug] [ADB] 'com.example.enterpriseapp' is installed
[debug] [ADB] Getting package info for 'com.example.enterpriseapp'
[debug] [ADB] Running '/Users/someuser/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys package com.example.enterpriseapp'
[debug] [ADB] The version name of the installed 'com.example.enterpriseapp' is greater or equal to the application version name ('3.8.6' >= '3.8.6')
[debug] [ADB] There is no need to install/upgrade '/var/folders/h9/c658z4xs62v1zjkymcxq5dwh15hrn3/T/2019519-20710-1n4bxof.de6c/MyTestApp.apk'
[AndroidDriver] Performing fast reset on 'com.example.enterpriseapp'
[debug] [ADB] Getting install status for com.example.enterpriseapp
[debug] [ADB] Running '/Users/someuser/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys package com.example.enterpriseapp'
[debug] [ADB] 'com.example.enterpriseapp' is installed
[debug] [ADB] Running '/Users/someuser/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am force-stop com.example.enterpriseapp'
[debug] [ADB] Running '/Users/someuser/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell pm clear com.example.enterpriseapp'
[debug] [AndroidDriver] Performed fast reset on the installed 'com.example.enterpriseapp' application (stop and clear)
[debug] [ADB] Running '/Users/someuser/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell ls /data/local/tmp/espresso.apppackage'
[debug] [ADB] Running '/Users/someuser/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell cat /data/local/tmp/espresso.apppackage'
[debug] [Espresso] The previous target application package was 'com.example.enterpriseapp'. The current package is 'com.example.enterpriseapp'
[debug] [ADB] Checking app cert for /var/folders/h9/c658z4xs62v1zjkymcxq5dwh15hrn3/T/io.appium.espressoserver.test_1.13.0_com.example.enterpriseapp.apk
[debug] [ADB] Starting '/Users/someuser/Library/Android/sdk/build-tools/28.0.3/apksigner' with args '["verify","--print-certs","/var/folders/h9/c658z4xs62v1zjkymcxq5dwh15hrn3/T/io.appium.espressoserver.test_1.13.0_com.example.enterpriseapp.apk"]'
[debug] [ADB] apksigner stdout: Signer #1 certificate DN: EMAILADDRESS=android@android.com, CN=Android, OU=Android, O=Android, L=Mountain View, ST=California, C=US
[debug] [ADB] Signer #1 certificate SHA-256 digest: a40da80a59d170caa950cf15c18c454d47a39b26989d8b640ecd745ba71bf5dc
[debug] [ADB] Signer #1 certificate SHA-1 digest: 61ed377e85d386a8dfee6b864bd85b0bfaa5af81
[debug] [ADB] Signer #1 certificate MD5 digest: e89b158e4bcf988ebd09eb83f5378e87
[debug] [ADB]
[debug] [ADB] '/var/folders/h9/c658z4xs62v1zjkymcxq5dwh15hrn3/T/io.appium.espressoserver.test_1.13.0_com.example.enterpriseapp.apk' is already signed.
[debug] [ADB] Getting install status for io.appium.espressoserver.test
[debug] [ADB] Running '/Users/someuser/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys package io.appium.espressoserver.test'
[debug] [ADB] 'io.appium.espressoserver.test' is installed
[debug] [ADB] Getting package info for 'io.appium.espressoserver.test'
[debug] [ADB] Running '/Users/someuser/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys package io.appium.espressoserver.test'
[debug] [ADB] The version name of the installed 'io.appium.espressoserver.test' is greater or equal to the application version name ('1.0.0' >= '1.0.0')
[debug] [Espresso] Performing cleanup of automation leftovers
[debug] [Espresso] No obsolete sessions have been detected (Error: socket hang up)
[Espresso] Starting Espresso Server v1.13.0 with cmd: adb shell am instrument -w -e debug false io.appium.espressoserver.test/androidx.test.runner.AndroidJUnitRunner
[debug] [ADB] Creating ADB subprocess with args: ["-P",5037,"-s","emulator-5554","shell","am","instrument","-w","-e","debug","false","io.appium.espressoserver.test/androidx.test.runner.AndroidJUnitRunner"]
[debug] [Espresso] [Instrumentation] [STDOUT]
[Espresso] Waiting for Espresso to be online...
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8301/status] with no body
[WD Proxy] Got an unexpected response: {"code":"ECONNRESET"}
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8301/status] with no body
[debug] [WD Proxy] Got response with status 200: "{\"id\":\"0ea25da7-a96c-4dee-9c39-8d6120461176\",\"sessionId\":null,\"status\":0,\"value\":null}"
[debug] [WD Proxy] Determined that the downstream protocol for proxy is MJSONWP
[debug] [WD Proxy] Matched '/session' to command name 'createSession'
[debug] [WD Proxy] Proxying [POST /session] to [POST http://localhost:8301/session] with body: {"desiredCapabilities":{"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"platformName":"Android","appActivity":"com.example.MyApp.MainActivity","appPackage":"com.example.enterpriseapp","app":"https://server.example.com/MobileApp/job/build/MyTestApp.apk","avd":"Pixel_2_API_28","deviceName":"Android Emulator","platformVersion":"9.0","automationName":"espresso"},"platformName":"Android","appActivity":"com.example.MyApp.MainActivity","appPackage":"com.example.enterpriseapp","app":"https://server.example.com/MobileApp/job/build/MyTestApp.apk","avd":"Pixel_2_API_28","deviceName":"emulator-5554","platformVersion":"9.0","automationName":"espresso","deviceUDID":"emulator-5554","appWaitPackage":"com.tes...
[WD Proxy] Got an unexpected response: {"code":"ECONNRESET"}
[debug] [Espresso] Deleting espresso session
[debug] [ADB] Running '/Users/someuser/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am force-stop com.example.enterpriseapp'
[debug] [Espresso] [Instrumentation] [STDOUT] io.appium.espressoserver.EspressoServerRunnerTest:INSTRUMENTATION_RESULT: shortMsg=Process crashed.
[debug] [Espresso] [Instrumentation] [STDOUT] INSTRUMENTATION_CODE: 0
[Espresso] Instrumentation process exited with code 0 from signal null
[debug] [Logcat] Stopping logcat capture
[Espresso] Restoring hidden api policy to the device default configuration
[debug] [ADB] Running '/Users/someuser/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell settings delete global hidden_api_policy_pre_p_apps'
[debug] [ADB] Running '/Users/someuser/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell settings delete global hidden_api_policy_p_apps'
[debug] [ADB] Running '/Users/someuser/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell settings delete global hidden_api_policy'
[debug] [ADB] Removing forwarded port socket connection: 8301
[debug] [ADB] Running '/Users/someuser/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 forward --remove tcp\:8301'
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1560989726037 (17:15:26 GMT-0700 (PDT))
[debug] [W3C] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up
[debug] [W3C]     at JWProxy.command (/Users/someuser/git/appium-espresso-driver/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:239:13)
[debug] [W3C]     at <anonymous>
[HTTP] <-- POST /wd/hub/session 500 7865 ms - 557
[HTTP]
```

**Comment by mykola-mokhnach** [comment]
Please attach the logcat output

**Comment by juandg** [comment]
Thanks @mykola-mokhnach I looked over at the ADB output and realized this seems to be a react-native issue, so I did more triage and investigation and have updated the issue accordingly. I'll try to sanitize the ADB logs a bit and post them here to help diagnosing the issue.

**Comment by juandg** [comment]
Closing this as it is not an espresso-driver issue.

Just for reference (in case someone stumbles into this closed issue by googling) I fixed this by just adding this line to our proguard rules:
```java
-keep class javax.inject.* { *; }
```

**Comment by idxn** [comment]
@mykola-mokhnach I faced the same issue. I think we need to add this in the document so that peoples would know how to deal with proguard.
