### ISSUE TITLE
Unable to click on few locators

### ISSUE THREAD

**Issue by vidyasagarp** [appium/appium-espresso-driver#464]
using Espresso driver not able to click on few locators, getting exception as Action will not be performed because the target view does not match one or more of the following constraints:
at least 90 percent of the view's area is displayed to the user. 
when inspected that locator using appium desktop i got bounds as [288,609][1376,695], 
same I tried using espresso driver.getRect().getX and getY() i was getting bounds as [-1152.0, 609.0] getting exception as MoveTargetOutOfBoundsException when i try to click on locator using coordinates.

Below is the exception i'm getting.
[AppiumLogs.pdf](https://github.com/appium/appium-espresso-driver/files/3329551/AppiumLogs.pdf)

org.openqa.selenium.InvalidElementStateException: io.appium.espressoserver.lib.handlers.exceptions.InvalidElementStateException: Could not perform click action on the element 96f007ff-7ce0-4992-b9c6-a963cb4fffb3
	at io.appium.espressoserver.lib.handlers.Click.handleInternal(Click.kt:35)
	at io.appium.espressoserver.lib.handlers.Click.handleInternal(Click.kt:27)
	at io.appium.espressoserver.lib.handlers.RequestHandler$DefaultImpls.handle(RequestHandler.kt:28)
	at io.appium.espressoserver.lib.handlers.Click.handle(Click.kt:27)
	at io.appium.espressoserver.lib.handlers.Click.handle(Click.kt:27)
	at io.appium.espressoserver.lib.http.Router.route(Router.kt:216)
	at io.appium.espressoserver.lib.http.Server.serve(Server.kt:53)
	at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:945)
	at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
	at java.lang.Thread.run(Thread.java:764)
Caused by: androidx.test.espresso.PerformException: Error performing 'single click' on view 'Looked for element with View com.vocera.uc.ui.chat.widget.MessageInfoView{709fa0b V.ED..... ........ 288,193-1376,279 #7f0800dc app:id/conversation_last_message}'.
	at androidx.test.espresso.PerformException$Builder.build(PerformException.java:84)
	at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:85)
	at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:57)
	at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:316)
	at androidx.test.espresso.ViewInteraction.desugaredPerform(ViewInteraction.java:177)
	at androidx.test.espresso.ViewInteraction.perform(ViewInteraction.java:118)
	at io.appium.espressoserver.lib.handlers.Click.handleInternal(Click.kt:33)
	... 9 more
Caused by: java.lang.RuntimeException: Action will not be performed because the target view does not match one or more of the following constraints:
at least 90 percent of the view's area is displayed to the user.
Target view: "MessageInfoView{id=2131230940, res-name=conversation_last_message, visibility=VISIBLE, width=1088, height=86, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.support.constraint.ConstraintLayout$LayoutParams@20485b6, tag=null, root-is-layout-requested=false, has-input-connection=false, x=288.0, y=193.0, text=Me: Hello85, input-type=0, ime-target=false, has-links=false}"
	at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:248)
	at androidx.test.espresso.ViewInteraction.access$100(ViewInteraction.java:64)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:157)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:154)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

Build info: version: '4.0.0-alpha-1', revision: 'd1d3728cae', time: '2019-04-24T13:42:21'
System info: host: 'vpesala01-mbp.local', ip: 'fe80:0:0:0:1cf1:2ae4:354:3c%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.1', java.version: '1.8.0_191'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities {app: /Users/vpesala/Documents/cl..., appActivity: com.vocera.uc.authenticatio..., appPackage: com.vocera.uc, appWaitPackage: com.vocera.uc, autoAcceptAlerts: true, autoGrantPermissions: true, automationName: Espresso, deviceName: MC 40, disableWindowAnimation: true, javascriptEnabled: true, newCommandTimeout: 120000, platform: ANDROID, platformName: Android, printPageSourceOnFindFailure: true, skipDeviceInitialization: true, skipServerInstallation: true, version: 7.0}
Session ID: 043a2b41-5346-475d-bfcc-48c4afff5ef4

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:190)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:124)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:51)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:161)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:577)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:308)
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:83)
	at com.uc.CommonAndroidUtility.clickOnMessage(CommonAndroidUtility.java:367)
	at com.uc.homescreentest.Android.TestUC726TitleOfMyConversations.Test_C125472_Verify_title_of_my_conversation_when_a_user_leave_1_1_conversation(TestUC726TitleOfMyConversations.java:171)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)

Environment:
Appium version (or git revision) that exhibits the issue: v1.14.0-beta.1
EspressoDriver version: 1.13.0
Last Appium version that did not exhibit the issue (if applicable): -
Desktop OS/version used to run Appium: Mac OS 10.14.1
Node.js version (unless using Appium.app|exe): v10.13.0
Npm or Yarn package manager: Npm
Mobile platform/version under test: Android 8
Real device or emulator/simulator: Real device
Appium CLI or Appium.app|exe: Appium CLI

**Comment by mykola-mokhnach** [comment]
> Caused by: java.lang.RuntimeException: Action will not be performed because the target view does not match one or more of the following constraints:
> at least 90 percent of the view's area is displayed to the user.

Such error is expected. You may try to click by coordinates to workaround it.
