### ISSUE TITLE
[Setup][OSX] Error: Neither ANDROID_HOME nor ANDROID_SDK_ROOT environment variable was exported

### ISSUE THREAD

**Issue by ganzf** [appium/appium-espresso-driver#466]
# Environment

OS: macOS 10.12.6 (16G1917)
Appium Version: 1.14.0-beta.2
Espresso driver version: 1.14.0 (^1.0.0 in package.json of appium)
Device: Android Version 8.0.0

# Problem

When trying to create a session with appium on an android device using the Espresso driver, the following error is found: 

```[debug] [BaseDriver] Event 'newSessionStarted' logged at 1562837217312 (11:26:57 GMT+0200 (CEST))
[debug] [MJSONWP] Encountered internal error running command: Error: Neither ANDROID_HOME nor ANDROID_SDK_ROOT environment variable was exported
[debug] [MJSONWP]     at getAndroidPlatformAndPath (/Users/ganzf/appium/node_modules/appium-adb/lib/helpers.js:32:11)
[debug] [MJSONWP]     at ADB.compileManifest (/Users/ganzf/appium/node_modules/appium-adb/lib/tools/android-manifest.js:253:42)
[debug] [MJSONWP]     at EspressoRunner.compileManifest [as buildNewModServer] (/Users/ganzf/appium/node_modules/appium-espresso-driver/lib/espresso-runner.js:118:20)
[debug] [MJSONWP]     at <anonymous>
[debug] [MJSONWP]     at process._tickCallback (internal/process/next_tick.js:188:7)
```

Yet here is the output of `env`: 

```TERM_PROGRAM=Apple_Terminal
ANDROID_HOME=/Users/ganzf/Library/Android/sdk
SHELL=/bin/bash
ANDROID_SDK_ROOT=this/is/not/working/either
USER=ganzf
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/ganzf/src/android-ndk-r14b:/Applications/Wireshark.app/Contents/MacOS
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home
HOME=/Users/ganzf
```

I am a novice when it comes to setting up appium but I have followed the tutorial on how to setup with android-studio. Any help is appreciated 👍 
Note that using UiAutomator2 **works**  but the ANDROID_HOME environment variable is still not found.

**Comment by ganzf** [comment]
My bad, the issue came from another soft managing my environment variables. Very sory.
