### ISSUE TITLE
Can't use setClipboard in espresso

### ISSUE THREAD

**Issue by aldochristiaan** [appium/appium-espresso-driver#493]
When using espresso driver, this method is not working.
`driver.setClipboardText("TEST STRING");`

It throws this exception:
```
org.openqa.selenium.InvalidArgumentException: io.appium.espressoserver.lib.handlers.exceptions.InvalidArgumentException: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter contentType
	at io.appium.espressoserver.lib.handlers.SetClipboard.handleInternal(SetClipboard.kt:42)
	at io.appium.espressoserver.lib.handlers.SetClipboard.handleInternal(SetClipboard.kt:32)
	at io.appium.espressoserver.lib.handlers.RequestHandler$DefaultImpls.handle(RequestHandler.kt:28)
	at io.appium.espressoserver.lib.handlers.SetClipboard.handle(SetClipboard.kt:32)
	at io.appium.espressoserver.lib.handlers.SetClipboard.handle(SetClipboard.kt:32)
	at io.appium.espressoserver.lib.http.Router.route(Router.kt:216)
	at io.appium.espressoserver.lib.http.Server.serve(Server.kt:53)
	at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:945)
	at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter contentType
	at io.appium.espressoserver.lib.handlers.SetClipboard$SetClipboardRunnable.<init>(Unknown Source:2)
	at io.appium.espressoserver.lib.handlers.SetClipboard.handleInternal(SetClipboard.kt:39)
	... 9 more
```

Appium Version : 1.14.2
Node Version : 1.16.0
Java Version : 1.8.0_211

**Comment by KazuCocoa** [comment]
Thanks.

Could you share your appium server log, too?
Exactly the exception is also espresso server-side issue, but I wonder what json data your client sent.

Below is an example by Ruby client.

```
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1566981729946 (17:42:09 GMT+0900 (Japan Standard Time))
[debug] [W3C (dd74176b)] Cached the protocol value 'W3C' for the new session dd74176b-f395-4887-8527-1465df08aead
[debug] [W3C (dd74176b)] Responding to client with driver.createSession() result: {"capabilities":{"platformName":"android","automationName":"espresso","app":"/Users/kazu/GitHub/ruby_lib_core/test/functional/app/api.apk.zip","udid":"emulator-5554","deviceName":"Android Emulator","appPackage":"io.appium.android.apis","appActivity":"io.appium.android.apis.ApiDemos","someCapability":"some_capability","eventTimings":true,"unicodeKeyboard":true,"resetKeyboard":true,"disableWindowAnimation":true,"newCommandTimeout":300,"autoGrantPermissions":true,"systemPort":8200,"language":"en","locale":"US","chromeOptions":{"args":["--disable-popup-blocking"]},"adbExecTimeout":60000,"uiautomator2ServerLaunchTimeout":60000}}
[HTTP] <-- POST /wd/hub/session 200 18069 ms - 692
[HTTP]
[HTTP] --> POST /wd/hub/session/dd74176b-f395-4887-8527-1465df08aead/timeouts
[HTTP] {"implicit":5000}
[debug] [W3C (dd74176b)] Calling AppiumDriver.timeouts() with args: [null,null,null,null,5000,"dd74176b-f395-4887-8527-1465df08aead"]
[debug] [BaseDriver] W3C timeout argument: {"implicit":5000}}
[debug] [BaseDriver] Set implicit wait to 5000ms
[debug] [W3C (dd74176b)] Responding to client with driver.timeouts() result: null
[HTTP] <-- POST /wd/hub/session/dd74176b-f395-4887-8527-1465df08aead/timeouts 200 16 ms - 14
[HTTP]
[HTTP] --> POST /wd/hub/session/dd74176b-f395-4887-8527-1465df08aead/appium/device/set_clipboard
[HTTP] {"contentType":"plaintext","content":"aGFwcHkgdGVzdGluZw==","label":"Note"}
[W3C (dd74176b)] Driver proxy active, passing request on via HTTP proxy
[debug] [WD Proxy] Matched '/wd/hub/session/dd74176b-f395-4887-8527-1465df08aead/appium/device/set_clipboard' to command name 'setClipboard'
[debug] [WD Proxy] Proxying [POST /wd/hub/session/dd74176b-f395-4887-8527-1465df08aead/appium/device/set_clipboard] to [POST http://localhost:8200/session/d5ecb35d-1dd3-402a-981f-93533a1c2661/appium/device/set_clipboard] with body: {"contentType":"plaintext","content":"aGFwcHkgdGVzdGluZw==","label":"Note"}
[debug] [WD Proxy] Got response with status 200: {"id":"99c65731-c9fa-4114-8ce3-c5cfdecd9ac4","sessionId":"d5ecb35d-1dd3-402a-981f-93533a1c2661","value":null}
[WD Proxy] Replacing sessionId d5ecb35d-1dd3-402a-981f-93533a1c2661 with dd74176b-f395-4887-8527-1465df08aead
[HTTP] <-- POST /wd/hub/session/dd74176b-f395-4887-8527-1465df08aead/appium/device/set_clipboard 200 39 ms - 109
[HTTP]
```

https://github.com/appium/java-client/blob/1991a8a0f9e4a3ff467dbb713cb5c51c8edc060f/src/main/java/io/appium/java_client/clipboard/HasClipboard.java#L62-L65 is Java client for it

**Comment by KazuCocoa** [comment]
Ah, I've fixed it in a couple of weeks ago. https://github.com/appium/appium-espresso-driver/pull/478
It will be in 1.15.0

You can try it as `appium@beta`

**Comment by aldochristiaan** [comment]
Okay, thanks @KazuCocoa 👍
