### ISSUE TITLE
App Crash with Espresso. Opening and immediately closing the app

### ISSUE THREAD

**Issue by Selvam-N** [appium/appium-espresso-driver#519]
ution not allowed: receiving Intent { act=android.intent.action.PACKAGE_ADDED dat=package:io.appium.espressoserver.test flg=0x4000010 (has extras) } to com.google.android.gms/.games.chimera.GamesSystemBroadcastReceiverProxy
12-09 17:33:01.075 W/BroadcastQueue( 4469): Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_ADDED dat=package:io.appium.espressoserver.test flg=0x4000010 (has extras) } to com.google.android.gms/.gass.chimera.PackageChangeBroadcastReceiver
12-09 17:33:01.076 W/BroadcastQueue( 4469): Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_ADDED dat=package:io.appium.espressoserver.test flg=0x4000010 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
12-09 17:33:01.077 W/BroadcastQueue( 4469): Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_ADDED dat=package:io.appium.espressoserver.test flg=0x4000010 (has extras) } to com.google.android.googlequicksearchbox/com.google.android.apps.gsa.googlequicksearchbox.GelStubAppWatcher
12-09 17:33:01.077 W/BroadcastQueue( 4469): Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_ADDED dat=package:io.appium.espressoserver.test flg=0x4000010 (has extras) } to com.google.android.ims/.receivers.RcsAutoStartReceiver
12-09 17:33:01.077 I/Finsky  (30251): [2] aavt.a(10): Do not start WearSupportService due to Wear service optimization
12-09 17:33:01.078 I/Finsky  (30251): [2] uxd.a(1): Clearing split related stale data.
12-09 17:33:01.081 I/am_pss  ( 4469): [29697,1000,com.android.settings,105358336,98873344,74752]
12-09 17:33:01.081 E/adbd    ( 6794): failed to connect to socket 'tcp:6791': Connection refused
12-09 17:33:01.084 I/Finsky  (30251): [186] neo.run(2): Cleaning dev-triggered-update data on package install for io.appium.espressoserver.test.
12-09 17:33:01.087 I/Finsky  (30251): [2] qfr.c(2): Frosting ID looked up on UI thread. Caller should move to a background thread.
12-09 17:33:01.094 I/Finsky  (30251): [194] neq.run(2): Finished dev-triggered-update cleaning.
12-09 17:33:01.101 I/Telecom ( 4469): DefaultDialerCache: Refreshing default dialer for user 0: now com.google.android.dialer: DDC.oR@ASk
12-09 17:33:01.111 I/Finsky  (30251): [189] qfn.run(16): Wrote row to frosting DB: 962
12-09 17:33:01.122 I/notification_cancel_all( 4469): [1000,4469,io.appium.espressoserver.test,0,0,0,5,NULL]
12-09 17:33:01.137 D/RegisteredNfcFServicesCache( 6852): Service unchanged, not updating
12-09 17:33:01.138 I/notification_enqueue( 4469): [10122,6909,com.duapps.recorder,201,NULL,0,Notification(channel=null pri=2 contentView=com.duapps.recorder/0x7f0b0052 vibrate=null sound=null defaults=0x0 flags=0x42 color=0x00000000 vis=PRIVATE),1]
12-09 17:33:01.151 W/GCM     ( 5464): Unexpected forwarded intent: Intent { act=android.intent.action.PACKAGE_ADDED dat=package:io.appium.espressoserver.test flg=0x4000010 cmp=com.google.android.gms/.chimera.PersistentIntentOperationService (has extras) }
12-09 17:33:01.154 W/GCM     ( 5464): Unexpected forwarded intent: Intent { act=android.intent.action.PACKAGE_ADDED dat=package:io.appium.espressoserver.test flg=0x4000010 cmp=com.google.android.gms/.chimera.PersistentIntentOperationService (has extras) }
12-09 17:33:01.163 I/Auth    ( 7019): [SupervisedAccountIntentOperation] onHandleIntent(): android.intent.action.PACKAGE_ADDED
12-09 17:33:01.165 I/am_pss  ( 4469): [4942,10076,com.google.android.inputmethod.latin,58904576,53657600,94208]
12-09 17:33:01.165 I/ChromeSync( 7019): [Sync,SyncIntentOperation] Handling the intent: Intent { act=android.intent.action.PACKAGE_ADDED dat=package:io.appium.espressoserver.test flg=0x4000010 cmp=com.google.android.gms/.chimera.GmsIntentOperationService (has extras) }.
12-09 17:33:01.166 I/FontsPackageChangeOp( 7019): Package io.appium.espressoserver.test has no metadata
12-09 17:33:01.205 I/zygote64( 4469): Background concurrent copying GC freed 120222(7MB) AllocSpace objects, 30(1368KB) LOS objects, 42% free, 18MB/32MB, paused 227us total 187.711ms
12-09 17:33:01.206 I/sysui_multi_action( 4955): [757,1093,758,4,793,3005,1094,605569024,1095,5]
12-09 17:33:01.241 I/am_pss  ( 4469): [5464,10018,com.google.android.gms.persistent,53908480,43122688,75776]
12-09 17:33:01.273 I/am_pss  ( 4469): [12003,99005,com.android.chrome:sandboxed_process0,24097792,17879040,0]
12-09 17:33:01.326 I/am_pss  ( 4469): [6909,10122,com.duapps.recorder,47767552,39809024,119808]
12-09 17:33:01.366 I/am_pss  ( 4469): [17894,10389,io.appium.settings,25269248,20602880,75776]
12-09 17:33:01.405 I/am_pss  ( 4469): [6825,10043,com.google.android.googlequicksearchbox:interactor,13159424,7667712,94208]
12-09 17:33:01.408 D/AndroidRuntime(31145): >>>>>> START com.android.internal.os.RuntimeInit uid 2000 <<<<<<
12-09 17:33:01.418 W/SearchableInfo( 4469): Invalid searchable metadata for com.google.android.gms/.nearby.sharing.ContactSelectActivity: Search label must be a resource reference.
12-09 17:33:01.496 D/ICU     (31145): Timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat
12-09 17:33:01.498 I/zygote64( 6881): Compiler allocated 4MB to compile void com.android.launcher3.LauncherModel$PackageUpdatedTask.run()
12-09 17:33:01.510 I/app_process(31145): The ClassLoaderContext is a special shared library.
12-09 17:33:01.540 D/AndroidRuntime(31145): Calling main entry com.android.commands.am.Am
12-09 17:33:01.546 I/ActivityManager( 4469): Force stopping bet.thescore.android.debug appid=10390 user=0: start instr
12-09 17:33:01.547 I/am_uid_running( 4469): 10390
12-09 17:33:01.560 I/am_proc_start( 4469): [0,31165,10390,bet.thescore.android.debug,added application,bet.thescore.android.debug]
12-09 17:33:01.561 I/ActivityManager( 4469): Start proc 31165:bet.thescore.android.debug/u0a390 for added application bet.thescore.android.debug
12-09 17:33:01.563 I/chatty  (31165): uid=10390(bet.thescore.android.debug) expire 173 lines
12-09 17:33:01.609 I/am_proc_bound( 4469): [0,31165,bet.thescore.android.debug]
12-09 17:33:01.612 I/am_uid_active( 4469): 10390
12-09 17:33:02.208 I/Icing   ( 7019): Indexing com.google.android.gms-apps from com.google.android.gms
12-09 17:33:02.217 I/Icing   ( 7019): Indexing done com.google.android.gms-apps
12-09 17:33:03.210 I/sysui_multi_action( 4955): [757,1093,758,4,793,2004,1094,605569024,1095,5]
12-09 17:33:03.341 I/chatty  (31165): uid=10390(bet.thescore.android.debug) expire 1 line
12-09 17:33:03.561 I/chatty  (31165): uid=10390(bet.thescore.android.debug) expire 4 lines
12-09 17:33:03.593 I/chatty  (31165): uid=10390(bet.thescore.android.debug) expire 16 lines
12-09 17:33:03.928 I/chatty  (31165): uid=10390(bet.thescore.android.debug) expire 2 lines
12-09 17:33:04.276 D/VoldConnector( 4469): SND -> {15 volume mkdirs /storage/emulated/0/Android/data/bet.thescore.android.debug/files/Download/}
12-09 17:33:04.277 D/VoldConnector( 4469): RCV <- {200 15 Command succeeded}
12-09 17:33:04.315 I/chatty  (31165): uid=10390(bet.thescore.android.debug) expire 11 lines
12-09 17:33:04.339 W/Conscrypt( 5464): Could not set socket write timeout: java.net.SocketException: Socket closed
12-09 17:33:04.339 W/Conscrypt( 5464):  at com.google.android.gms.org.conscrypt.Platform.setSocketWriteTimeout(:com.google.android.gms@19829019@19.8.29 (040400-282600551):2)
12-09 17:33:04.339 W/Conscrypt( 5464):  at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.setSoWriteTimeout(:com.google.android.gms@19829019@19.8.29 (040400-282600551):2)
12-09 17:33:04.362 W/Conscrypt( 5464): Could not set socket write timeout: java.net.SocketException: Socket closed
12-09 17:33:04.363 W/Conscrypt( 5464):  at com.google.android.gms.org.conscrypt.Platform.setSocketWriteTimeout(:com.google.android.gms@19829019@19.8.29 (040400-282600551):2)
12-09 17:33:04.363 W/Conscrypt( 5464):  at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.setSoWriteTimeout(:com.google.android.gms@19829019@19.8.29 (040400-282600551):2)
12-09 17:33:04.456 D/SubscriptionController( 5116): [getSubId]- invalid slotIndex=-1
12-09 17:33:04.877 I/chatty  (31165): uid=10390(bet.thescore.android.debug) expire 53 lines
12-09 17:33:04.932 I/chatty  (31165): uid=10390(bet.thescore.android.debug) expire 1 line
12-09 17:33:04.985 I/chatty  (

**Comment by KazuCocoa** [comment]
hm... the splash activity seems crashed. Can `bet.thescore.android.debug/bet.thescore.android.ui.splash.SplashActivity` launch?

```
7:33:08.689 D/DrmLibTime(  383): iotcl_continue_command finished! and return 0 
12-09 17:33:08.689 D/DrmLibTime(  383): before calling ioctl to read the next time_cmd
12-09 17:33:08.690 E/QC-time-services( 3668): Daemon: Time-services: Waiting to acceptconnection
12-09 17:33:08.787 I/chatty  (31165): uid=10390(bet.thescore.android.debug) expire 63 lines
12-09 17:33:09.488 W/WindowManager( 4469): removeWindowToken: Attempted to remove non-existing token: android.os.Binder@8cfac8a
12-09 17:33:11.198 I/sysui_multi_action( 4955): [757,1093,758,4,793,5987,1094,605569024,1095,5]
12-09 17:33:11.654 I/chatty  (31165): uid=10390(bet.thescore.android.debug) expire 1 line
12-09 17:33:13.023 I/chatty  (31165): uid=10390(bet.thescore.android.debug) expire 4 lines
12-09 17:33:13.205 I/sysui_multi_action( 4955): [757,1093,758,4,793,2007,1094,605569024,1095,5]
12-09 17:33:13.508 I/ActivityManager( 4469): Force stopping bet.thescore.android.debug appid=10390 user=0: from pid 31377
12-09 17:33:13.508 I/am_uid_stopped( 4469): 10390
12-09 17:33:13.508 I/ActivityManager( 4469): Killing 31165:bet.thescore.android.debug/u0a390 (adj 0): stop bet.thescore.android.debug
12-09 17:33:13.508 I/am_kill ( 4469): [0,31165,bet.thescore.android.debug,0,stop bet.thescore.android.debug]
12-09 17:33:13.511 W/zygote64( 4469): kill(-31165, 9) failed: No such process
12-09 17:33:13.514 W/ActivityManager( 4469): Force removing ActivityRecord{5a996cd u0 bet.thescore.android.debug/bet.thescore.android.ui.splash.SplashActivity t2568}: app died, no saved state
12-09 17:33:13.514 I/am_finish_activity( 4469): [0,95000269,2568,bet.thescore.android.debug/bet.thescore.android.ui.splash.SplashActivity,proc died without state saved]
12-09 17:33:13.519 I/WindowManager( 4469): Failed to capture screenshot of Token{4b5db82 ActivityRecord{5a996cd u0 bet.thescore.android.debug/bet.thescore.android.ui.splash.SplashActivity t2568 f}} appWin=Window{63e7fad u0 bet.thescore.android.debug/bet.thescore.android.ui.splash.SplashActivity} drawState=4
12-09 17:33:13.533 I/wm_task_removed( 4469): [2568,removeAppToken: last token]
12-09 17:33:13.535 I/wm_task_removed( 4469): [2568,removeTask]
12-09 17:33:13.536 W/ActivityManager( 4469): Crash of app bet.thescore.android.debug running instrumentation ComponentInfo{io.appium.espressoserver.test/androidx.test.runner.AndroidJUnitRunner}
12-09 17:33:13.536 I/ActivityManager( 4469): Force stopping bet.thescore.android.debug appid=10390 user=0: finished inst
12-09 17:33:13.537 W/Binder  ( 4469): Outgoing transactions from this process must be FLAG_ONEWAY
12-09 17:33:13.537 W/Binder  ( 4469): java.lang.Throwable
12-09 17:33:13.537 W/Binder  ( 4469):   at android.os.BinderProxy.transact(Binder.java:752)
12-09 17:33:13.537 W/Binder  ( 4469):   at android.app.IInstrumentationWatcher$Stub$Proxy.instrumentationFinished(IInstrumentationWatcher.java:160)
12-09 17:33:13.537 W/Binder  ( 4469):   at com.android.server.am.InstrumentationReporter$MyThread.run(InstrumentationReporter.java:86)
12-09 17:33:13.538 D/AndroidRuntime(31145): Shutting down VM
12-09 17:33:13.540 I/am_set_resumed_activity( 4469): [0,com.android.settings/.SubSettings,resumeTopActivityInnerLocked]
12-09 17:33:13.547 I/am_resume_activity( 4469): [0,187039159,2566,com.android.settings/.SubSettings]
12-09 17:33:13.556 W/zygote64( 4469): kill(-31165, 9) failed: No such process
12-09 17:33:13.563 I/sysui_count( 4469): [window_time_0,7]
12-09 17:33:13.563 I/sysui_multi_action( 4469): [757,803,799,window_time_0,802,7]
12-09 17:33:13.565 I/notification_cancel_all( 4469): [1000,4469,bet.thescore.android.debug,0,0,0,5,NULL]
12-09 17:33:13.567 I/sysui_multi_action(29697): [757,39,758,1,833,744]
12-09 17:33:13.573 I/chatty  (29697): uid=1000(system) com.android.settings expire 1 line
```
