### ISSUE TITLE
Failing to launch app with espresso driver menwhile when I'm using UIAutomator2 its working fine.

### ISSUE THREAD

**Issue by jeetendra50** [appium/appium-espresso-driver#527]
Appium version :-  Appium v1.15.1

[Espresso] [Instrumentation] [STDOUT] io.appium.espressoserver.EspressoServerRunnerTest:
[Espresso] [Instrumentation] [STDOUT] Process crashed while executing startEspressoServer(io.appium.espressoserver.EspressoServerRunnerTest):
[Espresso] [Instrumentation] [STDOUT] android.content.res.Resources$NotFoundException: Drawable com.choicehotels.android:dimen/browser_actions_context_menu_max_width with resource ID #0x7f070059
[Espresso] [Instrumentation] [STDOUT] Caused by: android.content.res.Resources$NotFoundException: Resource "com.choicehotels.android:dimen/browser_actions_context_menu_max_width" (7f070059) is not a Drawable (color or path): TypedValue{t=0x5/d=0x1f401 a=6 r=0x7f070059}
[Espresso] [Instrumentation] [STDOUT] 	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:814)
[Espresso] [Instrumentation] [STDOUT] 	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:659)
[Espresso] [Instrumentation] [STDOUT] 	at android.content.res.Resources.getDrawableForDensity(Resources.java:906)
[Espresso] [Instrumentation] [STDOUT] 	at android.content.res.Resources.getDrawable(Resources.java:845)
[Espresso] [Instrumentation] [STDOUT] 	at android.content.Context.getDrawable(Context.java:687)
[Espresso] [Instrumentation] [STDOUT] 	at androidx.core.content.ContextCompat.getDrawable(ContextCompat.java:463)
[Espresso] [Instrumentation] [STDOUT] 	at androidx.appcompat.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:203)
[Espresso] [Instrumentation] [STDOUT] 	at androidx.appcompat.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:191)
[Espresso] [Instrumentation] [STDOUT] 	at androidx.appcompat.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:753)
[Espresso] [Instrumentation] [STDOUT] 	at androidx.appcompat.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:196)
[Espresso] [Instrumentation] [STDOUT] 	at androidx.appcompat.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:86)
[Espresso] [Instrumentation] [STDOUT] 	at androidx.appcompat.app.AppCompatDelegateImpl.(AppCompatDelegateImpl.java:260)
[Espresso] [Instrumentation] [STDOUT] 	at androidx.appcompat.app.AppCompatDelegate.create(AppCompatDelegate.java:182)
[Espresso] [Instrumentation] [STDOUT] 	at androidx.appcompat.app.AppCompatActivity.getDelegate(AppCompatActivity.java:520)
[Espresso] [Instrumentation] [STDOUT] 	at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:71)
[Espresso] [Instrumentation] [STDOUT] 	at com.choicehotels.android.ui.SplashActivity.onCreate(SplashActivity.java:30)
[Espresso] [Instrumentation] [STDOUT] 	at android.app.Activity.performCreate(Activity.java:7802)
[Espresso] [Instrumentation] [STDOUT] 	at android.app.Activity.performCreate(Activity.java:7791)
[Espresso] [Instrumentation] [STDOUT] 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
[Espresso] [Instrumentation] [STDOUT] 	at androidx.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:702)
[Espresso] [Instrumentation] [STDOUT] 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
[Espresso] [Instrumentation] [STDOUT] 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
[Espresso] [Instrumentation] [STDOUT] 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
[Espresso] [Instrumentation] [STDOUT] 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
[Espresso] [Instrumentation] [STDOUT] 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
[Espresso] [Instrumentation] [STDOUT] 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
[Espresso] [Instrumentation] [STDOUT] 	at android.os.Handler.dispatchMessage(Handler.java:107)
[Espresso] [Instrumentation] [STDOUT] 	at android.os.Looper.loop(Looper.java:214)
[Espresso] [Instrumentation] [STDOUT] 	at android.app.ActivityThread.main(ActivityThread.java:7356)
[Espresso] [Instrumentation] [STDOUT] 	at java.lang.reflect.Method.invoke(Native Method)
[Espresso] [Instrumentation] [STDOUT] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
[Espresso] [Instrumentation] [STDOUT] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
[Espresso] [Instrumentation] [STDOUT]
[Espresso] [Instrumentation] [STDOUT] Process crashed while executing startEspressoServer(io.appium.espressoserver.EspressoServerRunnerTest):
[Espresso] [Instrumentation] [STDOUT] java.lang.RuntimeException: Unable to start activity ComponentInfo{com.choicehotels.android/com.choicehotels.android.ui.SplashActivity}: android.content.res.Resources$NotFoundException: Drawable com.choicehotels.android:dimen/browser_actions_context_menu_max_width with resource ID #0x7f070059
[Espresso] [Instrumentation] [STDOUT] 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
[Espresso] [Instrumentation] [STDOUT] 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
[Espresso] [Instrumentation] [STDOUT] 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
[Espresso] [Instrumentation] [STDOUT] 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
[Espresso] [Instrumentation] [STDOUT] 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
[Espresso] [Instrumentation] [STDOUT] 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
[Espresso] [Instrumentation] [STDOUT] 	at android.os.Handler.dispatchMessage(Handler.java:107)
[Espresso] [Instrumentation] [STDOUT] 	at android.os.Looper.loop(Looper.java:214)
[Espresso] [Instrumentation] [STDOUT] 	at android.app.ActivityThread.main(ActivityThread.java:7356)
[Espresso] [Instrumentation] [STDOUT] 	at java.lang.reflect.Method.invoke(Native Method)
[Espresso] [Instrumentation] [STDOUT] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
[Espresso] [Instrumentation] [STDOUT] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
[Espresso] [Instrumentation] [STDOUT] Caused by: android.content.res.Resources$NotFoundException: Drawable com.choicehotels.android:dimen/browser_actions_context_menu_max_width with resource ID #0x7f070059
[Espresso] [Instrumentation] [STDOUT] Caused by: android.content.res.Resources$NotFoundException: Resource "com.choicehotels.android:dimen/browser_actions_context_menu_max_width" (7f070059) is not a Drawable (color or path): TypedValue{t=0x5/d=0x1f401 a=6 r=0x7f070059}
[Espresso] [Instrumentation] [STDOUT] 	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:814)
[Espresso] [Instrumentation] [STDOUT] 	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:659)
[Espresso] [Instrumentation] [STDOUT] 	at android.content.res.Resources.getDrawableForDensity(Resources.java:906)
[Espresso] [Instrumentation] [STDOUT] 	at android.content.res.Resources.getDrawable(Resources.java:845)
[Espresso] [Instrumentation] [STDOUT] 	at android.content.Context.getDrawable(Context.java:687)
[Espresso] [Instrumentation] [STDOUT] 	at androidx.core.content.ContextCompat.getDrawable(ContextCompat.java:463)
[Espresso] [Instrumentation] [STDOUT] 	at androidx.appcompat.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:203)
[Espresso] [Instrumentation] [STDOUT] 	at androidx.appcompat.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:191)
[Espresso] [Instrumentation] [STDOUT] 	at androidx.appcompat.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:753)
[Espresso] [Instrumentation] [STDOUT] 	at androidx.appcompat.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:196)
[Espresso] [Instrumentation] [STDOUT] 	at androidx.appcompat.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:86)
[Espresso] [Instrumentation] [STDOUT] 	at androidx.appcompat.app.AppCompatDelegateImpl.(AppCompatDelegateImpl.java:260)
[Espresso] [Instrumentation] [STDOUT] 	at androidx.appcompat.app.AppCompatDelegate.create(AppCompatDelegate.java:182)
[Espresso] [Instrumentation] [STDOUT] 	at androidx.appcompat.app.AppCompatActivity.getDelegate(AppCompatActivity.java:520)
[Espresso] [Instrumentation] [STDOUT] 	at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:71)
[Espresso] [Instrumentation] [STDOUT] 	at com.choicehotels.android.ui.SplashActivity.onCreate(SplashActivity.java:30)
[Espresso] [Instrumentation] [STDOUT] 	at android.app.Activity.performCreate(Activity.java:7802)
[Espresso] [Instrumentation] [STDOUT] 	at android.app.Activity.performCreate(Activity.java:7791)
[Espresso] [Instrumentation] [STDOUT] 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
[Espresso] [Instrumentation] [STDOUT] 	at androidx.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:702)
[Espresso] [Instrumentation] [STDOUT] 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
[Espresso] [Instrumentation] [STDOUT] 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
[Espresso] [Instrumentation] [STDOUT] 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
[Espresso] [Instrumentation] [STDOUT] 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
[Espresso] [Instrumentation] [STDOUT] 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
[Espresso] [Instrumentation] [STDOUT] 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
[Espresso] [Instrumentation] [STDOUT] 	at android.os.Handler.dispatchMessage(Handler.java:107)
[Espresso] [Instrumentation] [STDOUT] 	at android.os.Looper.loop(Looper.java:214)
[Espresso] [Instrumentation] [STDOUT] 	at android.app.ActivityThread.main(ActivityThread.java:7356)
[Espresso] [Instrumentation] [STDOUT] 	at java.lang.reflect.Method.invoke(Native Method)
[Espresso] [Instrumentation] [STDOUT] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
[Espresso] [Instrumentation] [STDOUT] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
[WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNRESET"}
[Espresso] Deleting espresso session
[ADB] Running '/Users/818755/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am broadcast -a io.appium.settings.animation -n io.appium.settings/.receivers.AnimationSettingReceiver --es setstatus enable'
[Espresso] [Instrumentation] [STDOUT] INSTRUMENTATION_RESULT: shortMsg=Process crashed.
[Espresso] [Instrumentation] [STDOUT] INSTRUMENTATION_CODE: 0
[Espresso] Instrumentation process exited with code 0 from signal null
[ADB] Running '/Users/818755/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am force-stop com.choicehotels.android'
[Logcat] Stopping logcat capture
[Espresso] Restoring hidden api policy to the device default configuration
[ADB] Running '/Users/818755/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell settings delete global hidden_api_policy_pre_p_apps'
[ADB] Running '/Users/818755/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell settings delete global hidden_api_policy_p_apps'
[ADB] Running '/Users/818755/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell settings delete global hidden_api_policy'
[ADB] Removing forwarded port socket connection: 8300 
[ADB] Running '/Users/818755/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 forward --remove tcp\:8300'
[BaseDriver] Event 'newSessionStarted' logged at 1578125431367 (13:40:31 GMT+0530 (IST))
[MJSONWP] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up
[MJSONWP]     at JWProxy.command (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:261:13)
[HTTP] <-- POST /wd/hub/session 500 15396 ms - 216
[HTTP] 
[HTTP] --> DELETE /wd/hub/session
[HTTP] {}
[HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- DELETE /wd/hub/session 404 1 ms - 57
[HTTP]

**Comment by KazuCocoa** [comment]
Possible duplication of https://github.com/appium/appium-espresso-driver/issues/449

**Comment by johnhiggs** [comment]
I have a very similar issue, can you post your build.gradle

**Comment by vzenzo** [comment]
I see a lot of people with same issue as me and still no solution...sticking to UIAutomator2 until these things get fixed, I am having a headaches from "simple setup and simple use" Espresso...

**Comment by KazuCocoa** [comment]
I understand your feedback very well, but Espresso itself strongly depends on each project, unlike UIA2.
(We also very happy to find such general preference for Espresso.)

**Comment by claraSpark** [comment]
Hi, i want to ask about how to use this appium with espresso driver. Do we have to add espresso dependencies in the android application?
