### ISSUE TITLE
"mobile:startScreenStreaming" not working

### ISSUE THREAD

**Issue by rajdeepv** [appium/appium-espresso-driver#551]
Client Code:
```
@driver.execute_script('mobile:startScreenStreaming') 

Selenium::WebDriver::Error::UnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'opts' of undefined
from UnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'opts' of undefined
```

Appium Logs
```
[HTTP] --> POST /wd/hub/session/d64a8a4b-54b4-4c70-b5dc-4e3989ef8597/execute/sync
[HTTP] {"script":"mobile:startScreenStreaming","args":[]}
[debug] [W3C (d64a8a4b)] Calling AppiumDriver.execute() with args: ["mobile:startScreenStreaming",[],"d64a8a4b-54b4-4c70-b5dc-4e3989ef8597"]
[AndroidDriver] Executing native command 'mobile:startScreenStreaming'
[debug] [ADB] Running '/Users/rajdeepvarma/Library/Android/sdk/platform-tools/adb -H localhost -P 5037 -s emulator-5554 shell dumpsys display'
[debug] [W3C (d64a8a4b)] Encountered internal error running command: TypeError: Cannot read property 'opts' of undefined
[debug] [W3C (d64a8a4b)]     at initDeviceStreamingProc (/Users/rajdeepvarma/bma-calabash/node_modules/appium/node_modules/appium-espresso-driver/node_modules/appium-android-driver/lib/commands/streamscreen.js:122:81)
[debug] [W3C (d64a8a4b)]     at EspressoDriver.mobileStartScreenStreaming (/Users/rajdeepvarma/bma-calabash/node_modules/appium/node_modules/appium-espresso-driver/node_modules/appium-android-driver/lib/commands/streamscreen.js:303:37)
[debug] [W3C (d64a8a4b)]     at EspressoDriver.executeMobile (/Users/rajdeepvarma/bma-calabash/node_modules/appium/node_modules/appium-espresso-driver/lib/commands/execute.js:55:10)
[debug] [W3C (d64a8a4b)]     at EspressoDriver.execute (/Users/rajdeepvarma/bma-calabash/node_modules/appium/node_modules/appium-espresso-driver/node_modules/appium-android-driver/lib/commands/execute.js:11:12)
[HTTP] <-- POST /wd/hub/session/d64a8a4b-54b4-4c70-b5dc-4e3989ef8597/execute/sync 500 29 ms - 613
[HTTP]
```

**Comment by KazuCocoa** [comment]
Maybe https://github.com/appium/appium-android-driver/pull/604/files fixed this?
(By the line number and the file name)

**Comment by rajdeepv** [comment]
Oh yes. It has. Thanks!
