### ISSUE TITLE
Espresso fail during initial setup in emulator

### ISSUE THREAD

**Issue by zethyscythe** [appium/appium-espresso-driver#581]
## The problem
I'm trying to switch from uiautomator2 to espresso and i got error that the driver setup is failed. This is never happened before in uiautomator2.

## Environment
- Appium version (or git revision) that exhibits the issue:1.17.1
- Desktop OS/version used to run Appium:Windows 10
- Node.js version (unless using Appium.app|exe): v12.13.1
- Npm or Yarn package manager: npm v6.14.2
- Mobile platform/version under test: Android 28
- Real device or emulator/simulator: emulator
- Appium CLI or Appium.app|exe: cli
## Details
I got error in this part:
```
[Espresso] Starting Espresso Server v1.23.2 with cmd: adb shell am instrument -w -e debug false io.appium.espressoserver.test/androidx.test.runner.AndroidJUnitRunner
[debug] [ADB] Creating ADB subprocess with args: ["-P",5037,"-s","emulator-5554","shell","am","instrument","-w","-e","debug","false","io.appium.espressoserver.test/androidx.test.runner.AndroidJUnitRunner"]
[debug] [Espresso] [Instrumentation] [STDERR] android.util.AndroidException: INSTRUMENTATION_FAILED: io.appium.espressoserver.test/androidx.test.runner.AndroidJUnitRunner
[debug] [Espresso] [Instrumentation] [STDERR]   at com.android.commands.am.Instrument.run(Instrument.java:486)
[debug] [Espresso] [Instrumentation] [STDERR]   at com.android.commands.am.Am.runInstrument(Am.java:194)
[debug] [Espresso] [Instrumentation] [STDERR]   at com.android.commands.am.Am.onRun(Am.java:80)
[debug] [Espresso] [Instrumentation] [STDERR]   at com.android.internal.os.BaseCommand.run(BaseCommand.java:54)
[debug] [Espresso] [Instrumentation] [STDERR]   at com.android.commands.am.Am.main(Am.java:50)
[debug] [Espresso] [Instrumentation] [STDERR]   at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
[debug] [Espresso] [Instrumentation] [STDERR]   at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)
[debug] [Espresso] Deleting espresso session

```
Beforehand i noticed that io.appium.espressoserver.test  package was not even installed during initial setup
`adb shell dumpsys package io.appium.espressoserver.test` show package not found.

Also does appium-espresso support `systemPort` and `disableWindowAnimation` ? As the log stated those were not recognized as capabilities.

## Link to Appium logs
This complete log can be found at:
[appium-espresso-log](https://gist.github.com/zethyscythe/b4a9f0477c3811265a6dec5331417224)

**Comment by mykola-mokhnach** [comment]
It works as expected, since noReset option has been provided. Espresso driver works "on-top" of the tested application and must be bundled with it before starting the test.

**Comment by mykola-mokhnach** [comment]
> Also does appium-espresso support systemPort and disableWindowAnimation ? As the log stated those were not recognized as capabilities

Yes, these caps are specific for UiAutomator2: https://github.com/appium/appium-uiautomator2-driver/blob/master/lib/desired-caps.js

**Comment by zethyscythe** [comment]
Hi, by bundling the espresso with AUT do you mean add the espresso dependency to build.gradle like in [this](https://developer.android.com/training/testing/espresso/setup) setup?

> Yes, these caps are specific for UiAutomator2: https://github.com/appium/appium-uiautomator2-driver/blob/master/lib/desired-caps.js

Alright i see, seems this documentation a bit misleading: [http://appium.io/docs/en/writing-running-appium/caps/](url)

**Comment by mykola-mokhnach** [comment]
> Hi, by bundling the espresso with AUT do you mean add the espresso dependency to build.gradle like in this setup?

Not necessary. Espresso driver does the initial wrapping automatically if `app` capability is provided and `noReset` is `false`. The only issue there could be proguard usage by app under test. See https://discuss.appium.io/t/appium-1-17-1-with-espresso-session-start-failed/30681/13 for more details.

> Alright i see, seems this documentation a bit misleading: http://appium.io/docs/en/writing-running-appium/caps/

Feel free to create a PR to improve the docs. We know they are far from ideal.

**Comment by zethyscythe** [comment]
Hi @mykola-mokhnach , i finally found the cause which is `autoLaunch` caps is set to `false`. After remove this caps i got `io.appium.espressoserver.test` installed but i got another error which seems related to apk libs : [https://gist.github.com/zethyscythe/eb000fea6f02ea961fb0690da198de61](url)

> Feel free to create a PR to improve the docs. We know they are far from ideal.

Sure, will help when i got time later.

**Comment by mykola-mokhnach** [comment]
Yes, your error is similar to the one the gentleman in the ticket above had. Try to get an app build without obfuscation enabled.
