### ISSUE TITLE
UiAutomator2 actions are broken with kotlin

### ISSUE THREAD

**Issue by rajdeepv** [appium/appium-espresso-driver#586]
The reflection is throwing 
```
java.lang.IllegalStateException: No BuiltInsLoader implementation was found. Please ensure that the META-INF/services/ is not stripped from your application and that the Java virtual machine is not running under a security manager
```

**Stacktrace**
```
06-26 17:20:24.440 24868 25735 D appium  : Matched route definition: class io.appium.espressoserver.lib.http.RouteDefinition
06-26 17:20:24.440 24868 25735 D appium  : Matched route handler: class io.appium.espressoserver.lib.handlers.Uiautomator
06-26 17:20:24.440 24868 25735 D appium  : Got raw post data: {"strategy":"res","locator":"m_login_email","index":0,"action":"getText"}
06-26 17:20:24.445 24868 25735 I appium  : Invoking Uiautomator2 Methods
06-26 17:20:24.449 24868 25735 I appium  : Responding to server with error: {error=unknown error, message=java.lang.ExceptionInInitializerError, stacktrace=java.lang.ExceptionInInitializerError
06-26 17:20:24.449 24868 25735 I appium  : 	at kotlin.reflect.jvm.internal.impl.builtins.DefaultBuiltIns.getInstance(Unknown Source:0)
06-26 17:20:24.449 24868 25735 I appium  : 	at kotlin.reflect.jvm.internal.impl.types.ErrorUtils$1.getBuiltIns(ErrorUtils.java:139)
06-26 17:20:24.449 24868 25735 I appium  : 	at kotlin.reflect.jvm.internal.impl.resolve.descriptorUtil.DescriptorUtilsKt.getBuiltIns(DescriptorUtils.kt:167)
06-26 17:20:24.449 24868 25735 I appium  : 	at kotlin.reflect.jvm.internal.impl.descriptors.impl.TypeParameterDescriptorImpl.createWithDefaultBound(TypeParameterDescriptorImpl.java:56)
06-26 17:20:24.449 24868 25735 I appium  : 	at kotlin.reflect.jvm.internal.impl.builtins.SuspendFunctionTypesKt.<clinit>(suspendFunctionTypes.kt:33)
06-26 17:20:24.449 24868 25735 I appium  : 	at kotlin.reflect.jvm.internal.impl.builtins.SuspendFunctionTypesKt.isContinuation(suspendFunctionTypes.kt:82)
06-26 17:20:24.449 24868 25735 I appium  : 	at kotlin.reflect.jvm.internal.impl.load.java.lazy.descriptors.LazyJavaClassMemberScope.createSuspendView(LazyJavaClassMemberScope.kt:176)
06-26 17:20:24.449 24868 25735 I appium  : 	at kotlin.reflect.jvm.internal.impl.load.java.lazy.descriptors.LazyJavaClassMemberScope.doesOverrideSuspendFunction(LazyJavaClassMemberScope.kt:167)
06-26 17:20:24.449 24868 25735 I appium  : 	at kotlin.reflect.jvm.internal.impl.load.java.lazy.descriptors.LazyJavaClassMemberScope.isVisibleAsFunctionInCurrentClass(LazyJavaClassMemberScope.kt:121)
06-26 17:20:24.449 24868 25735 I appium  : 	at kotlin.reflect.jvm.internal.impl.load.java.lazy.descriptors.LazyJavaClassMemberScope.computeNonDeclaredFunctions(LazyJavaClassMemberScope.kt:276)
06-26 17:20:24.449 24868 25735 I appium  : 	at kotlin.reflect.jvm.internal.impl.load.java.lazy.descriptors.LazyJavaScope$functions$1.invoke(LazyJavaScope.kt:121)
06-26 17:20:24.449 24868 25735 I appium  : 	at kotlin.reflect.jvm.internal.impl.load.java.lazy.descriptors.LazyJavaScope$functions$1.invoke(LazyJavaScope.kt:59)
06-26 17:20:24.449 24868 25735 I appium  : 	at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(LockBasedStorageManager.java:512)
06-26 17:20:24.449 24868 25735 I appium  : 	at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$MapBasedMemoizedFunctionToNotNull.invoke(LockBasedStorageManager.java:587)
06-26 17:20:24.449 24868 25735 I appium  : 	at kotlin.reflect.jvm.internal.impl.load.java.lazy.descriptors.LazyJavaScope.getContributedFunctions(LazyJavaScope.kt:267)
06-26 17:20:24.449 24868 25735 I appium  : 	at kotlin.reflect.jvm.internal.impl.load.java.lazy.descriptors.LazyJavaClassMemberScope.getContributedFunctions(LazyJavaClassMemberScope.kt:747)
06-26 17:20:24.449 24868 25735 I appium  : 	at kotlin.reflect.jvm.internal.impl.load.java.lazy.descriptors.LazyJavaScope.computeDescriptors(LazyJavaScope.kt:363)
06-26 17:20:24.449 24868 25735 I appium  : 	at kotlin.reflect.jvm.internal.impl.load.java.lazy.descriptors.LazyJavaScope$allDescriptors$1.invoke(LazyJavaScope.kt:68)
06-26 17:20:24.449 24868 25735 I appium  : 	at kotlin.reflect.jvm.internal.impl.load.java.lazy.descriptors.LazyJavaScope$allDescriptors$1.invoke(LazyJavaScope.kt:59)
06-26 17:20:24.449 24868 25735 I appium  : 	at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:355)
06-26 17:20:24.449 24868 25735 I appium  : 	at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:474)
06-26 17:20:24.449 24868 25735 I appium  : 	at kotlin.reflect.jvm.internal.impl.load.java.lazy.descriptors.LazyJavaScope.getContributedDescriptors(LazyJavaScope.kt:342)
06-26 17:20:24.449 24868 25735 I appium  : 	at kotlin.reflect.jvm.internal.impl.resolve.scopes.ResolutionScope$DefaultImpls.getContributedDescriptors$default(ResolutionScope.kt:52)
06-26 17:20:24.449 24868 25735 I appium  : 	at kotlin.reflect.jvm.internal.KDeclarationContainerImpl.getMembers(KDeclarationContainerImpl.kt:65)
06-26 17:20:24.449 24868 25735 I appium  : 	at kotlin.reflect.jvm.internal.KClassImpl$Data$declaredNonStaticMembers$2.invoke(KClassImpl.kt:159)
06-26 17:20:24.449 24868 25735 I appium  : 	at kotlin.reflect.jvm.internal.KClassImpl$Data$declaredNonStaticMembers$2.invoke(KClassImpl.kt:44)
06-26 17:20:24.449 24868 25735 I appium  : 	at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:92)
06-26 17:20:24.449 24868 25735 I appium  : 	at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:31)
06-26 17:20:24.449 24868 25735 I appium  : 	at kotlin.reflect.jvm.internal.KClassImpl$Data.getDeclaredNonStaticMembers(Unknown Source:8)
06-26 17:20:24.449 24868 25735 I appium  : 	at kotlin.reflect.jvm.internal.KClassImpl$Data$allNonStaticMembers$2.invoke(KClassImpl.kt:168)
06-26 17:20:24.449 24868 25735 I appium  : 	at kotlin.reflect.jvm.internal.KClassImpl$Data$allNonStaticMembers$2.invoke(KClassImpl.kt:44)
06-26 17:20:24.449 24868 25735 I appium  : 	at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:92)
06-26 17:20:24.449 24868 25735 I appium  : 	at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:31)
06-26 17:20:24.449 24868 25735 I appium  : 	at kotlin.reflec
```

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-espresso-driver/pull/587
