### ISSUE TITLE
INSTRUMENTATION_RESULT: shortMsg=Process crashed.

### ISSUE THREAD

**Issue by wasder** [appium/appium-espresso-driver#605]
Hi! Please, help me understand why I can't launch appium with espresso driver.
Here are the logs. What else information can I provide?

```
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"app":"/Users/vasya/AndroidStudioProjects/android/app/build/outputs/apk/localhost/debug/MyApp.apk","automationName":"Espresso","deviceName":"Pixel 3 API 29","forceEspressoRebuild":true,"platformName":"Android","platformVersion":"10","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/vasya/AndroidStudioProjects/android/app/build/outputs/apk/localhost/debug/MyApp.apk","automationName":"Espresso","deviceName":"Pixel 3 API 29","forceEspressoRebuild":true,"platformName":"Android","platformVersion":"10","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1600967323750 (20:08:43 GMT+0300 (Москва, стандартное время))
[Appium] Appium v1.17.1 creating new EspressoDriver (v1.23.2) session
[BaseDriver] Creating session with MJSONWP desired capabilities: {
[BaseDriver]   "app": "/Users/vasya/AndroidStudioProjects/android/app/build/outputs/apk/localhost/debug/MyApp.apk",
[BaseDriver]   "automationName": "Espresso",
[BaseDriver]   "deviceName": "Pixel 3 API 29",
[BaseDriver]   "forceEspressoRebuild": true,
[BaseDriver]   "platformName": "Android",
[BaseDriver]   "platformVersion": "10",
[BaseDriver]   "newCommandTimeout": 0,
[BaseDriver]   "connectHardwareKeyboard": true
[BaseDriver] }
[BaseDriver] The following capabilities were provided, but are not recognized by Appium:
[BaseDriver]   connectHardwareKeyboard
[BaseDriver] Session created with session id: 4f9357fe-442d-4250-8805-c744d72c81bd
[BaseDriver] Using local app '/Users/vasya/AndroidStudioProjects/android/app/build/outputs/apk/localhost/debug/MyApp.apk'
[Espresso] Checking whether app is actually present
[Espresso] EspressoDriver version: 1.23.2
[ADB] Using 'adb' from '/Users/vasya/Library/Android/sdk/platform-tools/adb'
[AndroidDriver] Retrieving device list
[ADB] Trying to find a connected android device
[ADB] Getting connected devices...
[ADB] Connected devices: [{"udid":"emulator-5554","state":"device"}]
[AndroidDriver] Looking for a device with Android '10.0.0'
[ADB] Setting device id to emulator-5554
[ADB] Getting device platform version
[ADB] Running '/Users/vasya/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell getprop ro.build.version.release'
[ADB] Current device property 'ro.build.version.release': 10
[AndroidDriver] Using device: emulator-5554
[ADB] Using 'adb' from '/Users/vasya/Library/Android/sdk/platform-tools/adb'
[ADB] Setting device id to emulator-5554
[ADB] Running '/Users/vasya/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell getprop ro.build.version.sdk'
[ADB] Current device property 'ro.build.version.sdk': 29
[ADB] Getting device platform version
[ADB] Running '/Users/vasya/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell getprop ro.build.version.release'
[ADB] Current device property 'ro.build.version.release': 10
[ADB] Device API level: 29
[Espresso] Relaxing hidden api policy
[ADB] Running '/Users/vasya/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell settings put global hidden_api_policy_pre_p_apps 1'
[ADB] Running '/Users/vasya/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell settings put global hidden_api_policy_p_apps 1'
[ADB] Running '/Users/vasya/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell settings put global hidden_api_policy 1'
[AndroidDriver] Parsing package and activity from app manifest
[ADB] Package name: 'mtsit.com.finservice.localhost.debug'
[ADB] Main activity name: 'mtsit.com.finservice.presentation.start.StartActivity'
[AndroidDriver] Parsed package and activity are: mtsit.com.finservice.localhost.debug/mtsit.com.finservice.presentation.start.StartActivity
[ADB] Running '/Users/vasya/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 wait-for-device'
[ADB] Running '/Users/vasya/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell echo ping'
[AndroidDriver] Pushing settings apk to device...
[ADB] Getting install status for io.appium.settings
[ADB] Running '/Users/vasya/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys package io.appium.settings'
[ADB] 'io.appium.settings' is not installed
[ADB] App '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/io.appium.settings/apks/settings_apk-debug.apk' is not installed
[ADB] Installing '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/io.appium.settings/apks/settings_apk-debug.apk'
[ADB] Running '/Users/vasya/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 features'
[ADB] The application at '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/io.appium.settings/apks/settings_apk-debug.apk' will not be cached, because the device under test has confirmed the support of streamed installs
[ADB] Running '/Users/vasya/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 install -g /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/io.appium.settings/apks/settings_apk-debug.apk'
[ADB] The installation of 'settings_apk-debug.apk' took 289ms
[ADB] Install command stdout: Performing Streamed Install
[ADB] Success
[ADB] Getting IDs of all 'io.appium.settings' processes
[ADB] Running '/Users/vasya/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell 'pgrep --help; echo $?''
[ADB] Running '/Users/vasya/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell pgrep -f io\\.appium\\.settings'
[ADB] Getting IDs of all 'io.appium.settings' processes
[ADB] Running '/Users/vasya/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell pgrep -f io\\.appium\\.settings'
[ADB] Starting Appium Settings app
[ADB] Running '/Users/vasya/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am start -n io.appium.settings/.Settings -a android.intent.action.MAIN -c android.intent.category.LAUNCHER'
[ADB] Getting IDs of all 'io.appium.settings' processes
[ADB] Running '/Users/vasya/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell pgrep -f io\\.appium\\.settings'
[ADB] Getting IDs of all 'io.appium.settings' processes
[ADB] Running '/Users/vasya/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell pgrep -f io\\.appium\\.settings'
[ADB] Running '/Users/vasya/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell appops set io.appium.settings android\:mock_location allow'
[Logcat] Starting logcat capture
[ADB] Running '/Users/vasya/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell settings get global animator_duration_scale'
[ADB] Running '/Users/vasya/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell settings get global transition_animation_scale'
[ADB] Running '/Users/vasya/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell settings get global window_animation_scale'
[ADB] Running '/Users/vasya/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am broadcast -a io.appium.settings.animation -n io.appium.settings/.receivers.AnimationSettingReceiver --es setstatus disable'
[Espresso] Forwarding Espresso Server port 6791 to 8300
[ADB] Forwarding system: 8300 to device: 6791
[ADB] Running '/Users/vasya/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 forward tcp\:8300 tcp\:6791'
[ADB] Running '/Users/vasya/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys window'
[AndroidDriver] Screen already unlocked, doing nothing
[ADB] Checking app cert for /Users/vasya/AndroidStudioProjects/android/app/build/outputs/apk/localhost/debug/MyApp.apk
[ADB] Using 'apksigner.jar' from '/Users/vasya/Library/Android/sdk/build-tools/30.0.2/lib/apksigner.jar'
[ADB] Starting apksigner: /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/java -Xmx1024M -Xss1m -jar /Users/vasya/Library/Android/sdk/build-tools/30.0.2/lib/apksigner.jar verify --print-certs /Users/vasya/AndroidStudioProjects/android/app/build/outputs/apk/localhost/debug/MyApp.apk
[ADB] apksigner stdout: Signer #1 certificate DN: EMAILADDRESS=android@android.com, CN=Android, OU=Android, O=Android, L=Mountain View, ST=California, C=US
[ADB] Signer #1 certificate SHA-256 digest: a40da80a59d170caa950cf15c18c454d47a39b26989d8b640ecd745ba71bf5dc
[ADB] Signer #1 certificate SHA-1 digest: 61ed377e85d386a8dfee6b864bd85b0bfaa5af81
[ADB] Signer #1 certificate MD5 digest: e89b158e4bcf988ebd09eb83f5378e87
[ADB] 
[ADB] '/Users/vasya/AndroidStudioProjects/android/app/build/outputs/apk/localhost/debug/MyApp.apk' is signed with the default certificate
[ADB] Getting install status for mtsit.com.finservice.localhost.debug
[ADB] Running '/Users/vasya/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys package mtsit.com.finservice.localhost.debug'
[ADB] 'mtsit.com.finservice.localhost.debug' is not installed
[ADB] App '/Users/vasya/AndroidStudioProjects/android/app/build/outputs/apk/localhost/debug/MyApp.apk' is not installed
[ADB] Installing '/Users/vasya/AndroidStudioProjects/android/app/build/outputs/apk/localhost/debug/MyApp.apk'
[ADB] The application at '/Users/vasya/AndroidStudioProjects/android/app/build/outputs/apk/localhost/debug/MyApp.apk' will not be cached, because the device under test has confirmed the support of streamed installs
[ADB] Running '/Users/vasya/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 install /Users/vasya/AndroidStudioProjects/android/app/build/outputs/apk/localhost/debug/MyApp.apk'
[ADB] The installation of 'MyApp.apk' took 961ms
[ADB] Install command stdout: Performing Incremental Install
[ADB] Performing Streamed Install
[ADB] Success
[Espresso] 'forceEspressoRebuild' capability is enabled
[Espresso] Deleting the obsolete Espresso server package '/var/folders/03/49mkj7lx6ms8spqxnkv0d5dm0000gn/T/io.appium.espressoserver.test_1.23.2_mtsit.com.finservice.localhost.debug_emulator-5554.apk'
[Espresso] Building espresso server in '/var/folders/03/49mkj7lx6ms8spqxnkv0d5dm0000gn/T/espresso-server-emulator-5554'
[Espresso] The build folder root could be customized by changing the 'tmpDir' capability
[Espresso] Copying espresso server template from ('/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-espresso-driver/espresso-server' to '/var/folders/03/49mkj7lx6ms8spqxnkv0d5dm0000gn/T/espresso-server-emulator-5554')
[Support] Traversed 49 directories and 250 files in 509ms
[Espresso] Bulding espresso server
[Espresso] Beginning build with command './gradlew -PappiumTargetPackage=mtsit.com.finservice.localhost.debug assembleAndroidTest' in directory '/var/folders/03/49mkj7lx6ms8spqxnkv0d5dm0000gn/T/espresso-server-emulator-5554'
[Espresso] Output from Gradle will not be logged. To change this, use 'showGradleLog' desired capability
[Espresso] Copying built apk from '/var/folders/03/49mkj7lx6ms8spqxnkv0d5dm0000gn/T/espresso-server-emulator-5554/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk' to '/var/folders/03/49mkj7lx6ms8spqxnkv0d5dm0000gn/T/io.appium.espressoserver.test_1.23.2_mtsit.com.finservice.localhost.debug_emulator-5554.apk'
[ADB] Checking app cert for /var/folders/03/49mkj7lx6ms8spqxnkv0d5dm0000gn/T/io.appium.espressoserver.test_1.23.2_mtsit.com.finservice.localhost.debug_emulator-5554.apk
[ADB] Starting apksigner: /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/java -Xmx1024M -Xss1m -jar /Users/vasya/Library/Android/sdk/build-tools/30.0.2/lib/apksigner.jar verify --print-certs /var/folders/03/49mkj7lx6ms8spqxnkv0d5dm0000gn/T/io.appium.espressoserver.test_1.23.2_mtsit.com.finservice.localhost.debug_emulator-5554.apk
[ADB] apksigner stdout: Signer #1 certificate DN: C=US, O=Android, CN=Android Debug
[ADB] Signer #1 certificate SHA-256 digest: ce7e30be3975789797dc1b57dc192c71a6b97ebc73a2f906073c330bd9493d0c
[ADB] Signer #1 certificate SHA-1 digest: f3cf236d921b398242782c6a208dc6ba7ff0e602
[ADB] Signer #1 certificate MD5 digest: b3398b3040d5808175a0171887ddbf3b
[ADB] 
[ADB] '/var/folders/03/49mkj7lx6ms8spqxnkv0d5dm0000gn/T/io.appium.espressoserver.test_1.23.2_mtsit.com.finservice.localhost.debug_emulator-5554.apk' is signed with a non-default certificate
[ADB] Using 'zipalign' from '/Users/vasya/Library/Android/sdk/build-tools/30.0.2/zipalign'
[ADB] /var/folders/03/49mkj7lx6ms8spqxnkv0d5dm0000gn/T/io.appium.espressoserver.test_1.23.2_mtsit.com.finservice.localhost.debug_emulator-5554.apk' is already zip-aligned. Doing nothing
[ADB] Signing '/var/folders/03/49mkj7lx6ms8spqxnkv0d5dm0000gn/T/io.appium.espressoserver.test_1.23.2_mtsit.com.finservice.localhost.debug_emulator-5554.apk' with default cert
[ADB] Starting apksigner: /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/java -Xmx1024M -Xss1m -jar /Users/vasya/Library/Android/sdk/build-tools/30.0.2/lib/apksigner.jar sign --key /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-adb/keys/testkey.pk8 --cert /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-adb/keys/testkey.x509.pem /var/folders/03/49mkj7lx6ms8spqxnkv0d5dm0000gn/T/io.appium.espressoserver.test_1.23.2_mtsit.com.finservice.localhost.debug_emulator-5554.apk
[ADB] Uninstalling io.appium.espressoserver.test
[ADB] Getting install status for io.appium.espressoserver.test
[ADB] Running '/Users/vasya/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys package io.appium.espressoserver.test'
[ADB] 'io.appium.espressoserver.test' is not installed
[ADB] io.appium.espressoserver.test was not uninstalled, because it was not present on the device
[ADB] Getting install status for io.appium.espressoserver.test
[ADB] Running '/Users/vasya/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys package io.appium.espressoserver.test'
[ADB] 'io.appium.espressoserver.test' is not installed
[ADB] App '/var/folders/03/49mkj7lx6ms8spqxnkv0d5dm0000gn/T/io.appium.espressoserver.test_1.23.2_mtsit.com.finservice.localhost.debug_emulator-5554.apk' is not installed
[Espresso] Installing Espresso Test Server apk from the target device (path: '/var/folders/03/49mkj7lx6ms8spqxnkv0d5dm0000gn/T/io.appium.espressoserver.test_1.23.2_mtsit.com.finservice.localhost.debug_emulator-5554.apk')
[ADB] The application at '/var/folders/03/49mkj7lx6ms8spqxnkv0d5dm0000gn/T/io.appium.espressoserver.test_1.23.2_mtsit.com.finservice.localhost.debug_emulator-5554.apk' will not be cached, because the device under test has confirmed the support of streamed installs
[ADB] Running '/Users/vasya/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 install /var/folders/03/49mkj7lx6ms8spqxnkv0d5dm0000gn/T/io.appium.espressoserver.test_1.23.2_mtsit.com.finservice.localhost.debug_emulator-5554.apk'
[ADB] The installation of 'io.appium.espressoserver.test_1.23.2_mtsit.com.finservice.localhost.debug_emulator-5554.apk' took 144ms
[ADB] Install command stdout: Performing Incremental Install
[ADB] Performing Streamed Install
[ADB] Success
[Espresso] Installed Espresso Test Server apk '/var/folders/03/49mkj7lx6ms8spqxnkv0d5dm0000gn/T/io.appium.espressoserver.test_1.23.2_mtsit.com.finservice.localhost.debug_emulator-5554.apk' (pkg: 'io.appium.espressoserver.test')
[Espresso] Performing cleanup of automation leftovers
[Espresso] No obsolete sessions have been detected (Error: socket hang up)
[Espresso] Starting Espresso Server v1.23.2 with cmd: adb shell am instrument -w -e debug false io.appium.espressoserver.test/androidx.test.runner.AndroidJUnitRunner
[ADB] Creating ADB subprocess with args: ["-P",5037,"-s","emulator-5554","shell","am","instrument","-w","-e","debug","false","io.appium.espressoserver.test/androidx.test.runner.AndroidJUnitRunner"]
[Espresso] [Instrumentation] [STDOUT] INSTRUMENTATION_RESULT: shortMsg=Process crashed.
[Espresso] [Instrumentation] [STDOUT] INSTRUMENTATION_CODE: 0
[Espresso] Instrumentation process exited with code 0 from signal null
[Espresso] Deleting espresso session
[ADB] Running '/Users/vasya/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am broadcast -a io.appium.settings.animation -n io.appium.settings/.receivers.AnimationSettingReceiver --es setstatus enable'
[ADB] Running '/Users/vasya/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am force-stop mtsit.com.finservice.localhost.debug'
[Logcat] Stopping logcat capture
[Espresso] Restoring hidden api policy to the device default configuration
[ADB] Running '/Users/vasya/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell settings delete global hidden_api_policy_pre_p_apps'
[ADB] Running '/Users/vasya/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell settings delete global hidden_api_policy_p_apps'
[ADB] Running '/Users/vasya/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell settings delete global hidden_api_policy'
[ADB] Removing forwarded port socket connection: 8300 
[ADB] Running '/Users/vasya/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 forward --remove tcp\:8300'
[BaseDriver] Event 'newSessionStarted' logged at 1600967376043 (20:09:36 GMT+0300 (Москва, стандартное время))
[MJSONWP] Encountered internal error running command: A new session could not be created. Details: The process did not start within 30000ms (cmd: '/Users/vasya/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am instrument -w -e debug false io.appium.espressoserver.test/androidx.test.runner.AndroidJUnitRunner'). Check https://github.com/appium/appium-espresso-driver#troubleshooting regarding advanced session startup troubleshooting.
[MJSONWP] Error: The process did not start within 30000ms (cmd: '/Users/vasya/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am instrument -w -e debug false io.appium.espressoserver.test/androidx.test.runner.AndroidJUnitRunner')
[MJSONWP]     at Timeout._onTimeout (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/teen_process/lib/subprocess.js:197:18)
[MJSONWP]     at listOnTimeout (internal/timers.js:531:17)
[MJSONWP]     at processTimers (internal/timers.js:475:7)
[MJSONWP] Destroying socket connection
[HTTP] <-- POST /wd/hub/session 500 52293 ms - 464
[HTTP] 
[HTTP] --> DELETE /wd/hub/session
[HTTP] {}
[HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- DELETE /wd/hub/session 404 1 ms - 57
[HTTP] 
```

**Comment by KazuCocoa** [comment]
What happen when you call `adb shell am instrument -w -e debug false io.appium.espressoserver.test/androidx.test.runner.AndroidJUnitRunner` directly?
(I mean via console without Appium)

Then, could you attach the logcat, too?

**Comment by wasder** [comment]
```
% adb shell am instrument -w -e debug false io.appium.espressoserver.test/androidx.test.runner.AndroidJUnitRunner
INSTRUMENTATION_RESULT: shortMsg=Process crashed.
INSTRUMENTATION_CODE: 0

```

Logcat: https://gist.github.com/wasder/2164a4af6749bdf0f38546eebc13e7a1

**Comment by dlansakara** [comment]
@wasder I have the same issue. What was the solution to fix it ?

**Comment by Strime** [comment]
@wasder I got the same issue. Can you explain what was the solution please ?
