### ISSUE TITLE
Cannot start server

### ISSUE THREAD

**Issue by xuanzhaopeng** [appium/appium-espresso-driver#61]
Aligned apk and server apk are all installed in emulator. But :8080/status return with nobody. So I just execute the command manually to start espresso server.  Then I get it.

My env:
Appium 1.6.6-beta.4
Java-client 5.0.3
Android Emulator -  API 23

```
$ adb shell am instrument -w -e debug false io.appium.espressoserver.test/android.support.test.runner.AndroidJUnitRunner

io.appium.espressoserver.EspressoServerRunnerTest:
Error in startEspressoServer(io.appium.espressoserver.EspressoServerRunnerTest):
java.net.SocketException: socket failed: EACCES (Permission denied)
	at libcore.io.IoBridge.socket(IoBridge.java:619)
	at java.net.PlainSocketImpl.create(PlainSocketImpl.java:198)
	at java.net.PlainServerSocketImpl.create(PlainServerSocketImpl.java:38)
	at java.net.ServerSocket.<init>(ServerSocket.java:64)
	at fi.iki.elonen.NanoHTTPD$DefaultServerSocketFactory.create(NanoHTTPD.java:480)
	at fi.iki.elonen.NanoHTTPD.start(NanoHTTPD.java:2318)
	at io.appium.espressoserver.lib.http.Server.<init>(Server.java:25)
	at io.appium.espressoserver.EspressoServerRunnerTest.startEspressoServer(EspressoServerRunnerTest.java:26)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
	at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1879)
Caused by: android.system.ErrnoException: socket failed: EACCES (Permission denied)
	at libcore.io.Posix.socket(Native Method)
	at libcore.io.BlockGuardOs.socket(BlockGuardOs.java:282)
	at libcore.io.IoBridge.socket(IoBridge.java:604)
	... 34 more


Time: 0.007
There were 6 failures:
1) startEspressoServer(io.appium.espressoserver.EspressoServerRunnerTest)
java.net.SocketException: socket failed: EACCES (Permission denied)
	at libcore.io.IoBridge.socket(IoBridge.java:619)
	at java.net.PlainSocketImpl.create(PlainSocketImpl.java:198)
	at java.net.PlainServerSocketImpl.create(PlainServerSocketImpl.java:38)
	at java.net.ServerSocket.<init>(ServerSocket.java:64)
	at fi.iki.elonen.NanoHTTPD$DefaultServerSocketFactory.create(NanoHTTPD.java:480)
	at fi.iki.elonen.NanoHTTPD.start(NanoHTTPD.java:2318)
	at io.appium.espressoserver.lib.http.Server.<init>(Server.java:25)
	at io.appium.espressoserver.EspressoServerRunnerTest.startEspressoServer(EspressoServerRunnerTest.java:26)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
	at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1879)
Caused by: android.system.ErrnoException: socket failed: EACCES (Permission denied)
	at libcore.io.Posix.socket(Native Method)
	at libcore.io.BlockGuardOs.socket(BlockGuardOs.java:282)
	at libcore.io.IoBridge.socket(IoBridge.java:604)
	... 34 more
2) org.apache.bcel.verifier.VerifierAppFrame
java.lang.ClassNotFoundException: org.apache.bcel.verifier.VerifierAppFrame
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:324)
	at android.support.test.internal.runner.TestLoader.doLoadClass(TestLoader.java:92)
	at android.support.test.internal.runner.TestLoader.loadIfTest(TestLoader.java:113)
	at android.support.test.internal.runner.TestRequestBuilder.loadClassesFromClassPath(TestRequestBuilder.java:801)
	at android.support.test.internal.runner.TestRequestBuilder.build(TestRequestBuilder.java:747)
	at android.support.test.runner.AndroidJUnitRunner.buildRequest(AndroidJUnitRunner.java:354)
	at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:260)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1879)
Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.bcel.verifier.VerifierAppFrame" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/io.appium.espressoserver.test-1/base.apk", zip file "/data/app/im.getsocial.calc-1/base.apk"],nativeLibraryDirectories=[/data/app/io.appium.espressoserver.test-1/lib/x86, /data/app/im.getsocial.calc-1/lib/x86, /vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
	... 9 more
	Suppressed: java.lang.NoClassDefFoundError: org.apache.bcel.verifier.VerifierAppFrame
		at dalvik.system.DexFile.defineClassNative(Native Method)
		at dalvik.system.DexFile.defineClass(DexFile.java:226)
		at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
		at dalvik.system.DexPathList.findClass(DexPathList.java:338)
		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
		... 11 more
	Suppressed: java.lang.ClassNotFoundException: org.apache.bcel.verifier.VerifierAppFrame
		at java.lang.Class.classForName(Native Method)
		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
		... 10 more
	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
3) org.apache.bcel.verifier.VerifierFactoryListModel
java.lang.ClassNotFoundException: org.apache.bcel.verifier.VerifierFactoryListModel
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:324)
	at android.support.test.internal.runner.TestLoader.doLoadClass(TestLoader.java:92)
	at android.support.test.internal.runner.TestLoader.loadIfTest(TestLoader.java:113)
	at android.support.test.internal.runner.TestRequestBuilder.loadClassesFromClassPath(TestRequestBuilder.java:801)
	at android.support.test.internal.runner.TestRequestBuilder.build(TestRequestBuilder.java:747)
	at android.support.test.runner.AndroidJUnitRunner.buildRequest(AndroidJUnitRunner.java:354)
	at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:260)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1879)
Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.bcel.verifier.VerifierFactoryListModel" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/io.appium.espressoserver.test-1/base.apk", zip file "/data/app/im.getsocial.calc-1/base.apk"],nativeLibraryDirectories=[/data/app/io.appium.espressoserver.test-1/lib/x86, /data/app/im.getsocial.calc-1/lib/x86, /vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
	... 9 more
	Suppressed: java.lang.NoClassDefFoundError: org.apache.bcel.verifier.VerifierFactoryListModel
		at dalvik.system.DexFile.defineClassNative(Native Method)
		at dalvik.system.DexFile.defineClass(DexFile.java:226)
		at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
		at dalvik.system.DexPathList.findClass(DexPathList.java:338)
		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
		... 11 more
	Suppressed: java.lang.ClassNotFoundException: org.apache.bcel.verifier.VerifierFactoryListModel
		at java.lang.Class.classForName(Native Method)
		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
		... 10 more
	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
4) org.apache.bcel.verifier.VerifyDialog
java.lang.ClassNotFoundException: org.apache.bcel.verifier.VerifyDialog
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:324)
	at android.support.test.internal.runner.TestLoader.doLoadClass(TestLoader.java:92)
	at android.support.test.internal.runner.TestLoader.loadIfTest(TestLoader.java:113)
	at android.support.test.internal.runner.TestRequestBuilder.loadClassesFromClassPath(TestRequestBuilder.java:801)
	at android.support.test.internal.runner.TestRequestBuilder.build(TestRequestBuilder.java:747)
	at android.support.test.runner.AndroidJUnitRunner.buildRequest(AndroidJUnitRunner.java:354)
	at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:260)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1879)
Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.bcel.verifier.VerifyDialog" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/io.appium.espressoserver.test-1/base.apk", zip file "/data/app/im.getsocial.calc-1/base.apk"],nativeLibraryDirectories=[/data/app/io.appium.espressoserver.test-1/lib/x86, /data/app/im.getsocial.calc-1/lib/x86, /vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
	... 9 more
	Suppressed: java.lang.NoClassDefFoundError: org.apache.bcel.verifier.VerifyDialog
		at dalvik.system.DexFile.defineClassNative(Native Method)
		at dalvik.system.DexFile.defineClass(DexFile.java:226)
		at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
		at dalvik.system.DexPathList.findClass(DexPathList.java:338)
		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
		... 11 more
	Suppressed: java.lang.ClassNotFoundException: org.apache.bcel.verifier.VerifyDialog
		at java.lang.Class.classForName(Native Method)
		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
		... 10 more
	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
5) org.apache.regexp.REDemo
java.lang.ClassNotFoundException: org.apache.regexp.REDemo
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:324)
	at android.support.test.internal.runner.TestLoader.doLoadClass(TestLoader.java:92)
	at android.support.test.internal.runner.TestLoader.loadIfTest(TestLoader.java:113)
	at android.support.test.internal.runner.TestRequestBuilder.loadClassesFromClassPath(TestRequestBuilder.java:801)
	at android.support.test.internal.runner.TestRequestBuilder.build(TestRequestBuilder.java:747)
	at android.support.test.runner.AndroidJUnitRunner.buildRequest(AndroidJUnitRunner.java:354)
	at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:260)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1879)
Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.regexp.REDemo" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/io.appium.espressoserver.test-1/base.apk", zip file "/data/app/im.getsocial.calc-1/base.apk"],nativeLibraryDirectories=[/data/app/io.appium.espressoserver.test-1/lib/x86, /data/app/im.getsocial.calc-1/lib/x86, /vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
	... 9 more
	Suppressed: java.lang.NoClassDefFoundError: org.apache.regexp.REDemo
		at dalvik.system.DexFile.defineClassNative(Native Method)
		at dalvik.system.DexFile.defineClass(DexFile.java:226)
		at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
		at dalvik.system.DexPathList.findClass(DexPathList.java:338)
		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
		... 11 more
	Suppressed: java.lang.ClassNotFoundException: org.apache.regexp.REDemo
		at java.lang.Class.classForName(Native Method)
		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
		... 10 more
	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
6) org.apache.xalan.client.XSLTProcessorApplet
java.lang.ClassNotFoundException: org.apache.xalan.client.XSLTProcessorApplet
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:324)
	at android.support.test.internal.runner.TestLoader.doLoadClass(TestLoader.java:92)
	at android.support.test.internal.runner.TestLoader.loadIfTest(TestLoader.java:113)
	at android.support.test.internal.runner.TestRequestBuilder.loadClassesFromClassPath(TestRequestBuilder.java:801)
	at android.support.test.internal.runner.TestRequestBuilder.build(TestRequestBuilder.java:747)
	at android.support.test.runner.AndroidJUnitRunner.buildRequest(AndroidJUnitRunner.java:354)
	at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:260)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1879)
Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.xalan.client.XSLTProcessorApplet" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/io.appium.espressoserver.test-1/base.apk", zip file "/data/app/im.getsocial.calc-1/base.apk"],nativeLibraryDirectories=[/data/app/io.appium.espressoserver.test-1/lib/x86, /data/app/im.getsocial.calc-1/lib/x86, /vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
	... 9 more
	Suppressed: java.lang.NoClassDefFoundError: org.apache.xalan.client.XSLTProcessorApplet
		at dalvik.system.DexFile.defineClassNative(Native Method)
		at dalvik.system.DexFile.defineClass(DexFile.java:226)
		at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
		at dalvik.system.DexPathList.findClass(DexPathList.java:338)
		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
		... 11 more
	Suppressed: java.lang.ClassNotFoundException: org.apache.xalan.client.XSLTProcessorApplet
		at java.lang.Class.classForName(Native Method)
		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
		... 10 more
	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

FAILURES!!!
Tests run: 1,  Failures: 6
```

**Comment by xuanzhaopeng** [comment]
I guess maybe should add 
```
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
```

**Comment by dpgraham** [comment]
This probably still isn't an issue. But if it is I'll re-open.
