### ISSUE TITLE
Request timeout happens for `isToastVisible` instead of false

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium-espresso-driver#617]
`mobile: isToastVisible` raised below request timeout error instead of `false`.  (Noticed in ruby_lib_core's test cases)

```
[HTTP] --> POST /wd/hub/session/776b7972-c443-4c16-b2a1-e7bf5fc2e66a/execute/sync
[HTTP] {"script":"mobile: isToastVisible","args":[{"text":"A toast","isRegexp":true}]}
[debug] [W3C (776b7972)] Calling AppiumDriver.execute() with args: ["mobile: isToastVisible",[{"text":"A toast","isRegexp":true}],"776b7972-c443-4c16-b2a1-e7bf5fc2e66a"]
[AndroidDriver] Executing native command 'mobile: isToastVisible'
[debug] [WD Proxy] Proxying [POST /appium/execute_mobile/is_toast_displayed] to [POST http://localhost:8200/session/22a2df3a-8940-4f58-8370-c9181c9e8cb9/appium/execute_mobile/is_toast_displayed] with body: {"text":"A toast","isRegexp":true}
[WD Proxy] Error: timeout of 240000ms exceeded
[WD Proxy]     at createError (/Users/kazuaki/GitHub/appium/node_modules/axios/lib/core/createError.js:16:15)
[WD Proxy]     at RedirectableRequest.handleRequestTimeout (/Users/kazuaki/GitHub/appium/node_modules/axios/lib/adapters/http.js:264:16)
[WD Proxy]     at Object.onceWrapper (events.js:422:26)
[WD Proxy]     at RedirectableRequest.emit (events.js:315:20)
[WD Proxy]     at ClientRequest.eventHandlers.<computed> (/Users/kazuaki/GitHub/appium/node_modules/follow-redirects/index.js:13:24)
[WD Proxy]     at ClientRequest.emit (events.js:315:20)
[WD Proxy]     at Socket.emitRequestTimeout (_http_client.js:709:9)
[WD Proxy]     at Object.onceWrapper (events.js:421:28)
[WD Proxy]     at Socket.emit (events.js:327:22)
[WD Proxy]     at Socket._onTimeout (net.js:482:8)
[WD Proxy]     at listOnTimeout (internal/timers.js:549:17)
[WD Proxy]     at processTimers (internal/timers.js:492:7)
[debug] [W3C (776b7972)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: timeout of 240000ms exceeded
[debug] [W3C (776b7972)]     at JWProxy.command (/Users/kazuaki/GitHub/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:275:13)
[debug] [W3C (776b7972)]     at runMicrotasks (<anonymous>)
[debug] [W3C (776b7972)]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[HTTP] <-- POST /wd/hub/session/776b7972-c443-4c16-b2a1-e7bf5fc2e66a/execute/sync 500 60021 ms - 655
```

On logcat, below log appeared. Probably we should modify around https://github.com/appium/appium-espresso-driver/blob/master/espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetToastVisibility.kt#L35-L40 ?

```
2020-10-12 23:06:53.155 4418-4418/io.appium.android.apis D/IdlingResourceRegistry: All idling resources are idle.
2020-10-12 23:06:53.155 4418-4418/io.appium.android.apis D/IdlingResourceRegistry: All idling resources are idle.
2020-10-12 23:06:53.156 4418-4418/io.appium.android.apis D/RootViewPicker: No matching root available - waiting: 2000ms for one to appear.
2020-10-12 23:06:53.891 1845-2758/? I/GnssLocationProvider: WakeLock acquired by sendMessage(REPORT_SV_STATUS, 0, com.android.server.location.GnssLocationProvider$SvStatusInfo@ef7cb40)
2020-10-12 23:06:53.892 1845-1858/? I/GnssLocationProvider: WakeLock released by handleMessage(REPORT_SV_STATUS, 0, com.android.server.location.GnssLocationProvider$SvStatusInfo@ef7cb40)
2020-10-12 23:06:54.892 1845-2758/? I/GnssLocationProvider: WakeLock acquired by sendMessage(REPORT_SV_STATUS, 0, com.android.server.location.GnssLocationProvider$SvStatusInfo@2ef3a79)
2020-10-12 23:06:54.893 1845-1858/? I/GnssLocationProvider: WakeLock released by handleMessage(REPORT_SV_STATUS, 0, com.android.server.location.GnssLocationProvider$SvStatusInfo@2ef3a79)
2020-10-12 23:06:55.169 4418-4418/io.appium.android.apis D/IdlingResourceRegistry: All idling resources are idle.
2020-10-12 23:06:55.171 4418-4418/io.appium.android.apis D/IdlingResourceRegistry: All idling resources are idle.
2020-10-12 23:06:55.174 4418-4418/io.appium.android.apis D/RootViewPicker: No matching root available - waiting: 2000ms for one to appear.
2020-10-12 23:06:55.896 1845-2758/? I/GnssLocationProvider: WakeLock acquired by sendMessage(REPORT_SV_STATUS, 0, com.android.server.location.GnssLocationProvider$SvStatusInfo@642f3be)
2020-10-12 23:06:55.898 1845-1858/? I/GnssLocationProvider: WakeLock released by handleMessage(REPORT_SV_STATUS, 0, com.android.server.location.GnssLocationProvider$SvStatusInfo@642f3be)
2020-10-12 23:06:56.901 1845-2758/? I/GnssLocationProvider: WakeLock acquired by sendMessage(REPORT_SV_STATUS, 0, com.android.server.location.GnssLocationProvider$SvStatusInfo@3b9dc1f)
2020-10-12 23:06:56.902 1845-1858/? I/GnssLocationProvider: WakeLock released by handleMessage(REPORT_SV_STATUS, 0, com.android.server.location.GnssLocationProvider$SvStatusInfo@3b9dc1f)
2020-10-12 23:06:57.180 4418-4418/io.appium.android.apis D/IdlingResourceRegistry: All idling resources are idle.
2020-10-12 23:06:57.180 4418-4418/io.appium.android.apis D/IdlingResourceRegistry: All idling resources are idle.
2020-10-12 23:06:57.191 4418-4454/io.appium.android.apis D/appium: Finished processing POST request for '/session/6ec907e1-d020-4c48-93c4-0cc2fe227b55/appium/execute_mobile/is_toast_displayed'
2020-10-12 23:06:57.191 4418-4454/io.appium.android.apis I/appium: Responding to server with value: false
2020-10-12 23:06:57.202 4418-4454/io.appium.android.apis E/fi.iki.elonen.NanoHTTPD: Could not send response to the client
    java.net.SocketException: Broken pipe
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:117)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:161)
        at fi.iki.elonen.NanoHTTPD$Response.sendBody(NanoHTTPD.java:1694)
        at fi.iki.elonen.NanoHTTPD$Response.sendBodyWithCorrectEncoding(NanoHTTPD.java:1667)
        at fi.iki.elonen.NanoHTTPD$Response.sendBodyWithCorrectTransferAndEncoding(NanoHTTPD.java:1657)
        at fi.iki.elonen.NanoHTTPD$Response.send(NanoHTTPD.java:1624)
        at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:957)
        at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
        at java.lang.Thread.run(Thread.java:764)
2020-10-12 23:06:57.902 1845-2758/? I/GnssLocationProvider: Wake
```

The no matched `isToastVisible` returned false in Appium 1.18.3.
I'm taking a look....

**Comment by KazuCocoa** [comment]
hm, the behaviour changed since https://github.com/appium/appium-espresso-driver/pull/592

f84645583e13b5d8044fcb545383f34f5d3bf420 https://github.com/appium/appium-espresso-driver/commits/master

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-base-driver/compare/v6.2.3...v7.0.0 ?

**Comment by KazuCocoa** [comment]
Return `false` printed in the log, but this happened after timeout by base-driver. (In a case I increased DEFAULT_REQUEST_TIMEOUT in base-driver, too)
```
2020-10-16 00:25:30.861 7932-7964/io.appium.android.apis I/appium: Exception ========>>>>>>>: androidx.test.espresso.NoMatchingRootException: Matcher 'is toast' did not match any of the following roots: [Root{application-window-token=android.view.ViewRootImpl$W@1a4d615, window-token=android.view.ViewRootImpl$W@1a4d615, has-window-focus=true, layout-params-type=1, layout-params-string={(0,0)(fillxfill) ty=BASE_APPLICATION wanim=0x10302f8
      fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
      pfl=FORCE_DRAW_STATUS_BAR_BACKGROUND}, decor-view-string=DecorView{id=-1, visibility=VISIBLE, width=1080, height=1920, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params={(0,0)(fillxfill) ty=BASE_APPLICATION wanim=0x10302f8
      fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
      pfl=FORCE_DRAW_STATUS_BAR_BACKGROUND}, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=3}}]
2020-10-16 00:25:30.861 7932-7964/io.appium.android.apis I/appium: Exception to return false ========>>>>>>>: androidx.test.espresso.NoMatchingRootException: Matcher 'is toast' did not match any of the following roots: [Root{application-window-token=android.view.ViewRootImpl$W@1a4d615, window-token=android.view.ViewRootImpl$W@1a4d615, has-window-focus=true, layout-params-type=1, layout-params-string={(0,0)(fillxfill) ty=BASE_APPLICATION wanim=0x10302f8
      fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
      pfl=FORCE_DRAW_STATUS_BAR_BACKGROUND}, decor-view-string=DecorView{id=-1, visibility=VISIBLE, width=1080, height=1920, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params={(0,0)(fillxfill) ty=BASE_APPLICATION wanim=0x10302f8
      fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
      pfl=FORCE_DRAW_STATUS_BAR_BACKGROUND}, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=3}}]
2020-10-16 00:25:30.861 7932-7964/io.appium.android.apis D/appium: Finished processing POST request for '/session/d25e68c5-37fd-4251-b6fb-cf2d1e370c42/appium/execute_mobile/is_toast_displayed'
2020-10-16 00:25:30.861 7932-7964/io.appium.android.apis I/appium: Responding to server with value: false
2020-10-16 00:25:30.866 7932-7964/io.appium.android.apis E/fi.iki.elonen.NanoHTTPD: Could not send response to the client
    java.net.SocketException: Broken pipe
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:117)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:161)
        at fi.iki.elonen.NanoHTTPD$Response.sendBody(NanoHTTPD.java:1694)
        at fi.iki.elonen.NanoHTTPD$Response.sendBodyWithCorrectEncoding(NanoHTTPD.java:1667)
        at fi.iki.elonen.NanoHTTPD$Response.sendBodyWithCorrectTransferAndEncoding(NanoHTTPD.java:1657)
        at fi.iki.elonen.NanoHTTPD$Response.send(NanoHTTPD.java:1624)
        at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:957)
        at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by mykola-mokhnach** [comment]
Base driver works properly in this case: The actual matcher blocks for too long, so the proxy request times out. We probably need to tune the matcher itself (perhaps implement it same way it is done in UIA2, where we have an accessibility listener). Would you like to try it yourself @KazuCocoa or shall I try?

**Comment by KazuCocoa** [comment]
mm, yeah, I think so > tune

Too many like below log appeared on the log.
```
2020-10-12 23:06:55.174 4418-4418/io.appium.android.apis D/RootViewPicker: No matching root available - waiting: 2000ms for one to appear.
```

Feel free to do this if you have time.
Most of my recent time for like this investigation/coding is late time
