### ISSUE TITLE
waitForIdleTimeout request

### ISSUE THREAD

**Issue by howsyourface** [appium/appium-espresso-driver#621]
Hi hi,

On one of our screens our AUT stalls out and waits for the 10 second idle timeout on every request which makes the tests unusably slow.
With UIAutomator2 this occurs as well but I can override the idle time and it gets by timing out on each request when it hits the screen that never goes idle.

I have got us to the point where we have replaced UIAutomator2 with Espresso and everything is working well and this seems to be our last road block. Is this in the roadmap to be completed soon?

[Appium] Applying the initial values to Appium settings parsed from MJSONWP caps: {"waitForIdleTimeout":100}
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1603070167808 (14:16:07 GMT+1300 (New Zealand Daylight Time))
[debug] [MJSONWP] Encountered internal error running command: NotYetImplementedError: Method has not yet been implemented
[debug] [MJSONWP]     at EspressoDriver.updateSettings (/usr/local/lib/node_modules/appium/node_modules/appium-espresso-driver/lib/commands/general.js:274:9)
[debug] [MJSONWP]     at AppiumDriver.createSession (/usr/local/lib/node_modules/appium/lib/appium.js:388:17)
[debug] [MJSONWP]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[debug] [MJSONWP] Destroying socket connection

**Comment by KazuCocoa** [comment]
I'm afraid Espresso framework does not provide the feature like 
 https://developer.android.com/reference/androidx/test/uiautomator/Configurator#setwaitforidletimeout we refer to.

You probably can consider adding idling resources for Espresso instead.
https://developer.android.com/training/testing/espresso/idling-resource
Current Appium beta (will be next release) has mobile commands like `mobile:registerIdlingResources` http://appium.io/docs/en/commands/mobile-command/ to append custom ones.
