### ISSUE TITLE
polling of espresso server start is interrupted by DEFAULT_REQUEST_TIMEOUT = 240000 in WD_PROXY

### ISSUE THREAD

**Issue by rajdeepv** [appium/appium-espresso-driver#638]
Over the past few weeks, our tests have become flaky. While polling for the instrumentation server, I get a timeout from Axios

```
2020-12-10 17:35:54:779 [Espresso] Starting Espresso Server v1.39.0 with cmd: adb shell am instrument -w -e debug false io.appium.espressoserver.test/androidx.test.runner.AndroidJUnitRunner
2020-12-10 17:35:54:779 [ADB] Creating ADB subprocess with args: ["-H","automation9.d4","-P",9134,"-s","emulator-5554","shell","am","instrument","-w","-e","debug",false,"io.appium.espressoserver.test/androidx.test.runner.AndroidJUnitRunner"]
2020-12-10 17:35:54:811 [Espresso] Waiting up to 180000ms for Espresso server to be online
2020-12-10 17:35:54:811 [WD Proxy] Matched '/status' to command name 'getStatus'
2020-12-10 17:35:54:812 [WD Proxy] Proxying [GET /status] to [GET http://automation9.d4:34005/status] with no body
2020-12-10 17:35:54:826 [WD Proxy] socket hang up
2020-12-10 17:35:55:328 [WD Proxy] Matched '/status' to command name 'getStatus'
2020-12-10 17:35:55:329 [WD Proxy] Proxying [GET /status] to [GET http://automation9.d4:34005/status] with no body
2020-12-10 17:35:55:335 [WD Proxy] Error: read ECONNRESET
2020-12-10 17:35:55:335 [WD Proxy]     at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
2020-12-10 17:35:55:837 [WD Proxy] Matched '/status' to command name 'getStatus'
2020-12-10 17:35:55:837 [WD Proxy] Proxying [GET /status] to [GET http://automation9.d4:34005/status] with no body
2020-12-10 17:35:55:841 [WD Proxy] Error: read ECONNRESET
2020-12-10 17:35:55:842 [WD Proxy]     at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
2020-12-10 17:35:56:343 [WD Proxy] Matched '/status' to command name 'getStatus'
2020-12-10 17:35:56:343 [WD Proxy] Proxying [GET /status] to [GET http://automation9.d4:34005/status] with no body
2020-12-10 17:35:56:348 [WD Proxy] Error: read ECONNRESET
2020-12-10 17:35:56:348 [WD Proxy]     at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
2020-12-10 17:35:56:851 [WD Proxy] Matched '/status' to command name 'getStatus'
2020-12-10 17:35:56:851 [WD Proxy] Proxying [GET /status] to [GET http://automation9.d4:34005/status] with no body
2020-12-10 17:35:56:859 [WD Proxy] socket hang up
2020-12-10 17:35:57:367 [WD Proxy] Matched '/status' to command name 'getStatus'
2020-12-10 17:35:57:367 [WD Proxy] Proxying [GET /status] to [GET http://automation9.d4:34005/status] with no body
2020-12-10 17:35:57:383 [WD Proxy] socket hang up
2020-12-10 17:35:57:888 [WD Proxy] Matched '/status' to command name 'getStatus'
2020-12-10 17:35:57:890 [WD Proxy] Proxying [GET /status] to [GET http://automation9.d4:34005/status] with no body
2020-12-10 17:35:57:898 [WD Proxy] Error: read ECONNRESET
2020-12-10 17:35:57:899 [WD Proxy]     at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
2020-12-10 17:35:58:400 [WD Proxy] Matched '/status' to command name 'getStatus'
2020-12-10 17:35:58:400 [WD Proxy] Proxying [GET /status] to [GET http://automation9.d4:34005/status] with no body
2020-12-10 17:35:58:404 [WD Proxy] Error: read ECONNRESET
2020-12-10 17:35:58:405 [WD Proxy]     at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
2020-12-10 17:35:58:907 [WD Proxy] Matched '/status' to command name 'getStatus'
2020-12-10 17:35:58:907 [WD Proxy] Proxying [GET /status] to [GET http://automation9.d4:34005/status] with no body
2020-12-10 17:36:03:256 [Espresso] [Instrumentation] io.appium.espressoserver.EspressoServerRunnerTest:
2020-12-10 17:39:58:919 [WD Proxy] Error: timeout of 240000ms exceeded
2020-12-10 17:39:58:920 [WD Proxy]     at createError (/tmp/root/node_modules/appium/node_modules/appium-base-driver/node_modules/axios/lib/core/createError.js:16:15)
2020-12-10 17:39:58:920 [WD Proxy]     at RedirectableRequest.handleRequestTimeout (/tmp/root/node_modules/appium/node_modules/appium-base-driver/node_modules/axios/lib/adapters/http.js:264:16)
2020-12-10 17:39:58:920 [WD Proxy]     at Object.onceWrapper (events.js:286:20)
2020-12-10 17:39:58:926 [WD Proxy]     at RedirectableRequest.emit (events.js:198:13)
2020-12-10 17:39:58:926 [WD Proxy]     at Timeout._onTimeout (/tmp/root/node_modules/appium/node_modules/follow-redirects/index.js:166:13)
2020-12-10 17:39:58:926 [WD Proxy]     at ontimeout (timers.js:436:11)
2020-12-10 17:39:58:926 [WD Proxy]     at tryOnTimeout (timers.js:300:5)
2020-12-10 17:39:58:926 [WD Proxy]     at listOnTimeout (timers.js:263:5)
2020-12-10 17:39:58:927 [WD Proxy]     at Timer.processTimers (timers.js:223:10)
2020-12-10 17:39:58:928 [Espresso] Timed out waiting for Espresso server to be online within 180000ms. The timeout value could be customized using 'espressoServerLaunchTimeout' capability
2020-12-10 17:39:58:928 [Espresso] Deleting espresso session
2020-12-10 17:39:58:929 [ADB] Running '/opt/android-sdk-linux/platform-tools/adb -H automation9.d4 -P 9134 -s emulator-5554 shell am broadcast -a io.appium.settings.animation -n io.appium.settings/.receivers.AnimationSettingReceiver --es setstatus enable'
2020-12-10 17:39:59:064 [ADB] Running '/opt/android-sdk-linux/platform-tools/adb -H automation9.d4 -P 9134 -s emulator-5554 shell am force-stop com.bumble.app'
2020-12-10 17:39:59:252 [Espresso] [Instrumentation] INSTRUMENTATION_RESULT: shortMsg=Process crashed.
2020-12-10 17:39:59:253 [Espresso] INSTRUMENTATION_CODE: 0
```

In the ADB logs, I can see the espresso server has started 

`12-10 17:36:03.031 I/appium  (12894): Running Appium Espresso Server at port 6791`

I am curious if there is anything related to proxying the call to the device has changed recently. The next test on the same device moves on without this issue (Our emulators are on a remote host)
Also, is there a way to configure the timeout of 240000ms to something small? I want to keep it very small because it is anyway polled until espressoServerLaunchTimeout

**Comment by mykola-mokhnach** [comment]
This timeout is set at https://github.com/appium/appium-base-driver/blob/0ad64791363dae0e18c04bef427428392b1a0ca5/lib/jsonwp-proxy/proxy.js#L35 and it is hardcoded. This timeout is the READ timeout and happens when the TCP connection to the remote server was successful, but no HTTP response has been received from it.

**Comment by mykola-mokhnach** [comment]
Also, there is a way to change it dynamically by setting the corresponding JWProxy property

**Comment by rajdeepv** [comment]
>  Also, there is a way to change it dynamically by setting the corresponding JWProxy property
Is that available by any capabilities, or will I need to change the code?
