### ISSUE TITLE
build failing in espresso driver

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium-espresso-driver#664]
`appium-espresso-driver@1.43.0` got the below error in https://dev.azure.com/AppiumCI/Appium%20CI/_build/results?buildId=14647&view=logs&j=04254d8a-0ee4-5202-28c9-d56c2bc94eb2&t=defac201-5385-5c4b-790f-3d632b5b92ed and failing espresso build in a new session process in Appium server side while `appium-espresso-driver@1.42.0` worked in ruby_lib_core suite.

Should figure out the cause since the same error may happen user env before our next release (at least)

```
2021-03-30T00:26:22.7183740Z [0m[1000D[KERROR AppiumLibCoreTest::PathTest#test_type (205.61s)
2021-03-30T00:26:22.7286510Z Minitest::UnexpectedError:         Selenium::WebDriver::Error::SessionNotCreatedError: A new session could not be created. Details: Unable to build Espresso server - Process ended with exitcode 1 (cmd: './gradlew -PappiumTargetPackage\=io.appium.android.apis assembleAndroidTest')
2021-03-30T00:26:22.7386440Z         Gradle error message:
2021-03-30T00:26:22.7488520Z         
2021-03-30T00:26:22.7590700Z         [STDOUT] Downloading https://services.gradle.org/distributions/gradle-6.8.3-all.zip,
2021-03-30T00:26:22.7602440Z         [STDOUT] ..............10%..............20%...............30%..............40%..............50%...............60%..............70%..............80%...............90%..............100%,
2021-03-30T00:26:22.7704760Z         [STDOUT] Starting a Gradle Daemon (subsequent builds will be faster),
2021-03-30T00:26:22.7806910Z         [STDERR] ,
2021-03-30T00:26:22.7908790Z         [STDERR] FAILURE: Build failed with an exception.,
2021-03-30T00:26:22.8010760Z         [STDERR] ,
2021-03-30T00:26:22.8088210Z         [STDERR] * What went wrong:,
2021-03-30T00:26:22.8192880Z         [STDERR] Task 'assembleAndroidTest' not found in root project 'espresso-server-emulator-5554'.,
2021-03-30T00:26:22.8230450Z         [STDERR] ,
2021-03-30T00:26:22.8261530Z         [STDERR] * Try:,
2021-03-30T00:26:22.8272600Z         [STDERR] Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.,
2021-03-30T00:26:22.8352370Z         [STDERR] ,
2021-03-30T00:26:22.8375620Z         [STDERR] * Get more help at https://help.gradle.org,
2021-03-30T00:26:22.8433160Z         [STDERR] ,
2021-03-30T00:26:22.8435890Z         [STDERR] BUILD FAILED in 2m 7s. Check https://github.com/appium/appium-espresso-driver#troubleshooting regarding advanced session startup troubleshooting.
2021-03-30T00:26:22.8439270Z             Error: Unable to build Espresso server - Process ended with exitcode 1 (cmd: './gradlew -PappiumTargetPackage\=io.appium.android.apis assembleAndroidTest')
2021-03-30T00:26:22.8472700Z             Gradle error message:
2021-03-30T00:26:22.8484070Z             
2021-03-30T00:26:22.8498710Z             [STDOUT] Downloading https://services.gradle.org/distributions/gradle-6.8.3-all.zip,
2021-03-30T00:26:22.8508130Z             [STDOUT] ..............10%..............20%...............30%..............40%..............50%...............60%..............70%..............80%...............90%..............100%,
2021-03-30T00:26:22.8516010Z             [STDOUT] Starting a Gradle Daemon (subsequent builds will be faster),
2021-03-30T00:26:22.8518230Z             [STDERR] ,
2021-03-30T00:26:22.8520480Z             [STDERR] FAILURE: Build failed with an exception.,
2021-03-30T00:26:22.8523540Z             [STDERR] ,
2021-03-30T00:26:22.8526440Z             [STDERR] * What went wrong:,
2021-03-30T00:26:22.8546860Z             [STDERR] Task 'assembleAndroidTest' not found in root project 'espresso-server-emulator-5554'.,
2021-03-30T00:26:22.8556970Z             [STDERR] ,
2021-03-30T00:26:22.8559000Z             [STDERR] * Try:,
2021-03-30T00:26:22.8573460Z             [STDERR] Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.,
2021-03-30T00:26:22.8637470Z             [STDERR] ,
2021-03-30T00:26:22.8644950Z             [STDERR] * Get more help at https://help.gradle.org,
2021-03-30T00:26:22.8647270Z             [STDERR] ,
2021-03-30T00:26:22.8659510Z             [STDERR] BUILD FAILED in 2m 7s. Check https://github.com/appium/appium-espresso-driver#troubleshooting regarding advanced session startup troubleshooting.
2021-03-30T00:26:22.8671370Z                 at Object.errorAndThrow (/Users/runner/hostedtoolcache/node/12.21.0/x64/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:94:35)
2021-03-30T00:26:22.8679890Z                 at ServerBuilder.runBuildProcess (/Users/runner/hostedtoolcache/node/12.21.0/x64/lib/node_modules/appium/node_modules/appium-espresso-driver/lib/server-builder.js:188:11)
2021-03-30T00:26:22.8683700Z             /Users/runner/work/1/s/vendor/bundle/ruby/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/response.rb:72:in `assert_ok'
2021-03-30T00:26:22.8689000Z             /Users/runner/work/1/s/vendor/bundle/ruby/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
2021-03-30T00:26:22.8792110Z             /Users/runner/work/1/s/vendor/bundle/ruby/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/common.rb:88:in `new'
2021-03-30T00:26:22.8805010Z             /Users/runner/work/1/s/vendor/bundle/ruby/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/common.rb:88:in `create_response'
2021-03-30T00:26:22.8838450Z             /Users/runner/work/1/s/vendor/bundle/ruby/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/default.rb:114:in `request'
2021-03-30T00:26:22.8854590Z             /Users/runner/work/1/s/lib/appium_lib_core/common/base/http_default.rb:97:in `call'
2021-03-30T00:26:22.8866540Z             /Users/runner/work/1/s/vendor/bundle/ruby/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/bridge.rb:167:in `execute'
2021-03-30T00:26:22.8874140Z             /Users/runner/work/1/s/lib/appium_lib_core/common/base/bridge.rb:85:in `create_session'
2021-03-30T00:26:22.8881570Z             /Users/runner/work/1/s/lib/appium_lib_core/common/base/bridge.rb:47:in `handshake'
2021-03-30T00:26:22.8918700Z             /Users/runner/work/1/s/lib/appium_lib_core/common/base/driver.rb:45:in `initialize'
2021-03-30T00:26:22.8925520Z             /Users/runner/work/1/s/lib/appium_lib_core/driver.rb:371:in `new'
2021-03-30T00:26:22.8933530Z             /Users/runner/work/1/s/lib/appium_lib_core/driver.rb:371:in `start_driver'
2021-03-30T00:26:22.8949770Z             /Users/runner/work/1/s/test/functional/android/patch_test.rb:23:in `setup'
2021-03-30T00:26:22.8958360Z 
```

**Comment by mykola-mokhnach** [comment]
Maybe something is wrong with the gradle wrapper. On my machine this standard task is present:

```
./gradlew tasks --all
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :tasks

------------------------------------------------------------
Tasks runnable from root project 'espresso-server'
------------------------------------------------------------

Android tasks
-------------
app:androidDependencies - Displays the Android dependencies of the project.
app:signingReport - Displays the signing info for the base and test modules
app:sourceSets - Prints out all the source sets defined in this project.

Build tasks
-----------
app:assemble - Assemble main outputs for all the variants.
app:assembleAndroidTest - Assembles all the Test applications.
app:build - Assembles and tests this project.
app:buildDependents - Assembles and tests this project and all projects that depend on it.
app:buildNeeded - Assembles and tests this project and all projects it depends on.
app:bundle - Assemble bundles for all the variants.
app:clean - Deletes the build directory.
app:cleanBuildCache - Deletes the build cache directory.
app:compileDebugAndroidTestSources
app:compileDebugSources
app:compileDebugUnitTestSources
app:compileReleaseSources
app:compileReleaseUnitTestSources

Build Setup tasks
-----------------
init - Initializes a new Gradle build.
wrapper - Generates Gradle wrapper files.

Cleanup tasks
-------------
app:lintFix - Runs lint on all variants and applies any safe suggestions to the source code.

Help tasks
----------
buildEnvironment - Displays all buildscript dependencies declared in root project 'espresso-server'.
app:buildEnvironment - Displays all buildscript dependencies declared in project ':app'.
dependencies - Displays all dependencies declared in root project 'espresso-server'.
app:dependencies - Displays all dependencies declared in project ':app'.
dependencyInsight - Displays the insight into a specific dependency in root project 'espresso-server'.
app:dependencyInsight - Displays the insight into a specific dependency in project ':app'.
help - Displays a help message.
app:help - Displays a help message.
javaToolchains - Displays the detected java toolchains. [incubating]
app:javaToolchains - Displays the detected java toolchains. [incubating]
kotlinDslAccessorsReport - Prints the Kotlin code for accessing the currently available project extensions and conventions.
app:kotlinDslAccessorsReport - Prints the Kotlin code for accessing the currently available project extensions and conventions.
outgoingVariants - Displays the outgoing variants of root project 'espresso-server'.
app:outgoingVariants - Displays the outgoing variants of project ':app'.
projects - Displays the sub-projects of root project 'espresso-server'.
app:projects - Displays the sub-projects of project ':app'.
properties - Displays the properties of root project 'espresso-server'.
app:properties - Displays the properties of project ':app'.
tasks - Displays the tasks runnable from root project 'espresso-server' (some of the displayed tasks may belong to subprojects).
app:tasks - Displays the tasks runnable from project ':app'.

Install tasks
-------------
app:installDebug - Installs the Debug build.
app:installDebugAndroidTest - Installs the android (on device) tests for the Debug build.
app:uninstallAll - Uninstall all applications.
app:uninstallDebug - Uninstalls the Debug build.
app:uninstallDebugAndroidTest - Uninstalls the android (on device) tests for the Debug build.
app:uninstallRelease - Uninstalls the Release build.

Verification tasks
------------------
app:check - Runs all checks.
app:connectedAndroidTest - Installs and runs instrumentation tests for all flavors on connected devices.
app:connectedCheck - Runs all device checks on currently connected devices.
app:connectedDebugAndroidTest - Installs and runs the tests for debug on connected devices.
app:deviceAndroidTest - Installs and runs instrumentation tests using all Device Providers.
app:deviceCheck - Runs all device checks using Device Providers and Test Servers.
app:lint - Runs lint on all variants.
app:lintDebug - Runs lint on the Debug build.
app:lintRelease - Runs lint on the Release build.
app:lintVitalRelease - Runs lint on just the fatal issues in the release build.
app:test - Run unit tests for all variants.
app:testDebugUnitTest - Run unit tests for the debug build.
app:testReleaseUnitTest - Run unit tests for the release build.

Other tasks
-----------
app:analyzeDebugAndroidTestDependencies
app:analyzeDebugDependencies
app:analyzeDebugUnitTestDependencies
app:analyzeReleaseDependencies
app:analyzeReleaseUnitTestDependencies
app:assembleDebug - Assembles main output for variant debug
app:assembleDebugAndroidTest - Assembles main output for variant debugAndroidTest
app:assembleDebugUnitTest - Assembles main output for variant debugUnitTest
app:assembleRelease - Assembles main output for variant release
app:assembleReleaseUnitTest - Assembles main output for variant releaseUnitTest
app:buildDebugPreBundle
app:buildReleasePreBundle
app:bundleDebug - Assembles bundle for variant debug
app:bundleDebugAndroidTestClasses
app:bundleDebugClasses
app:bundleDebugResources
app:bundleDebugUnitTestClasses
app:bundleRelease - Assembles bundle for variant release
app:bundleReleaseClasses
app:bundleReleaseResources
app:bundleReleaseUnitTestClasses
app:checkDebugAarMetadata
app:checkDebugAndroidTestAarMetadata
app:checkDebugAndroidTestDuplicateClasses
app:checkDebugDuplicateClasses
app:checkDebugManifest
app:checkReleaseAarMetadata
app:checkReleaseDuplicateClasses
app:checkReleaseManifest
clean
app:collectReleaseDependencies
app:compileDebugAidl
app:compileDebugAndroidTestAidl
app:compileDebugAndroidTestJavaWithJavac
app:compileDebugAndroidTestKotlin - Compiles the debugAndroidTest kotlin.
app:compileDebugAndroidTestRenderscript
app:compileDebugAndroidTestShaders
app:compileDebugJavaWithJavac
app:compileDebugKotlin - Compiles the debug kotlin.
app:compileDebugRenderscript
app:compileDebugShaders
app:compileDebugUnitTestJavaWithJavac
app:compileDebugUnitTestKotlin - Compiles the debugUnitTest kotlin.
app:compileLint
app:compileLintChecks
app:compileReleaseAidl
app:compileReleaseJavaWithJavac
app:compileReleaseKotlin - Compiles the release kotlin.
app:compileReleaseRenderscript
app:compileReleaseShaders
app:compileReleaseUnitTestJavaWithJavac
app:compileReleaseUnitTestKotlin - Compiles the releaseUnitTest kotlin.
components - Displays the components produced by root project 'espresso-server'. [deprecated]
app:components - Displays the components produced by project ':app'. [deprecated]
app:compressDebugAndroidTestAssets
app:compressDebugAssets
app:compressReleaseAssets
app:configureReleaseDependencies
app:consumeConfigAttr
app:createDebugCompatibleScreenManifests
app:createMockableJar
app:createReleaseCompatibleScreenManifests
dependentComponents - Displays the dependent components of components in root project 'espresso-server'. [deprecated]
app:dependentComponents - Displays the dependent components of components in project ':app'. [deprecated]
app:dexBuilderDebug
app:dexBuilderDebugAndroidTest
app:dexBuilderRelease
app:extractApksForDebug
app:extractApksForRelease
app:extractDebugNativeDebugMetadata
app:extractDebugNativeSymbolTables
app:extractDeepLinksDebug
app:extractDeepLinksRelease
app:extractProguardFiles
app:extractReleaseNativeDebugMetadata
app:extractReleaseNativeSymbolTables
app:generateDebugAndroidTestAssets
app:generateDebugAndroidTestBuildConfig
app:generateDebugAndroidTestResources
app:generateDebugAndroidTestResValues
app:generateDebugAndroidTestSources
app:generateDebugAssets
app:generateDebugBuildConfig
app:generateDebugFeatureMetadata
app:generateDebugFeatureTransitiveDeps
app:generateDebugManifestClass
app:generateDebugResources
app:generateDebugResValues
app:generateDebugSources
app:generateDebugUnitTestAssets
app:generateDebugUnitTestResources
app:generateDebugUnitTestSources
app:generateReleaseAssets
app:generateReleaseBuildConfig
app:generateReleaseFeatureMetadata
app:generateReleaseFeatureTransitiveDeps
app:generateReleaseManifestClass
app:generateReleaseResources
app:generateReleaseResValues
app:generateReleaseSources
app:generateReleaseUnitTestAssets
app:generateReleaseUnitTestResources
app:generateReleaseUnitTestSources
app:javaPreCompileDebug
app:javaPreCompileDebugAndroidTest
app:javaPreCompileDebugUnitTest
app:javaPreCompileRelease
app:javaPreCompileReleaseUnitTest
app:makeApkFromBundleForDebug
app:makeApkFromBundleForRelease
app:mergeDebugAndroidTestAssets
app:mergeDebugAndroidTestGeneratedProguardFiles
app:mergeDebugAndroidTestJavaResource
app:mergeDebugAndroidTestJniLibFolders
app:mergeDebugAndroidTestNativeLibs
app:mergeDebugAndroidTestResources
app:mergeDebugAndroidTestShaders
app:mergeDebugAssets
app:mergeDebugGeneratedProguardFiles
app:mergeDebugJavaResource
app:mergeDebugJniLibFolders
app:mergeDebugNativeDebugMetadata
app:mergeDebugNativeLibs
app:mergeDebugResources
app:mergeDebugShaders
app:mergeDexRelease
app:mergeExtDexDebug
app:mergeExtDexDebugAndroidTest
app:mergeExtDexRelease
app:mergeLibDexDebug
app:mergeLibDexDebugAndroidTest
app:mergeProjectDexDebug
app:mergeProjectDexDebugAndroidTest
app:mergeReleaseAssets
app:mergeReleaseGeneratedProguardFiles
app:mergeReleaseJavaResource
app:mergeReleaseJniLibFolders
app:mergeReleaseNativeDebugMetadata
app:mergeReleaseNativeLibs
app:mergeReleaseResources
app:mergeReleaseShaders
model - Displays the configuration model of root project 'espresso-server'. [deprecated]
app:model - Displays the configuration model of project ':app'. [deprecated]
app:packageDebug
app:packageDebugAndroidTest
app:packageDebugBundle
app:packageDebugUniversalApk
app:packageRelease
app:packageReleaseBundle
app:packageReleaseUniversalApk
app:parseDebugIntegrityConfig
app:parseReleaseIntegrityConfig
app:preBuild
app:preDebugAndroidTestBuild
app:preDebugBuild
app:preDebugUnitTestBuild
prepareKotlinBuildScriptModel
app:prepareLintJarForPublish
app:preReleaseBuild
app:preReleaseUnitTestBuild
app:processApplicationManifestDebugForBundle
app:processApplicationManifestReleaseForBundle
app:processDebugAndroidTestJavaRes
app:processDebugAndroidTestManifest
app:processDebugAndroidTestResources
app:processDebugJavaRes
app:processDebugMainManifest
app:processDebugManifest
app:processDebugManifestForInstantApp
app:processDebugManifestForPackage
app:processDebugResources
app:processDebugUnitTestJavaRes
app:processManifestDebugForFeature
app:processManifestReleaseForFeature
app:processReleaseJavaRes
app:processReleaseMainManifest
app:processReleaseManifest
app:processReleaseManifestForInstantApp
app:processReleaseManifestForPackage
app:processReleaseResources
app:processReleaseUnitTestJavaRes
app:resolveConfigAttr
app:sdkReleaseDependencyData
app:signDebugBundle
app:signingConfigWriterDebug
app:signingConfigWriterDebugAndroidTest
app:signingConfigWriterRelease
app:signReleaseBundle
app:stripDebugDebugSymbols
app:stripReleaseDebugSymbols
app:validateSigningDebug
app:validateSigningDebugAndroidTest
app:writeDebugApplicationId
app:writeDebugModuleMetadata
app:writeReleaseApplicationId
app:writeReleaseModuleMetadata
app:zipApksForDebug
app:zipApksForRelease
```

**Comment by misa** [comment]
Can you try to change it to
`./gradlew :app:assembleAndroidTest`

**Comment by KazuCocoa** [comment]
espresso driver installed via `npm install -g appium@beta` had only below tasks. Something missed

```
> Task :tasks

------------------------------------------------------------
Tasks runnable from root project 'espresso-server'
------------------------------------------------------------

Build Setup tasks
-----------------
init - Initializes a new Gradle build.
wrapper - Generates Gradle wrapper files.

Help tasks
----------
buildEnvironment - Displays all buildscript dependencies declared in root project 'espresso-server'.
dependencies - Displays all dependencies declared in root project 'espresso-server'.
dependencyInsight - Displays the insight into a specific dependency in root project 'espresso-server'.
help - Displays a help message.
javaToolchains - Displays the detected java toolchains. [incubating]
kotlinDslAccessorsReport - Prints the Kotlin code for accessing the currently available project extensions and conventions.
outgoingVariants - Displays the outgoing variants of root project 'espresso-server'.
projects - Displays the sub-projects of root project 'espresso-server'.
properties - Displays the properties of root project 'espresso-server'.
tasks - Displays the tasks runnable from root project 'espresso-server'.

To see all tasks and more detail, run gradlew tasks --all

To see more detail about a task, run gradlew help --task <task>

BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed
kazuaki@kazus-MB-pro espresso-server % pwd
/Users/kazuaki/.nodebrew/current/lib/node_modules/appium/node_modules/appium-espresso-driver/espresso-server
```
