### ISSUE TITLE
Calling Appium Server (1.20.1) is giving an alert error, but there is no alert shown or generated 

### ISSUE THREAD

**Issue by suparnashal** [appium/appium-espresso-driver#678]
See the following appium server log. I am calling the AppiumDriver.Execute with same command as below. The first time it works ok, but second time it fails. I am not generating any alerts because i do not see any on screen.
Device: ipad mini 5th generation ios.14 Safari browser.
I did AutoDismissAlerts and AutoAcceptAlerts capability. But it still does not work.  Please help

 [debug] [MJSONWP (63d5ace6)] **Calling AppiumDriver.execute() with args: ["return document.readyState",[],"63d5ace6-ae36-4a57-9beb-8bab625c24e9"]**
2021-07-11 19:00:09:341 - [debug] [XCUITest] Executing command 'execute'
2021-07-11 19:00:09:342 - [debug] [RemoteDebugger] Executing atom 'execute_script' with 'args=["return document.readyState",[]]; frames='
2021-07-11 19:00:09:342 - [debug] [RemoteDebugger] Executing 'execute_script' atom in default context
2021-07-11 19:00:09:342 - [debug] [RemoteDebugger] Sending javascript command: '(function(){return function(){var f=this;
2021-07-11 19:00:09:342 - [debug] [RemoteDebugger] funct...'
2021-07-11 19:00:09:343 - [debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to app 'PID:4233', page '1', target 'page-13' (id: 64): 'Runtime.evaluate'
2021-07-11 19:00:09:746 - [debug] [WD Proxy] Matched '/alert/text' to command name 'getAlertText'
2021-07-11 19:00:09:747 - [debug] [WD Proxy] Proxying [GET /alert/text] to [GET http://127.0.0.1:8100/session/4CECF9C0-C206-43F9-9AEA-CDD0A407BA31/alert/text] with no body
2021-07-11 19:00:29:329 - [WD Proxy] Got response with status 404: {"value":{"error":"no such alert","message":"An attempt was made to operate on a modal dialog when one was not open","traceback":""},"sessionId":"4CECF9C0-C206-43F9-9AEA-CDD0A407BA31"}
2021-07-11 19:00:29:329 - [debug] [W3C] Matched W3C error code 'no such alert' to NoSuchAlertError
2021-07-11 19:02:09:343 - [debug] [XCUITest] Error received while executing atom: operation timed out
2021-07-11 19:02:09:343 - [debug] [XCUITest] No alert found: Did not get any response for atom execution after 120001ms
2021-07-11 19:02:09:345 - [debug] [MJSONWP (63d5ace6)] Encountered internal error running command: Error: Did not get any response for atom execution after 120001ms
2021-07-11 19:02:09:345 - [debug] [MJSONWP (63d5ace6)]     at /Volumes/Sauce/selenium/appium-v1.20.1/node_modules/appium-xcuitest-driver/lib/commands/web.js:275:15
2021-07-11 19:02:09:345 - [debug] [MJSONWP (63d5ace6)]     at tryCatcher (/Volumes/Sauce/selenium/appium-v1.20.1/node_modules/bluebird/js/release/util.js:16:23)
2021-07-11 19:02:09:345 - [debug] [MJSONWP (63d5ace6)]     at Promise._settlePromiseFromHandler (/Volumes/Sauce/selenium/appium-v1.20.1/node_modules/bluebird/js/release/promise.js:547:31)
2021-07-11 19:02:09:345 - [debug] [MJSONWP (63d5ace6)]     at Promise._settlePromise (/Volumes/Sauce/selenium/appium-v1.20.1/node_modules/bluebird/js/release/promise.js:604:18)
2021-07-11 19:02:09:345 - [debug] [MJSONWP (63d5ace6)]     at Promise._settlePromise0 (/Volumes/Sauce/selenium/appium-v1.20.1/node_modules/bluebird/js/release/promise.js:649:10)
2021-07-11 19:02:09:345 - [debug] [MJSONWP (63d5ace6)]     at Promise._settlePromises (/Volumes/Sauce/selenium/appium-v1.20.1/node_modules/bluebird/js/release/promise.js:725:18)
2021-07-11 19:02:09:346 - [debug] [MJSONWP (63d5ace6)]     at _drainQueueStep (/Volumes/Sauce/selenium/appium-v1.20.1/node_modules/bluebird/js/release/async.js:93:12)
2021-07-11 19:02:09:346 - [debug] [MJSONWP (63d5ace6)]     at _drainQueue (/Volumes/Sauce/selenium/appium-v1.20.1/node_modules/bluebird/js/release/async.js:86:9)
2021-07-11 19:02:09:346 - [debug] [MJSONWP (63d5ace6)]     at Async._drainQueues (/Volumes/Sauce/selenium/appium-v1.20.1/node_modules/bluebird/js/release/async.js:102:5)
2021-07-11 19:02:09:346 - [debug] [MJSONWP (63d5ace6)]     at Immediate.Async.drainQueues (/Volumes/Sauce/selenium/appium-v1.20.1/node_modules/bluebird/js/release/async.js:15:14)
2021-07-11 19:02:09:346 - [debug] [MJSONWP (63d5ace6)]     at processImmediate (internal/timers.js:461:21)

**Comment by jlipps** [comment]
If you are not working with alerts, why is Appium receiving a request to check the alert text?

**Comment by mykola-mokhnach** [comment]
This logs has nothing to do with Espresso driver. @suparnashal consider reporting your issue to an appropriate place.
