### ISSUE TITLE
Appium server crashed after app restart

### ISSUE THREAD

**Issue by TerryCarry** [appium/appium-espresso-driver#685]
Hi masters,
I'm switching uiautomator to espresso driver with same automation script, and i'm encountering appium crash issue only by appium espresso driver while my app restart, could someone help me to check it?

adb logcat:
[adb_logcat.log](https://github.com/appium/appium-espresso-driver/files/6999568/adb_logcat.log)

appium log:
[appium_log.log](https://github.com/appium/appium-espresso-driver/files/6999573/appium_log.log)

**Comment by KazuCocoa** [comment]
According to the logcat, the app under test crashed.

```
08-17 11:17:52.095  1891  7581 W ActivityManager: Crash of app com.newee.mc.debug running instrumentation ComponentInfo{io.appium.espressoserver.test/androidx.test.runner.AndroidJUnitRunner}
```

So, do you mean the crash was when you clicked as below?

```
1-08-17 11:17:50:492 [HTTP] --> POST /wd/hub/session/d2fd944f-9487-448b-b2d6-241b2c0b9a29/element/58e48721-5971-4818-9e26-b834bf95f660/click
2021-08-17 11:17:50:492 [HTTP] {"id":"58e48721-5971-4818-9e26-b834bf95f660"}
2021-08-17 11:17:50:493 [W3C (d2fd944f)] Driver proxy active, passing request on via HTTP proxy
2021-08-17 11:17:50:493 [WD Proxy] Matched '/wd/hub/session/d2fd944f-9487-448b-b2d6-241b2c0b9a29/element/58e48721-5971-4818-9e26-b834bf95f660/click' to command name 'click'
2021-08-17 11:17:50:494 [WD Proxy] Proxying [POST /wd/hub/session/d2fd944f-9487-448b-b2d6-241b2c0b9a29/element/58e48721-5971-4818-9e26-b834bf95f660/click] to [POST http://localhost:12001/session/09bae0fe-22e4-4239-80c4-d6c3c6ebf4b5/element/58e48721-5971-4818-9e26-b834bf95f660/click] with body: {"id":"58e48721-5971-4818-9e26-b834bf95f660"}
2021-08-17 11:17:51:158 [WD Proxy] Got response with status 200: {"id":"cbd30b5f-231a-463a-b8da-80f21d0cb3d0","sessionId":"09bae0fe-22e4-4239-80c4-d6c3c6ebf4b5","value":null}
2021-08-17 11:17:51:159 [WD Proxy] Replacing sessionId 09bae0fe-22e4-4239-80c4-d6c3c6ebf4b5 with d2fd944f-9487-448b-b2d6-241b2c0b9a29
2021-08-17 11:17:51:160 [HTTP] <-- POST /wd/hub/session/d2fd944f-9487-448b-b2d6-241b2c0b9a29/element/58e48721-5971-4818-9e26-b834bf95f660/click 200 668 ms - 109
2021-08-17 11:17:51:160 [HTTP] 
2021-08-17 11:17:52:680 [Espresso] [Instrumentation] INSTRUMENTATION_RESULT: shortMsg=Process crashed.

2021-08-17 11:17:52:682 [Espresso] INSTRUMENTATION_CODE: 0
2021-08-17 11:17:52:696 [Espresso] Instrumentation process exited with code 0 from signal null
2021-08-17 11:17:59:230 [HTTP] --> POST /wd/hub/session/d2fd944f-9487-448b-b2d6-241b2c0b9a29/element
2021-08-17 11:17:59:231 [HTTP] {"using":"xpath","value":"//*[@text='Me']"}
2021-08-17 11:17:59:231 [W3C (d2fd944f)] Driver proxy active, passing request on via HTTP proxy
2021-08-17 11:17:59:256 [W3C (d2fd944f)] Encountered internal error running command: Error: Could not proxy. Proxy error: 'POST /wd/hub/session/d2fd944f-9487-448b-b2d6-241b2c0b9a29/element' cannot be proxied to Espresso server because the instrumentation process has crashed. Check the Appium server log and the logcat output for more details
2021-08-17 11:17:59:257 [W3C (d2fd944f)]     at doJwpProxy (C:\Users\terry\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:481:13)
2021-08-17 11:17:59:258 [W3C (d2fd944f)]     at asyncHandler (C:\Users\terry\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:253:9)
2021-08-17 11:17:59:266 [HTTP] <-- POST /wd/hub/session/d2fd944f-9487-448b-b2d6-241b2c0b9a29/element 500 36 ms - 1061
2021-08-17 11:17:59:266 [HTTP] 
```

Then, it is expected.
Espresso (https://developer.android.com/training/testing/espresso/) crashes when the app under test process is stopped. It is by design in the framework.

**Comment by TerryCarry** [comment]
@KazuCocoa the app restarted due to some action performing on UI, it's an expected behavior in our design.
If the app under test process is stopped, is there any chance that appium re-launch the app and establish conneciton with app again?

**Comment by KazuCocoa** [comment]
No, unfortunately.

The appium espresso driver assumes if the app under test was crashed (== the espresso process also stopped), the session should stop since the espresso server on the device can do nothing. It is difficult to identify if the crash is exactly expected or exactly crashed
Then, you should start creating a new session.

If the crash is expected for you, then you probably can do like the below to avoid 500 error in your expected place:

1. Do your scenario should crash
2. Check if the app is running via https://appium.io/docs/en/commands/device/app/app-state/ (probably this works even when the espresso server is crashed)
3. Re-create a new session in your test case to proceed your test case
4. complete your test...
