### ISSUE TITLE
java.lang.IllegalStateException: The application under test must require android.permission.INTERNET permission in its manifest

### ISSUE THREAD

**Issue by tandt53** [appium/appium-espresso-driver#689]
I start appium using espresso but it causes failure.
- appium server: 1.21.0
- appium java client: 7.5.1
- Capabilities:
```
DesiredCapabilities caps = new DesiredCapabilities();
caps.setCapability("platformName", "android");
caps.setCapability("platformVersion", "12");
caps.setCapability("noReset", true);
caps.setCapability("automationName", "Espresso");
caps.setCapability("injectInternetPermission", "true");
caps.setCapability("forceEspressoRebuild", "true");
caps.setCapability("app", appPath);
```

Anyone please help and thanks in advance.

**Comment by tandt53** [comment]
I checked [AndroidManifest.xml](https://github.com/appium/appium-espresso-driver/blob/00f9d2c971d009da74f45f61c669a3f17f02ea75/espresso-server/app/src/main/AndroidManifest.xml) of esspress-driver, it contains INTERNET permission already. 

Then I checked app permission `io.appium.espressoserver.test` on emulator, but there is no permission.
![image](https://user-images.githubusercontent.com/22423679/133916185-3e05c46c-3a70-4226-bc82-9b6f8961a002.png)

Anything goes wrong?

**Comment by KazuCocoa** [comment]
What permissions are in the manifesto of your application under test? (not espresso server)

**Comment by tandt53** [comment]
> What permissions are in the manifesto of your application under test? (not espresso server)

AUT's manifest has added INTERNET permission, but issue still there.

**Comment by KazuCocoa** [comment]
What the output of `adb shell am instrument -w -e debug false -e disableAnalytics true io.appium.espressoserver.test/androidx.test.runner.AndroidJUnitRunner`?

**Comment by tandt53** [comment]
Output of command 

```
* daemon started successfully

io.appium.espressoserver.EspressoServerRunnerTest:
Error in startEspressoServer(io.appium.espressoserver.EspressoServerRunnerTest):
java.lang.IllegalStateException: The application under test must require android.permission.INTERNET permission in its manifest
	at io.appium.espressoserver.lib.http.Server.start(Server.kt:93)
	at io.appium.espressoserver.EspressoServerRunnerTest.startEspressoServer(EspressoServerRunnerTest.kt:45)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2248)
Caused by: java.net.SocketException: socket failed: EPERM (Operation not permitted)
	at java.net.ServerSocket.createImpl(ServerSocket.java:309)
	at java.net.ServerSocket.getImpl(ServerSocket.java:259)
	at java.net.ServerSocket.setReuseAddress(ServerSocket.java:716)
	at fi.iki.elonen.NanoHTTPD.start(NanoHTTPD.java:2319)
	at io.appium.espressoserver.lib.http.Server.start(Server.kt:91)
	... 28 more


Time: 0.015
There was 1 failure:
1) startEspressoServer(io.appium.espressoserver.EspressoServerRunnerTest)
java.lang.IllegalStateException: The application under test must require android.permission.INTERNET permission in its manifest
	at io.appium.espressoserver.lib.http.Server.start(Server.kt:93)
	at io.appium.espressoserver.EspressoServerRunnerTest.startEspressoServer(EspressoServerRunnerTest.kt:45)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2248)
Caused by: java.net.SocketException: socket failed: EPERM (Operation not permitted)
	at java.net.ServerSocket.createImpl(ServerSocket.java:309)
	at java.net.ServerSocket.getImpl(ServerSocket.java:259)
	at java.net.ServerSocket.setReuseAddress(ServerSocket.java:716)
	at fi.iki.elonen.NanoHTTPD.start(NanoHTTPD.java:2319)
	at io.appium.espressoserver.lib.http.Server.start(Server.kt:91)
	... 28 more

FAILURES!!!
Tests run: 1,  Failures: 1
```

**Comment by KazuCocoa** [comment]
Did you remove your test target from the device under test?
I don't have a good idea to solve it, but I wondered some non-internet permission apk was in the device.

Quickly tested with https://github.com/appium/ruby_lib_core and https://github.com/appium/android-apidemos on android 12 emulator via appium 1.22.0 rc. It had no issues...


https://discuss.appium.io/ may also help.

**Comment by tandt53** [comment]
I tried successfully with apidemos app, but not my own app. 
Here is manifest
<img width="695" alt="image" src="https://user-images.githubusercontent.com/22423679/134157814-f61c873e-55ca-4203-b501-a4054d00b6bb.png">

**Comment by KazuCocoa** [comment]
mm, it seems good enough...

**Comment by theflyingwolves** [comment]
hey any luck on this? I am stuck here, too. 

Seems the Espresso Server app is lacking the INTERNET permission in its manifest? The version installed for my case is 1.45.3.
