### ISSUE TITLE
Socket hang up trying to access Espresso server status

### ISSUE THREAD

**Issue by ncalaway** [appium/appium-espresso-driver#710]
I am unable to start a session using Espresso. Each time I do, I get socket hang ups before the Espresso server just quits.
When I try to manually run `adb shell am instrument -w -e debug false -e disableAnalytics true io.appium.espressoserver.test/androidx.test.runner.AndroidJUnitRunner`, the result is:
```
INSTRUMENTATION_RESULT: shortMsg=Process crashed.
INSTRUMENTATION_CODE: 0
```

[Here](https://gist.github.com/ncalaway/293e890c0f746ae070d2f0c11ba701cd) are my Appium logs.

**Comment by KazuCocoa** [comment]
What the result of logcat when you called the adb command?
I guess you need to coordinate dependencies with https://github.com/appium/appium-espresso-driver#espresso-build-config

**Comment by ncalaway** [comment]
> What the result of logcat when you called the adb command? I guess you need to coordinate dependencies with https://github.com/appium/appium-espresso-driver#espresso-build-config

https://gist.github.com/ncalaway/0cf588665a538277e65299387257c1a1

**Comment by KazuCocoa** [comment]
I guess you should coordinate kotlin version or kotlin standard library version to match with the application under test by using https://github.com/appium/appium-espresso-driver#espresso-build-config

```
11-03 13:53:59.846  8381  8421 D TransportRuntime.JobInfoScheduler: Scheduling upload for context TransportContext(cct, HIGHEST, MSRodHRwczovL2NyYXNobHl0aWNzcmVwb3J0cy1wYS5nb29nbGVhcGlzLmNvbS92MS9maXJlbG9nL2xlZ2FjeS9iYXRjaGxvZ1xBSXphU3lCcnBTWVQ0RkZMMDlyZUhKaTZIOUZZZGVpU25VVE92Mk0=) with jobId=-1951253668 in 1000ms(Backend next call timestamp 0). Attempt 1
11-03 13:53:59.853  8381  8381 E UncaughtException: java.lang.NoSuchMethodError: No static method d0([Ljava/lang/Object;)Ljava/util/List; in class Lkotlin/collections/ArraysKt___ArraysKt; or its super classes (declaration of 'kotlin.collections.ArraysKt___ArraysKt' appears in /data/app/~~wFuEQKeTG3ClwbCjktGW1A==/io.appium.espressoserver.test-wmzqX4lCLcwiUk8ueDQJ3A==/base.apk)
11-03 13:53:59.853  8381  8381 E UncaughtException: 	at kotlin.collections.f.d0(Unknown Source:0)
11-03 13:53:59.853  8381  8381 E UncaughtException: 	at okio.q$a.d(Unknown Source:32)
11-03 13:53:59.853  8381  8381 E UncaughtException: 	at okhttp3.e0.b.<clinit>(Unknown Source:87)
11-03 13:53:59.853  8381  8381 E UncaughtException: 	at okhttp3.e0.b.t(Unknown Source:0)
11-03 13:53:59.853  8381  8381 E UncaughtException: 	at okhttp3.y.<clinit>(Unknown Source:21)
11-03 13:53:59.853  8381  8381 E UncaughtException: 	at com.echelonfit.api.b.c(Unknown Source:0)
11-03 13:53:59.853  8381  8381 E UncaughtException: 	at com.echelonfit.api.e.c(Unknown Source:0)
11-03 13:53:59.853  8381  8381 E UncaughtException: 	at com.echelonfit.api.e.b(Unknown Source:2)
11-03 13:53:59.853  8381  8381 E UncaughtException: 	at com.echelonfit.api.e.get(Unknown Source:0)
11-03 13:53:59.853  8381  8381 E UncaughtException: 	at com.echelonfit.api.i.h.b(Unknown Source:2)
11-03 13:53:59.853  8381  8381 E UncaughtException: 	at com.echelonfit.api.i.h.get(Unknown Source:0)
11-03 13:53:59.853  8381  8381 E UncaughtException: 	at com.echelonfit.authentication.domain.x.b(Unknown Source:2)
11-03 13:53:59.853  8381  8381 E UncaughtException: 	at com.echelonfit.authentication.domain.x.get(Unknown Source:0)
11-03 13:53:59.853  8381  8381 E UncaughtException: 	at com.echelonfit.authentication.domain.y.b(Unknown Source:10)
11-03 13:53:59.853  8381  8381 E UncaughtException: 	at com.echelonfit.authentication.domain.y.get(Unknown Source:0)
11-03 13:53:59.853  8381  8381 E UncaughtException: 	at e.a.a.get(Unknown Source:13)
11-03 13:53:59.853  8381  8381 E UncaughtException: 	at d.b.a.e.h.l(Unknown Source:2)
```

**Comment by ncalaway** [comment]
I coordinated the kotlin version like you said, but I still have the same crash output in logcat.

**Comment by KazuCocoa** [comment]
What configuration did you set?
I guess kotlin version, kotlin-stdlib and kotlin-reflect or around might affect this case.
You can see appium espresso driver's one in https://github.com/appium/appium-espresso-driver/blob/master/espresso-server/app/build.gradle.kts (this version is current master though).

This is my guess, but this depends on your test app's dependencies as well.
If your app also specified kotlin related versions etc, they probably also should coordinate.

**Comment by ncalaway** [comment]
I specified kotlin, like so: https://github.com/appium/appium-espresso-driver#toolsversions

**Comment by bronik** [comment]
I have the same issue while using espresso driver. has anyone suggestions how to fix it?

**Comment by rajdeepv** [comment]
If the app is already installed, it may need to be uninstalled. Please retry with uninstalling app and espresso server both

**Comment by ncalaway** [comment]
Tried uninstalling application under test and Appium Settings, and forcing a rebuild of the Espresso server. Same error.

**Comment by bronik** [comment]
@ncalaway try this solution:
https://discuss.appium.io/t/appium-server-1-19-1-still-getting-lifecycleeventobserver-error-when-using-espresso-driver/32569/17

works for me

**Comment by ncalaway** [comment]
> @ncalaway try this solution: https://discuss.appium.io/t/appium-server-1-19-1-still-getting-lifecycleeventobserver-error-when-using-espresso-driver/32569/17
> 
> works for me

This had no discernible effect.
