### ISSUE TITLE
ERROR: java.lang.NoSuchMethodError: No static method isTraceInProgress()Z in class Landroidx/compose/runtime/ComposerKt

### ISSUE THREAD

**Issue by PDesire** [appium/appium-espresso-driver#765]
Hello mates, 

I run into this issue currently while want to test a Jetpack Compose app (version 1.1.1 btw) with Appium 2.0.0-beta.27 (as they include the newest Appium Espresso driver). So far so good, I always get this error when I wanna launch the Jetpack Compose app with the Espresso test runner:

````
[EspressoDriver@863f (ec95dc83)] Installed Espresso Test Server apk '/Users/pdesire/Documents/Projects/driver-tmp/io.appium.espressoserver.test_2.2.1_de.CENSORED.android.sample_c21669c8.apk' (pkg: 'io.appium.espressoserver.test')
[ADB] Adding packages ["io.appium.settings","io.appium.espressoserver.test"] to Doze whitelist
[debug] [ADB] Got the following command chunks to execute: [["dumpsys","deviceidle","whitelist","+io.appium.settings",";","dumpsys","deviceidle","whitelist","+io.appium.espressoserver.test",";"]]
[debug] [ADB] Running '/Users/pdesire/Library/Android/sdk/platform-tools/adb -P 5037 -s c21669c8 shell dumpsys deviceidle whitelist +io.appium.settings ; dumpsys deviceidle whitelist +io.appium.espressoserver.test ;'
[debug] [EspressoDriver@863f (ec95dc83)] Performing cleanup of automation leftovers
[debug] [EspressoDriver@863f (ec95dc83)] No obsolete sessions have been detected (socket hang up)
[EspressoDriver@863f (ec95dc83)] Starting Espresso Server v2.2.1 with cmd: adb shell am instrument -w -e debug false -e disableAnalytics true io.appium.espressoserver.test/androidx.test.runner.AndroidJUnitRunner
[debug] [ADB] Creating ADB subprocess with args: ["-P",5037,"-s","c21669c8","shell","am","instrument","-w","-e","debug",false,"-e","disableAnalytics",true,"io.appium.espressoserver.test/androidx.test.runner.AndroidJUnitRunner"]
[EspressoDriver@863f (ec95dc83)] Waiting up to 45000ms for Espresso server to be online
[debug] [EspressoDriver@863f (ec95dc83)] Matched '/status' to command name 'getStatus'
[debug] [EspressoDriver@863f (ec95dc83)] Proxying [GET /status] to [GET http://127.0.0.1:8300/status] with no body
[EspressoDriver@863f (ec95dc83)] socket hang up
[debug] [EspressoDriver@863f (ec95dc83)] Matched '/status' to command name 'getStatus'
[debug] [EspressoDriver@863f (ec95dc83)] Proxying [GET /status] to [GET http://127.0.0.1:8300/status] with no body
[EspressoDriver@863f (ec95dc83)] socket hang up
[debug] [EspressoDriver@863f (ec95dc83)] Matched '/status' to command name 'getStatus'
[debug] [EspressoDriver@863f (ec95dc83)] Proxying [GET /status] to [GET http://127.0.0.1:8300/status] with no body
[EspressoDriver@863f (ec95dc83)] socket hang up
[debug] [EspressoDriver@863f (ec95dc83)] [Instrumentation] io.appium.espressoserver.EspressoServerRunnerTest:
[debug] [EspressoDriver@863f (ec95dc83)] Matched '/status' to command name 'getStatus'
[debug] [EspressoDriver@863f (ec95dc83)] Proxying [GET /status] to [GET http://127.0.0.1:8300/status] with no body
[debug] [EspressoDriver@863f (ec95dc83)] Got response with status 200: {"id":"d3e0c9f1-2eea-436e-9500-302f461636e2","sessionId":null,"value":null}
[EspressoDriver@863f (ec95dc83)] Espresso server is online. The initialization process took 1566ms
[EspressoDriver@863f (ec95dc83)] Starting the session
[debug] [EspressoDriver@863f (ec95dc83)] Matched '/session' to command name 'createSession'
[debug] [EspressoDriver@863f (ec95dc83)] Proxying [POST /session] to [POST http://127.0.0.1:8300/session] with body: {"capabilities":{"firstMatch":[{"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"platformName":"Android","platformVersion":"12.0","deviceName":"OnePlus AC2001","udid":"c21669c8","appPackage":"de.CENSORED.android.sample","appActivity":".MainActivity","app":"/Users/pdesire/Documents/Projects/CENSORED-android/sample/build/intermediates/apk/debug/sample-debug.apk","driver":"compose","automationName":"espresso","allowTestPackages":true,"tmpDir":"/Users/pdesire/Documents/Projects/driver-tmp","forceEspressoRebuild":true,"espressoBuildConfig":"{\"toolsVersions\": {\"composeVersion\": \"1.1.1\", \"compileSdk\":\"31\", \"minSdk\":\"31\", \"kotlin\":\"1.6.10\"}}","ensureWebviewsHavePages":true,"nativeWebScreenshot":true,"newCommandTimeout":3600,"connectHardwareKeyboard":true},"platformName":"Android","platformVersion":"12.0","deviceName":"c21669c8","udid":"c21669c8","...
[debug] [EspressoDriver@863f (ec95dc83)] [Instrumentation] Process crashed while executing startEspressoServer(io.appium.espressoserver.EspressoServerRunnerTest):
[debug] [EspressoDriver@863f (ec95dc83)] java.lang.NoSuchMethodError: No static method isTraceInProgress()Z in class Landroidx/compose/runtime/ComposerKt; or its super classes (declaration of 'androidx.compose.runtime.ComposerKt' appears in /data/app/~~jG77LgD9W8KsWqn9LO2Pbg==/io.appium.espressoserver.test-TZ0aoPsVr_UrONxzKJmEwg==/base.apk)
[debug] [EspressoDriver@863f (ec95dc83)] 	at androidx.compose.material.MaterialThemeKt.MaterialTheme(Unknown Source:10)
[debug] [EspressoDriver@863f (ec95dc83)] 	at de.CENSORED.android.sample.ui.theme.ThemeKt.RouterAppTheme(Theme.kt:34)
[debug] [EspressoDriver@863f (ec95dc83)] 	at de.CENSORED.android.sample.RouterAppKt.RouterApp(RouterApp.kt:65)
[debug] [EspressoDriver@863f (ec95dc83)] 	at de.CENSORED.android.sample.ComposableSingletons$MainActivityKt$lambda-1$1.invoke(MainActivity.kt:14)
[debug] [EspressoDriver@863f (ec95dc83)] 	at de.CENSORED.android.sample.ComposableSingletons$MainActivityKt$lambda-1$1.invoke(MainActivity.kt:13)
[debug] [EspressoDriver@863f (ec95dc83)] 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
[debug] [EspressoDriver@863f (ec95dc83)] 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
[debug] [EspressoDriver@863f (ec95dc83)] 	at androidx.compose.ui.platform.ComposeView.Content(ComposeView.android.kt:410)
[debug] [EspressoDriver@863f (ec95dc83)] 	at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:252)
[debug] [EspressoDriver@863f (ec95dc83)] 	at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:251)
[debug] [EspressoDriver@863f (ec95dc83)] 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
[debug] [EspressoDriver@863f (ec95dc83)] 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
[debug] [EspressoDriver@863f (ec95dc83)] 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
[debug] [EspressoDriver@863f (ec95dc83)] 	at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals(CompositionLocals.kt:166)
[debug] [EspressoDriver@863f (ec95dc83)] 	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:123)
[debug] [EspressoDriver@863f (ec95dc83)] 	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:122)
[debug] [EspressoDriver@863f (ec95dc83)] 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
[debug] [EspressoDriver@863f (ec95dc83)] 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
[debug] [EspressoDriver@863f (ec95dc83)] 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
[debug] [EspressoDriver@863f (ec95dc83)] 	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals(AndroidCompositionLocals.android.kt:114)
[debug] [EspressoDriver@863f (ec95dc83)] 	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke(Wrapper.android.kt:157)
[debug] [EspressoDriver@863f (ec95dc83)] 	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke(Wrapper.android.kt:156)
[debug] [EspressoDriver@863f (ec95dc83)] 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
[debug] [EspressoDriver@863f (ec95dc83)] 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
[debug] [EspressoDriver@863f (ec95dc83)] 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
[debug] [EspressoDriver@863f (ec95dc83)] 	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:156)
[debug] [EspressoDriver@863f (ec95dc83)] 	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:140)
[debug] [EspressoDriver@863f (ec95dc83)] 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
[debug] [EspressoDriver@863f (ec95dc83)] 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
[debug] [EspressoDriver@863f (ec95dc83)] 	at androidx.compose.runtime.ComposerKt.invokeComposable(Composer.kt:3337)
[debug] [EspressoDriver@863f (ec95dc83)] 	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:2582)
[debug] [EspressoDriver@863f (ec95dc83)] 	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:2571)
[debug] [EspressoDriver@863f (ec95dc83)] 	at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:247)
[debug] [EspressoDriver@863f (ec95dc83)] 	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:1)
[debug] [EspressoDriver@863f (ec95dc83)] 	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:2571)
[debug] [EspressoDriver@863f (ec95dc83)] 	at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(Composer.kt:2522)
[debug] [EspressoDriver@863f (ec95dc83)] 	at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:478)
[debug] [EspressoDriver@863f (ec95dc83)] 	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:748)
[debug] [EspressoDriver@863f (ec95dc83)] 	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:433)
[debug] [EspressoDriver@863f (ec95dc83)] 	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:140)
[debug] [EspressoDriver@863f (ec95dc83)] 	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:131)
[debug] [EspressoDriver@863f (ec95dc83)] 	at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(AndroidComposeView.android.kt:907)
[debug] [EspressoDriver@863f (ec95dc83)] 	at androidx.compose.ui.platform.WrappedComposition.setContent(Wrapper.android.kt:131)
[debug] [EspressoDriver@863f (ec95dc83)] 	at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Wrapper.android.kt:182)
[debug] [EspressoDriver@863f (ec95dc83)] 	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
[debug] [EspressoDriver@863f (ec95dc83)] 	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:196)
[debug] [EspressoDriver@863f (ec95dc83)] 	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:138)
[debug] [EspressoDriver@863f (ec95dc83)] 	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:131)
[debug] [EspressoDriver@863f (ec95dc83)] 	at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:994)
[debug] [EspressoDriver@863f (ec95dc83)] 	at android.view.View.dispatchAttachedToWindow(View.java:20812)
[debug] [EspressoDriver@863f (ec95dc83)] 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3490)
[debug] [EspressoDriver@863f (ec95dc83)] 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
[debug] [EspressoDriver@863f (ec95dc83)] 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
[debug] [EspressoDriver@863f (ec95dc83)] 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
[debug] [EspressoDriver@863f (ec95dc83)] 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
[debug] [EspressoDriver@863f (ec95dc83)] 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2675)
[debug] [EspressoDriver@863f (ec95dc83)] 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2179)
[debug] [EspressoDriver@863f (ec95dc83)] 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8800)
[debug] [EspressoDriver@863f (ec95dc83)] 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
[debug] [EspressoDriver@863f (ec95dc83)] 	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
[debug] [EspressoDriver@863f (ec95dc83)] 	at android.view.Choreographer.doFrame(Choreographer.java:780)
[debug] [EspressoDriver@863f (ec95dc83)] 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
[debug] [EspressoDriver@863f (ec95dc83)] 	at android.os.Handler.handleCallback(Handler.java:938)
[debug] [EspressoDriver@863f (ec95dc83)] 	at android.os.Handler.dispatchMessage(Handler.java:99)
[debug] [EspressoDriver@863f (ec95dc83)] 	at android.os.Looper.loopOnce(Looper.java:201)
[debug] [EspressoDriver@863f (ec95dc83)] 	at android.os.Looper.loop(Looper.java:288)
[debug] [EspressoDriver@863f (ec95dc83)] 	at android.app.ActivityThread.main(ActivityThread.java:7871)
[debug] [EspressoDriver@863f (ec95dc83)] 	at java.lang.reflect.Method.invoke(Native Method)
[debug] [EspressoDriver@863f (ec95dc83)] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
[debug] [EspressoDriver@863f (ec95dc83)] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
[EspressoDriver@863f (ec95dc83)] socket hang up
[debug] [EspressoDriver@863f (ec95dc83)] Deleting espresso session
[debug] [ADB] Running '/Users/pdesire/Library/Android/sdk/platform-tools/adb -P 5037 -s c21669c8 shell am force-stop de.CENSORED.android.sample'
[debug] [EspressoDriver@863f (ec95dc83)] [Instrumentation] INSTRUMENTATION_RESULT: shortMsg=Process crashed.
[debug] [EspressoDriver@863f (ec95dc83)] INSTRUMENTATION_CODE: 0
[debug] [Logcat] Stopping logcat capture
[EspressoDriver@863f (ec95dc83)] Restoring hidden api policy to the device default configuration
[debug] [ADB] Running '/Users/pdesire/Library/Android/sdk/platform-tools/adb -P 5037 -s c21669c8 shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy''
[debug] [ADB] Removing forwarded port socket connection: 8300
[debug] [ADB] Running '/Users/pdesire/Library/Android/sdk/platform-tools/adb -P 5037 -s c21669c8 forward --remove tcp:8300'
[debug] [AppiumDriver@891a] Event 'newSessionStarted' logged at 1649064256138 (11:24:16 GMT+0200 (Mitteleuropäische Sommerzeit))
[debug] [AppiumDriver@891a] Encountered internal error running command: A new session could not be created. Details: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up. Check https://github.com/appium/appium-espresso-driver#troubleshooting regarding advanced session startup troubleshooting.
[debug] [AppiumDriver@891a] UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up. Check https://github.com/appium/appium-espresso-driver#troubleshooting regarding advanced session startup troubleshooting.
[debug] [AppiumDriver@891a]     at EspressoProxy.command (/Users/pdesire/.appium/node_modules/appium-espresso-driver/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:277:13)
[debug] [AppiumDriver@891a]     at runMicrotasks (<anonymous>)
[debug] [AppiumDriver@891a]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[debug] [AppiumDriver@891a]     at EspressoRunner.startSession (/Users/pdesire/.appium/node_modules/appium-espresso-driver/lib/espresso-runner.js:310:5)
[debug] [AppiumDriver@891a]     at EspressoDriver.startEspressoSession (/Users/pdesire/.appium/node_modules/appium-espresso-driver/lib/driver.js:443:5)
[debug] [AppiumDriver@891a]     at EspressoDriver.createSession (/Users/pdesire/.appium/node_modules/appium-espresso-driver/lib/driver.js:224:7)
[debug] [AppiumDriver@891a]     at AppiumDriver.createSession (/usr/local/lib/node_modules/appium/lib/appium.js:253:35)
[HTTP] <-- POST /wd/hub/session 500 10717 ms - 1427
[HTTP]
[EspressoDriver@863f] Instrumentation process exited with code 0 from signal null
````

(Sorry I've had to censor some things in their namings, so the log is only modified in terms of some names)

The app itself launches completely fine, just with the test driver it fails completely.
I don't know right now if I provided enough, but if you gonna need more information, I'll ofc provide you them.

**Comment by cmaganu** [comment]
try adding "androidx.activity:activity:$activity_version" to https://github.com/appium/appium-espresso-driver#additionalandroidtestdependencies
that solved the issue for me.
* for activity_version check your app's dependencies to see which version gets bundled - it might differ from the one declared in build.gradle or try one from there https://developer.android.com/jetpack/androidx/releases/activity stable/alpha

**Comment by PDesire** [comment]
Thankyou, that made it! I'll close this issue now.
