### ISSUE TITLE
'androidx.startup.StartupException: java.lang.NoSuchMethodError' when launching inspection session

### ISSUE THREAD

**Issue by gosr** [appium/appium-espresso-driver#768]
I'm targeting my debug app (debug build with no minify and no shrink resources), using this config in Appium Inspector:

> {
>   "deviceName": "emulator-5554",
>   "platformName": "Android",
>   "udid": "emulator-5554",
>   "app": "Users/Shared/my-app-debug.apk",
>   "automationName": "espresso",
>   "noReset": "true",
>   "fullReset": "false",
>   "appPackage": "my.app.package.name.debug",
>   "appActivity": "my.feature.MainActivity",
>   "forceEspressoRebuild": "true"
> }

The inspection session crashes and I see this output in logcat:

> 2022-04-11 15:20:17.680 10100-10100/my.app.package.name.debug E/AndroidJUnitRunner: An unhandled exception was thrown by the app.
> 2022-04-11 15:20:17.684 2622-2622/? E/adbd: failed to connect to socket 'tcp:6791': Connection refused
> 2022-04-11 15:20:17.689 10100-10100/my.app.package.name.debug E/InstrumentationResultPrinter: Failed to mark test No Tests as finished after process crash
> 2022-04-11 15:20:17.690 10100-10100/my.app.package.name.debug I/AndroidJUnitRunner: Bringing down the entire Instrumentation process.
> 2022-04-11 15:20:17.691 10100-10100/my.app.package.name.debug E/MonitoringInstr: Exception encountered by: null. Dumping thread state to outputs and pining for the fjords.
>     androidx.startup.StartupException: androidx.startup.StartupException: java.lang.NoSuchMethodError: No virtual method getTargetState()Landroidx/lifecycle/Lifecycle$State; in class Landroidx/lifecycle/Lifecycle$Event; or its super classes (declaration of 'androidx.lifecycle.Lifecycle$Event' appears in /data/app/io.appium.espressoserver.test-1eAdkPkjlG0E9nVCD53_-g==/base.apk)
>         at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:162)
>         at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:198)
>         at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:42)
>         at android.content.ContentProvider.attachInfo(ContentProvider.java:1917)
>         at android.content.ContentProvider.attachInfo(ContentProvider.java:1892)
>         at android.app.ActivityThread.installProvider(ActivityThread.java:6239)
>         at android.app.ActivityThread.installContentProviders(ActivityThread.java:5805)
>         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5722)
>         at android.app.ActivityThread.-wrap1(Unknown Source:0)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
>         at android.os.Handler.dispatchMessage(Handler.java:106)
>         at android.os.Looper.loop(Looper.java:164)
>         at android.app.ActivityThread.main(ActivityThread.java:6494)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
>      Caused by: androidx.startup.StartupException: java.lang.NoSuchMethodError: No virtual method getTargetState()Landroidx/lifecycle/Lifecycle$State; in class Landroidx/lifecycle/Lifecycle$Event; or its super classes (declaration of 'androidx.lifecycle.Lifecycle$Event' appears in /data/app/io.appium.espressoserver.test-1eAdkPkjlG0E9nVCD53_-g==/base.apk)
>         at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:162)
>         at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:148)
>         at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:198) 
>         at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:42) 
>         at android.content.ContentProvider.attachInfo(ContentProvider.java:1917) 
>         at android.content.ContentProvider.attachInfo(ContentProvider.java:1892) 
>         at android.app.ActivityThread.installProvider(ActivityThread.java:6239) 
>         at android.app.ActivityThread.installContentProviders(ActivityThread.java:5805) 
>         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5722) 
>         at android.app.ActivityThread.-wrap1(Unknown Source:0) 
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656) 
>         at android.os.Handler.dispatchMessage(Handler.java:106) 
>         at android.os.Looper.loop(Looper.java:164) 
>         at android.app.ActivityThread.main(ActivityThread.java:6494) 
>         at java.lang.reflect.Method.invoke(Native Method) 
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
>      Caused by: java.lang.NoSuchMethodError: No virtual method getTargetState()Landroidx/lifecycle/Lifecycle$State; in class Landroidx/lifecycle/Lifecycle$Event; or its super classes (declaration of 'androidx.lifecycle.Lifecycle$Event' appears in /data/app/io.appium.espressoserver.test-1eAdkPkjlG0E9nVCD53_-g==/base.apk)
>         at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
>         at androidx.lifecycle.ProcessLifecycleOwner.attach(ProcessLifecycleOwner.java:161)
>         at androidx.lifecycle.ProcessLifecycleOwner.init(ProcessLifecycleOwner.java:106)
>         at androidx.lifecycle.ProcessLifecycleInitializer.create(ProcessLifecycleInitializer.java:36)
>         at androidx.lifecycle.ProcessLifecycleInitializer.create(ProcessLifecycleInitializer.java:30)
>         at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:155)
>         at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:148) 
>         at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:198) 
>         at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:42) 
>         at android.content.ContentProvider.attachInfo(ContentProvider.java:1917) 
>         at android.content.ContentProvider.attachInfo(ContentProvider.java:1892) 
>         at android.app.ActivityThread.installProvider(ActivityThread.java:6239) 
>         at android.app.ActivityThread.installContentProviders(ActivityThread.java:5805) 
>         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5722) 
>         at android.app.ActivityThread.-wrap1(Unknown Source:0) 
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656) 
>         at android.os.Handler.dispatchMessage(Handler.java:106) 
>         at android.os.Looper.loop(Looper.java:164) 
>         at android.app.ActivityThread.main(ActivityThread.java:6494) 
>         at java.lang.reflect.Method.invoke(Native Method) 
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by gosr** [comment]
This seems to have happened because I was missing `espressoBuildConfig` capability.
