### ISSUE TITLE
"Cannot read property 'sendAction' of undefined" when scrolling

### ISSUE THREAD

**Issue by gosr** [appium/appium-espresso-driver#783]
When executing a `Perform()` command using Appium.Net (on a `TouchAction` instance), the Espresso driver crashes with:

```
2022-05-23 11:43:28:412 [HTTP] --> POST /wd/hub/session/ad8742c7-2b55-475b-aa08-c56b43efbc5e/touch/perform
2022-05-23 11:43:28:412 [HTTP] {"actions":[{"action":"press","options":{"x":721,"y":1733}},{"action":"wait","options":{"ms":500}},{"action":"moveTo","options":{"x":721,"y":577}},{"action":"release"}]}
2022-05-23 11:43:28:413 [EspressoDriver@7c4f (ad8742c7)] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"x":721,"y":1733}},{"action":"wait","options":{"ms":500}},{"action":"moveTo","options":{"x":721,"y":577}},{"action":"release"}],"ad8742c7-2b55-475b-aa08-c56b43efbc5e"]
2022-05-23 11:43:28:436 [EspressoDriver@7c4f (ad8742c7)] Encountered internal error running command: TypeError: Cannot read property 'sendAction' of undefined
2022-05-23 11:43:28:436 [EspressoDriver@7c4f (ad8742c7)]     at EspressoDriver.doSwipe (/Users/<user>/.appium/node_modules/appium-espresso-driver/node_modules/appium-android-driver/lib/commands/actions.js:74:33)
2022-05-23 11:43:28:436 [EspressoDriver@7c4f (ad8742c7)]     at EspressoDriver.swipe (/Users/<user>/.appium/node_modules/appium-espresso-driver/node_modules/appium-android-driver/lib/commands/actions.js:67:21)
2022-05-23 11:43:28:436 [EspressoDriver@7c4f (ad8742c7)]     at EspressoDriver.performTouch (/Users/<user>/.appium/node_modules/appium-espresso-driver/node_modules/appium-android-driver/lib/commands/touch.js:192:23)
2022-05-23 11:43:28:436 [EspressoDriver@7c4f (ad8742c7)]     at runMicrotasks (<anonymous>)
2022-05-23 11:43:28:437 [EspressoDriver@7c4f (ad8742c7)]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
2022-05-23 11:43:28:456 [HTTP] <-- POST /wd/hub/session/ad8742c7-2b55-475b-aa08-c56b43efbc5e/touch/perform 500 44 ms - 653
```

If touch actions aren't implemented in the Espresso driver yet, how would you perform scrolling?

I'm using Appium2 btw.

**Comment by mykola-mokhnach** [comment]
Espresso supports W3C actions, so consider to use them instead on the client side as it is the only spec officially supported by W3C.

**Comment by gosr** [comment]
I just tried to use what is mentioned here (in the C# section):
http://appium.io/docs/en/commands/interactions/actions/

And I get a 501 back:
```
2022-05-23 12:47:57:599 [HTTP] --> POST /wd/hub/session/337960e8-4b7e-45ff-bee2-a2443bc765a2/actions
2022-05-23 12:47:57:599 [HTTP] {"actions":[{"type":"pointer","id":"e51415f3-cf87-4a89-b742-321a05a6def0","parameters":{"pointerType":"touch"},"actions":[{"type":"pointerMove","duration":0,"origin":"pointer","x":721,"y":1733},{"type":"pointerDown","button":0},{"type":"pause","duration":1000},{"type":"pointerUp","button":0}]}]}
2022-05-23 12:47:57:599 [EspressoDriver@74b8 (337960e8)] Driver proxy active, passing request on via HTTP proxy
2022-05-23 12:47:57:600 [Chromedriver@a083 (6fd6b963)] Matched '/wd/hub/session/337960e8-4b7e-45ff-bee2-a2443bc765a2/actions' to command name 'performActions'
2022-05-23 12:47:57:601 [Chromedriver@a083 (6fd6b963)] Proxying [POST /wd/hub/session/337960e8-4b7e-45ff-bee2-a2443bc765a2/actions] to [POST http://127.0.0.1:8009/session/6fd6b963bbf98c7a415d2cb253209dde/actions] with body: {"actions":[{"type":"pointer","id":"e51415f3-cf87-4a89-b742-321a05a6def0","parameters":{"pointerType":"touch"},"actions":[{"type":"pointerMove","duration":0,"origin":"pointer","x":721,"y":1733},{"type":"pointerDown","button":0},{"type":"pause","duration":1000},{"type":"pointerUp","button":0}]}]}
2022-05-23 12:47:57:603 [Chromedriver@a083 (6fd6b963)] Got response with status 501: unimplemented command: session/6fd6b963bbf98c7a415d2cb253209dde/actions
```

**Comment by KazuCocoa** [comment]
It is `Chromedriver` in your case (not espresso native app context?). Could you share the full appium log as gist to understand the situation?

**Comment by mykola-mokhnach** [comment]
> I just tried to use what is mentioned here (in the C# section): http://appium.io/docs/en/commands/interactions/actions/
> 
> And I get a 501 back:
> 
> ```
> 2022-05-23 12:47:57:599 [HTTP] --> POST /wd/hub/session/337960e8-4b7e-45ff-bee2-a2443bc765a2/actions
> 2022-05-23 12:47:57:599 [HTTP] {"actions":[{"type":"pointer","id":"e51415f3-cf87-4a89-b742-321a05a6def0","parameters":{"pointerType":"touch"},"actions":[{"type":"pointerMove","duration":0,"origin":"pointer","x":721,"y":1733},{"type":"pointerDown","button":0},{"type":"pause","duration":1000},{"type":"pointerUp","button":0}]}]}
> 2022-05-23 12:47:57:599 [EspressoDriver@74b8 (337960e8)] Driver proxy active, passing request on via HTTP proxy
> 2022-05-23 12:47:57:600 [Chromedriver@a083 (6fd6b963)] Matched '/wd/hub/session/337960e8-4b7e-45ff-bee2-a2443bc765a2/actions' to command name 'performActions'
> 2022-05-23 12:47:57:601 [Chromedriver@a083 (6fd6b963)] Proxying [POST /wd/hub/session/337960e8-4b7e-45ff-bee2-a2443bc765a2/actions] to [POST http://127.0.0.1:8009/session/6fd6b963bbf98c7a415d2cb253209dde/actions] with body: {"actions":[{"type":"pointer","id":"e51415f3-cf87-4a89-b742-321a05a6def0","parameters":{"pointerType":"touch"},"actions":[{"type":"pointerMove","duration":0,"origin":"pointer","x":721,"y":1733},{"type":"pointerDown","button":0},{"type":"pause","duration":1000},{"type":"pointerUp","button":0}]}]}
> 2022-05-23 12:47:57:603 [Chromedriver@a083 (6fd6b963)] Got response with status 501: unimplemented command: session/6fd6b963bbf98c7a415d2cb253209dde/actions
> ```

It looks like chromedriver does not support W3C actions. Try to run them in native context.

**Comment by gosr** [comment]
Thanks, it works in native context.
