### ISSUE TITLE
java.lang.NoSuchMethodError: No direct method <init>(Landroidx/lifecycle/ViewModelStore

### ISSUE THREAD

**Issue by gosr** [appium/appium-espresso-driver#806]
The Espresso driver is crashing on startup.

```
2022-08-04 10:32:18:441 [EspressoDriver@8f5d (a76c547f)] Proxying [POST /session] to [POST http://127.0.0.1:8201/session] with body: {"capabilities":{"firstMatch":[{"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"platformName":"Android","automationName":"espresso","forceEspressoRebuild":false,"noReset":true,"fullReset":false,"deviceName":"Nexus6","platformVersion":"8.1","udid":"emulator-5554","systemPort":8201,"app":"<apk>","appPackage":"<packagename>","appActivity":"<activity>","newCommandTimeout":360,"autoLaunch":true,"showGradleLog":true,"autoGrantPermissions":true,"espressoBuildConfig":"{\"toolsVersions\":{\"kotlin\":\"1.7.0\",\"composeVersion\":\"1.2.0\",\"minSdk\":24,\"compileSdk\":33,\"sourceCompatibility\":null,\"targetCompatibility\":null},\"additionalAppDependencies\":[\"org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.0\",\"org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.3\...
2022-08-04 10:32:22:662 [EspressoDriver@8f5d (a76c547f)] [Instrumentation] Process crashed while executing startEspressoServer(io.appium.espressoserver.EspressoServerRunnerTest):
2022-08-04 10:32:22:663 [EspressoDriver@8f5d (a76c547f)] java.lang.NoSuchMethodError: No direct method <init>(Landroidx/lifecycle/ViewModelStore;Landroidx/lifecycle/ViewModelProvider$Factory;Landroidx/lifecycle/viewmodel/CreationExtras;ILkotlin/jvm/internal/DefaultConstructorMarker;)V in class Landroidx/lifecycle/ViewModelProvider; or its super classes (declaration of 'androidx.lifecycle.ViewModelProvider' appears in /data/app/io.appium.espressoserver.test-cdL3sOuGXz3Knhkct4cihA==/base.apk)
2022-08-04 10:32:22:663 [EspressoDriver@8f5d (a76c547f)] 	at androidx.navigation.NavControllerViewModel$Companion.getInstance(NavControllerViewModel.kt:77)
2022-08-04 10:32:22:663 [EspressoDriver@8f5d (a76c547f)] 	at androidx.navigation.NavController.setViewModelStore(NavController.kt:2166)
2022-08-04 10:32:22:663 [EspressoDriver@8f5d (a76c547f)] 	at androidx.navigation.NavHostController.setViewModelStore(NavHostController.kt:101)
2022-08-04 10:32:22:663 [EspressoDriver@8f5d (a76c547f)] 	at androidx.navigation.fragment.NavHostFragment.onCreate(NavHostFragment.kt:136)
2022-08-04 10:32:22:663 [EspressoDriver@8f5d (a76c547f)] 	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2949)
2022-08-04 10:32:22:663 [EspressoDriver@8f5d (a76c547f)] 	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
2022-08-04 10:32:22:663 [EspressoDriver@8f5d (a76c547f)] 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)
2022-08-04 10:32:22:663 [EspressoDriver@8f5d (a76c547f)] 	at androidx.fragment.app.FragmentLayoutInflaterFactory.onCreateView(FragmentLayoutInflaterFactory.java:140)
2022-08-04 10:32:22:663 [EspressoDriver@8f5d (a76c547f)] 	at androidx.fragment.app.FragmentController.onCreateView(FragmentController.java:135)
2022-08-04 10:32:22:664 [EspressoDriver@8f5d (a76c547f)] 	at androidx.fragment.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:319)
2022-08-04 10:32:22:664 [EspressoDriver@8f5d (a76c547f)] 	at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:298)
2022-08-04 10:32:22:664 [EspressoDriver@8f5d (a76c547f)] 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:780)
2022-08-04 10:32:22:664 [EspressoDriver@8f5d (a76c547f)] 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
2022-08-04 10:32:22:664 [EspressoDriver@8f5d (a76c547f)] 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
2022-08-04 10:32:22:664 [EspressoDriver@8f5d (a76c547f)] 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
2022-08-04 10:32:22:664 [EspressoDriver@8f5d (a76c547f)] 	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
2022-08-04 10:32:22:664 [EspressoDriver@8f5d (a76c547f)] 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
2022-08-04 10:32:22:664 [EspressoDriver@8f5d (a76c547f)] 	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
2022-08-04 10:32:22:664 [EspressoDriver@8f5d (a76c547f)] 	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:706)
2022-08-04 10:32:22:664 [EspressoDriver@8f5d (a76c547f)] 	at androidx.appcompat.app.BaseContextWrappingDelegate.setContentView(BaseContextWrappingDelegate.kt:50)
2022-08-04 10:32:22:664 [EspressoDriver@8f5d (a76c547f)] 	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)
```

Setting `"androidx.lifecycle:lifecycle-extensions:2.2.0"` or `"androidx.lifecycle:lifecycle-viewmodel-ktx:2.4.0"` as part of the `AdditionalAppDependencies` doesn't help.

`{"version":"2.0.0-beta.33","git-sha":"3fea5493a431ac64470d4230d4b51438cf213bd1","built":"2021-03-29 12:49:10 -0700"}`
`espresso@2.8.2`

**Comment by gosr** [comment]
I managed to make it work by adding `"androidx.lifecycle:lifecycle-viewmodel:2.5.0"` to **additionalAndroidTestDependencies**.

**Comment by sudo-naim** [comment]
@gosr how and where did you add 'androidx.lifecycle:lifecycle-viewmodel:2.5.0' to additionalAndroidTestDependencies ?

**Comment by gosr** [comment]
> @gosr how and where did you add 'androidx.lifecycle:lifecycle-viewmodel:2.5.0' to additionalAndroidTestDependencies ?

When you're configuring your Espresso driver, you can do this: https://github.com/appium/appium-espresso-driver?tab=readme-ov-file#additionalandroidtestdependencies
