### ISSUE TITLE
After relaunch application no more ui interacts with application as if property "appium:espressoBuildConfig" is lost

### ISSUE THREAD

**Issue by LissaRider** [appium/appium-espresso-driver#862]
Environment:

- Appium: 2.0.0-beta.57
- Espresso driver espresso: 2.16.1
- Java 11

Appium capabilities:

Creating session with W3C capabilities: {
            "platformName": "android",
            "appium:adbExecTimeout": 600000,
            "appium:adbPort": 5037,
            "appium:allowTestPackages": false,
            "appium:androidDeviceReadyTimeout": 600,
            "appium:androidInstallTimeout": 600000,
            "appium:app": "my.app.apk",
            "appium:appActivity": "my.app.main.activity",
            "appium:appPackage": "my.app.package",
            "appium:appWaitDuration": 600000,
            "appium:autoGrantPermissions": true,
            "appium:autoLaunch": false,
            "appium:automationName": "Espresso",
            "appium:avd": "Nexus_5X_API_30",
            "appium:avdArgs": "-no-audio",
            "appium:avdLaunchTimeout": 600000,
            "appium:avdReadyTimeout": 600000,
            "appium:clearDeviceLogsOnStart": false,
             "appium:deviceName": "Android Emulator",
            "appium:deviceReadyTimeout": 600,
             "appium:dontStopAppOnReset": true,
            "appium:espressoBuildConfig": "{\"toolsVersions\":{\"minSdk\":26,\"composeVersion\":\"1.3.3\",\"targetSdk\":33,\"compileSdk\":\"33\"}}",
            "appium:espressoServerLaunchTimeout": 600000,
            "appium:forceEspressoRebuild": true,
            "appium:fullReset": false,
            "appium:ignoreHiddenApiPolicyError": true,
            "appium:isHeadless": false,
            "appium:newCommandTimeout": 600,
            "appium:noReset": false,
            "appium:orientation": "PORTRAIT",
            "appium:printPageSourceOnFindFailure": false,
            "appium:resetKeyboard": true,
            "appium:showGradleLog": true,
            "appium:skipServerInstallation": false,
            "appium:systemPort": 8221,
            "appium:unicodeKeyboard": true
}

Appium server is started automatically with the driver (new AndroidDriver(getAppiumDriverLocalService(), desiredCapabilities)).
 App has few pages with compose elements (for example, main activity page).
I run a suite of tests.
Each test ends with the application closing (driver.terminate(bundleId)) and starts with the application opening (driver.activate(bundleId)) .
Automation logic is separated. 
UiAutomator2: suite passed.
Espresso: suite failed. First test passed, then the second one started: it opens app, verifies current activity, but then crashed as if property "appium:espressoBuildConfig" is lost. No more ui interacts with application.
Each test is passed individually.

Of course, I can make it hard at the end to return to the first page, but I have tests that require reopening the application (for example, with biometrics) and I have to use Espresso driver (must have).

```
2023-03-23 22:31:45:176 - [debug] [EspressoDriver@d2b0 (d8680030)] Calling AppiumDriver.getSettings() with args: ["d8680030-a30e-420d-b317-32d950882d83"]
2023-03-23 22:31:45:184 - [debug] [EspressoDriver@d2b0 (d8680030)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: 'GET /appium/settings' cannot be proxied to Espresso server because the instrumentation process has crashed. Check the Appium server log and the logcat output for more details
2023-03-23 22:31:45:184 - [debug] [EspressoDriver@d2b0 (d8680030)]     at EspressoProxy.command (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:342:13)
2023-03-23 22:31:45:184 - [debug] [EspressoDriver@d2b0 (d8680030)]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-03-23 22:31:45:184 - [debug] [EspressoDriver@d2b0 (d8680030)]     at EspressoDriver.getSettings (/Users/alice.fabler/.appium/node_modules/appium-espresso-driver/lib/commands/general.js:288:10)
2023-03-23 22:31:45:185 - [HTTP] <-- GET /wd/hub/session/d8680030-a30e-420d-b317-32d950882d83/appium/settings 500 9 ms - 936
```

```
INFO       org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: 'GET /appium/settings' cannot be proxied to Espresso server because the instrumentation process has crashed. Check the Appium server log and the logcat output for more details
Build info: version: '4.7.2', revision: '4d4020c3b7'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '13.2.1', java.version: '11.0.18'
Driver info: io.appium.java_client.android.AndroidDriver
Command: [d8680030-a30e-420d-b317-32d950882d83, getSettings {}]
```
or

```
2023-03-23 22:47:37:285 - [HTTP] --> POST /wd/hub/session/02db5f21-1f2c-47bf-a01e-6812972f00f1/element
2023-03-23 22:47:37:285 - [HTTP] {"using":"xpath","value":"//*[contains(@resource-id, 'id/bottom_navigation')]"}
2023-03-23 22:47:37:286 - [EspressoDriver@4915 (02db5f21)] Driver proxy active, passing request on via HTTP proxy
2023-03-23 22:47:37:287 - [HTTP] <-- POST /wd/hub/session/02db5f21-1f2c-47bf-a01e-6812972f00f1/element 400 2 ms - 2050
2023-03-23 22:47:37:287 - [HTTP] 
мар. 23, 2023 10:47:37 PM org.openqa.selenium.remote.ErrorCodes toStatus
INFO: HTTP Status: '400' -> incorrect JSON status mapping for 'unknown error' (500 expected)
```

**Comment by LissaRider** [comment]
I've searched and read a little more information, experimented with a simple example.
Espresso driver can only work with one application.
It turns out that in order for me to restart the application with Espresso, I need to close the old driver and open the new driver without resetting the application.
As a result, I need to separate the logic of starting and stopping the appium server and starting and stopping the driver in order to implement the driver orchestrator to work with multiple windows.
Did I understand correctly? What else do I need?

**Comment by KazuCocoa** [comment]
The espresso and the application under test tie each other as your understanding. This is vanilla Espresso's architecture.
It means as your trial, the terminate app killed the espresso process as well (expected).
Starting an espresso process via instrument command launches the application under test as Espresso's architecture.  Thus, you need to create a new session every time to start the application under test and the espresso server properly.

**Comment by LissaRider** [comment]
Thanks. I got it.
