### ISSUE TITLE
.Resources$NotFoundException: String resource ID #0x7f0e001b

### ISSUE THREAD

**Issue by loomdoom** [appium/appium-espresso-driver#911]
Appium 2.1.3
espresso-driver 2.25.6

I'm building espresso on the fly in test so i use it like this:
```
Confugration
val capabilities = DesiredCapabilities()
        capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "Android")
        capabilities.setCapability(
            MobileCapabilityType.APP,
            "${File(".").absolutePath}/../{redacted}/app/build/outputs/apk/debugTest/app-debugTest.apk"
        )
        capabilities.setCapability(MobileCapabilityType.UDID, "5QBYD22823000300")

        capabilities.setCapability("forceEspressoRebuild", "true")
        capabilities.setCapability("showGradleLog", true)
        capabilities.setCapability("tmpDir", "./espresso-server")
        // Workaround for Espresso driver and Jetpack compose compatibility
        val espressoBuildConfig = """
            {
                "toolsVersions": { 
                    "compileSdk": "33",
                     "targetSdk": "32",
                     "minSdk": "29"
                },
                "additionalAndroidTestDependencies": [
                    "androidx.core:core-ktx:1.10.1",
                    "androidx.appcompat:appcompat:1.6.1",
                    "androidx.constraintlayout:constraintlayout:2.1.4",
                    "androidx.legacy:legacy-support-v4:1.0.0",
                    "com.google.android.material:material:1.9.0",
                    "androidx.activity:activity-ktx:1.7.2",
                    "com.google.android.material:material:1.2.0",
                    "app.rive:rive-android:4.0.0",
                    "androidx.camera:camera-core:1.2.3",
                    "androidx.camera:camera-camera2:1.2.3",
                    "androidx.camera:camera-lifecycle:1.2.3",
                    "androidx.camera:camera-view:1.2.3",
                    "androidx.lifecycle:lifecycle-livedata-ktx:2.6.1",
                    "androidx.lifecycle:lifecycle-viewmodel-ktx:2.6.1",
                    "androidx.navigation:navigation-fragment-ktx:2.6.0",
                    "androidx.navigation:navigation-ui-ktx:2.6.0"
                ]
            }
        """.trimIndent()
        capabilities.setCapability("espressoBuildConfig", espressoBuildConfig)
        capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, io.appium.java_client.remote.AutomationName.ESPRESSO)
        capabilities.setCapability(MobileCapabilityType.FULL_RESET, true)
        try {
            Companion.driver = AppiumDriver(URL("http://0.0.0.0:4723"), capabilities).apply {
                setSetting("driver", "compose")
            }
```
When it's run on device i get the following callstack:

```
FATAL EXCEPTION: main
                 Process: <redacted>, PID: 20658
                 java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: android.content.res.Resources$NotFoundException: String resource ID #0x7f0e001b
                 	at android.app.ActivityThread.installProvider(ActivityThread.java:8562)
                 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:8094)
                 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7941)
                 	at android.app.ActivityThread.access$2600(ActivityThread.java:278)
                 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2527)
                 	at android.os.Handler.dispatchMessage(Handler.java:109)
                 	at android.os.Looper.loop(Looper.java:228)
                 	at android.app.ActivityThread.main(ActivityThread.java:9105)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:614)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1129)
                 Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x7f0e001b
                 	at android.content.res.Resources.getText(Resources.java:496)
                 	at android.content.res.Resources.getString(Resources.java:592)
                 	at android.content.Context.getString(Context.java:645)
                 	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:216)
                 	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:206)
                 	at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:45)
                 	at android.content.ContentProvider.attachInfo(ContentProvider.java:2393)
                 	at android.content.ContentProvider.attachInfo(ContentProvider.java:2361)
                 	at android.app.ActivityThread.installProvider(ActivityThread.java:8557)
                 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:8094) 
                 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7941) 
                 	at android.app.ActivityThread.access$2600(ActivityThread.java:278) 
                 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2527) 
                 	at android.os.Handler.dispatchMessage(Handler.java:109) 
                 	at android.os.Looper.loop(Looper.java:228) 
                 	at android.app.ActivityThread.main(ActivityThread.java:9105) 
                 	at java.lang.reflect.Method.invoke(Native Method) 
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:614) 
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1129) 
```

- androidx.startup-runtime comes from  "app.rive:rive-android:4.0.0". and as far as i know it's not used directly anywhere in the code
- i've checked resources.arsc inside builtapk and there is a string with given id ("androidx_startup")
![obraz](https://github.com/appium/appium-espresso-driver/assets/11277272/47ad7acb-4883-4248-944f-7cc97a987350)
- i've checked other issues with ResourceNotFound (Drawable one)

Any ideas?

**Comment by kesavaIndla** [comment]
@loomdoom Seeing the same issue , Are you able to resolve this issue?

**Comment by loomdoom** [comment]
I dont remember what finally made it to work but
what actually worked for me looked like this:
```

 init {

        dadb.terminateApp("com.redacted.app.automatedTest")

        appiumLocalServer = startHostServer()

        var errorThrown = true
        try {
            val capabilities = DesiredCapabilities()
            capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "Android")
            capabilities.setCapability(MobileCapabilityType.UDID, dadb.toString())
            capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, ANDROID_UIAUTOMATOR2)
            //capabilities.setCapability(MobileCapabilityType.APP, apkPath)
            capabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, 0)

            //capabilities.setCapability(AndroidMobileCapabilityType.APP_PACKAGE, "com.redacted.app.automatedTest")
            //capabilities.setCapability(MobileCapabilityType.NO_RESET, true)

            extraCaps.asMap().forEach {
                capabilities.setCapability(it.key, it.value)
            }

            val androidDriver = AndroidDriver(URL("http://0.0.0.0:$appiumPort"), capabilities).apply {
                setSetting("driver", "compose")
            }

            installApp(androidDriver, apkPath)
            androidDriver.activateApp("com.redacted.app.automatedTest")


            driver = androidDriver
            instrumentationClient = InstrumentationClient(instrumentationPort)
            println(dadb.forward(instrumentationPort, 8080))
            errorThrown = false
        } catch (e: MalformedURLException) {
            e.printStackTrace()
            throw (e)
        } catch (e: Exception) {
            println(e.message)
            throw (e)
        } finally {
            if (errorThrown) {
                close()
            } else {
                instances.add(this)
            }
        }
    }
```
there were other issues like e.g. app install uninstall that i had to do using adb(dadb variable in code above) client or running custom instrumentation http server(embedded in app's test variant and client impl using retrofit - InstrumentationClient in code above)

**Comment by yaoyue1019** [comment]
I got the same issue,at last found there are 2 application in different moudules

**Comment by mdp-siteimprove** [comment]
Any news on this one?
I'm facing the same issue and I have really no idea what's going on....
I tried starting from scratch, just making a nearly blank app from the templates in Android Studio, targeting and using latest version of everything.
I've added all the same dependencies and tools in the `espressoBuildConfig`
```
{
  "toolsVersions": {
    "gradle": "8.10.2",
    "compileSdk": 35,
     "minSdk": 35,
     "targetSdk": 35
  },
  "additionalAndroidTestDependencies": [
    "junit:junit:4.13.2",
    "androidx.test.ext:junit:1.2.1",
    "androidx.test.espresso:espresso-core:3.6.1",
    "androidx.appcompat:appcompat:1.7.0",
    "com.google.android.material:material:1.12.0",
    "androidx.activity:activity:1.10.0",
    "androidx.constraintlayout:constraintlayout:2.2.0"
  ]
}
```
still, no dice....

**Comment by mykola-mokhnach** [comment]
@mdp-siteimprove I believe you could try to complie Espresso server as a library to your application under test. This feature was made possible after https://github.com/appium/appium-espresso-driver/pull/1020 was merged. However the author (@technoir42) has never got time to document the process. Probably, you could try and document it yourself.
