### ISSUE TITLE
Unable to build Espresso server

### ISSUE THREAD

**Issue by russtu** [appium/appium-espresso-driver#938]
Appium Version :2.2.0
Espresso driver version: 2.26.6

Principal error:
```
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: A new session could not be created. Details: Unable to build Espresso server - '/tmp/espresso-server-R8YW80AZNLF/gradlew' executable is not found neither in the process working folder (/tmp/espresso-server-R8YW80AZNLF) nor in any folders specified in the PATH environment variable (/home/.local/bin:/opt/gradle/latest/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin)
Build info: version: '4.9.1', revision: 'eb2032df7f'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.2.0-34-generic', java.version: '17.0.9'
Driver info: io.appium.java_client.AppiumDriver
Command: [null, newSession {capabilities=[{appium:appActivity=com.sec.android.app.popupcalculator.Calculator, appium:appPackage=com.sec.android.app.popupcalculator, appium:automationName=Espresso, appium:forceEspressoRebuild=true, appium:noReset=true, platformName=ANDROID, appium:showGradleLog=true}], desiredCapabilities=Capabilities {appActivity: com.sec.android.app.popupca..., appPackage: com.sec.android.app.popupca..., appium:automationName: Espresso, forceEspressoRebuild: true, noReset: true, platformName: ANDROID, showGradleLog: true}}]
Capabilities {appActivity: com.sec.android.app.popupca..., appPackage: com.sec.android.app.popupca..., appium:automationName: Espresso, forceEspressoRebuild: true, noReset: true, platformName: ANDROID, showGradleLog: true}
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:136)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.appium.java_client.remote.AppiumProtocolHandshake.createSession(AppiumProtocolHandshake.java:133)
	at io.appium.java_client.remote.AppiumProtocolHandshake.createSession(AppiumProtocolHandshake.java:102)
	at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:182)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:250)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:274)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:157)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:89)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:112)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:137)
	at com.example.test.AppiumTests.openApp(AppiumTests.java:69)
	at com.example.test.AppiumTests.main(AppiumTests.java:16)
```

Log:
```
[AppiumDriver@1ff4] . Check https://github.com/appium/appium-espresso-driver#troubleshooting regarding advanced session startup troubleshooting.
[AppiumDriver@1ff4] Error: Unable to build Espresso server - '/tmp/espresso-server-R8YW80AZNLF/gradlew' executable is not found neither in the process working folder (/tmp/espresso-server-R8YW80AZNLF) nor in any folders specified in the PATH environment variable (/home/.local/bin:/opt/gradle/latest/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin)
[AppiumDriver@1ff4] Gradle error message:
[AppiumDriver@1ff4] . Check https://github.com/appium/appium-espresso-driver#troubleshooting regarding advanced session startup troubleshooting.
[AppiumDriver@1ff4]     at Object.wrappedLogger.errorAndThrow (/home/node_modules/@appium/support/lib/logging.js:115:34)
[AppiumDriver@1ff4]     at ServerBuilder.runBuildProcess (/home/.appium/node_modules/appium-espresso-driver/lib/server-builder.js:200:16)
[AppiumDriver@1ff4]     at ServerBuilder.build (/home/.appium/node_modules/appium-espresso-driver/lib/server-builder.js:73:5)
[AppiumDriver@1ff4]     at EspressoRunner.buildNewModServer (/home/.appium/node_modules/appium-espresso-driver/lib/espresso-runner.js:215:5)
[AppiumDriver@1ff4]     at EspressoRunner.installTestApk (/home/.appium/node_modules/appium-espresso-driver/lib/espresso-runner.js:173:7)
[AppiumDriver@1ff4]     at EspressoDriver.initAUT (/home/.appium/node_modules/appium-espresso-driver/lib/driver.js:561:7)
[AppiumDriver@1ff4]     at EspressoDriver.startEspressoSession (/home/.appium/node_modules/appium-espresso-driver/lib/driver.js:409:5)
[AppiumDriver@1ff4]     at EspressoDriver.createSession (/home/.appium/node_modules/appium-espresso-driver/lib/driver.js:245:7)
[AppiumDriver@1ff4]     at AppiumDriver.createSession (/usr/local/lib/node_modules/appium/lib/appium.js:374:35)
[HTTP] <-- POST /session 500 3484 ms - 2242
```

**Comment by afathonih** [comment]
I saw this error couple days ago. I was able to solve it by running `gradle wrapper` inside the espresso server directory:
```
cd /home/.appium/node_modules/appium-espresso-driver/espresso-server
gradle wrapper
```

**Comment by KazuCocoa** [comment]
What's about 2.26.7 and newer? 2.26.6 - 2.26.0 had package issue

**Comment by KazuCocoa** [comment]
Let me know if still build command issue (gradle command) present with over 2.26.10.
