### ISSUE TITLE
Unable to build Espresso server

### ISSUE THREAD

**Issue by ruizhengu** [appium/appium-espresso-driver#951]
Capabilities
```
capabilities = dict(
    platformName='Android',
    # automationName='uiautomator2',
    automationName='espresso',
    deviceName='emulator-5554',
    appPackage='com.example.toyaut',
    # appPackage='com.android.settings',
    appActivity='.MainActivity',
    # appActivity='.Settings',
    language='en',
    locale='US'
)
```

Test Code
```
el = self.driver.find_element(by=AppiumBy.ANDROID_VIEW_MATCHER, value="text(\"Hello Android!\")")
```

build.gradle.kts in App
```
plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
}

android {
    namespace = "com.example.toyaut"
    compileSdk = 33
    defaultConfig {
        applicationId = "com.example.toyaut"
        minSdk = 33
        targetSdk = 33
        versionCode = 1
        versionName = "1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            useSupportLibrary = true
        }
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
    }
    buildFeatures {
        compose = true
    }
    composeOptions {
        kotlinCompilerExtensionVersion = "1.4.3"
    }
    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }
}

dependencies {

    implementation("androidx.core:core-ktx:1.9.0")
    implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.6.1")
    implementation("androidx.activity:activity-compose:1.7.0")
    implementation(platform("androidx.compose:compose-bom:2023.03.00"))
    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.ui:ui-graphics")
    implementation("androidx.compose.ui:ui-tooling-preview")
    implementation("androidx.compose.material3:material3")
    testImplementation("junit:junit:4.13.2")
    testImplementation("io.appium:java-client:9.0.0")
    androidTestImplementation("androidx.test.ext:junit:1.1.5")
    androidTestImplementation("androidx.test.espresso:espresso-core:3.5.1")
    androidTestImplementation(platform("androidx.compose:compose-bom:2023.03.00"))
    androidTestImplementation("androidx.compose.ui:ui-test-junit4")
    debugImplementation("androidx.compose.ui:ui-tooling")
    debugImplementation("androidx.compose.ui:ui-test-manifest")

    androidTestImplementation("io.cucumber:cucumber-android:7.14.0")
}
```

build.,gradle.kts in Project
```
buildscript {
    extra.apply {
        set("appiumKotlin", properties.getOrDefault("appiumKotlin", "1.8.10"))
        set(
            "appiumAndroidGradlePlugin",
            properties.getOrDefault("appiumAndroidGradlePlugin", "8.1.1")
        )
    }
}

// Top-level build file where you can add configuration options common to all sub-projects/modules.
plugins {
    id("com.android.application") version "8.1.1" apply false
    id("org.jetbrains.kotlin.android") version "1.8.10" apply false
}
//val sourceCompatibility by extra(VERSION_17)
```

Appium Log
```
[Appium] Welcome to Appium v2.2.1
[Appium] Attempting to load driver uiautomator2...
[Appium] Requiring driver at /Users/ruizhengu/.appium/node_modules/appium-uiautomator2-driver
[Appium] Attempting to load driver espresso...
[Appium] Requiring driver at /Users/ruizhengu/.appium/node_modules/appium-espresso-driver
[Appium] Appium REST http interface listener started on http://0.0.0.0:4723
[Appium] You can provide the following URLs in your client code to connect to this server:
[Appium] 	http://127.0.0.1:4723/ (only accessible from the same host)
[Appium] 	http://143.167.102.251:4723/
[Appium] 	http://143.167.96.43:4723/
[Appium] Available drivers:
[Appium]   - uiautomator2@2.34.1 (automationName 'UiAutomator2')
[Appium]   - espresso@2.29.2 (automationName 'Espresso')
[Appium] No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use.
[HTTP] Request idempotency key: f0fe5835-dec7-4884-9b84-c3da66e27c14
[HTTP] --> POST /session
[HTTP] {"capabilities":{"firstMatch":[{}],"alwaysMatch":{"appium:automationName":"espresso","platformName":"Android","appium:deviceName":"emulator-5554","appium:appPackage":"com.example.toyaut","appium:appActivity":".MainActivity","appium:language":"en","appium:locale":"US"}}}
[AppiumDriver@b6d0] Calling AppiumDriver.createSession() with args: [null,null,{"firstMatch":[{}],"alwaysMatch":{"appium:automationName":"espresso","platformName":"Android","appium:deviceName":"emulator-5554","appium:appPackage":"com.example.toyaut","appium:appActivity":".MainActivity","appium:language":"en","appium:locale":"US"}}]
[AppiumDriver@b6d0] Event 'newSessionRequested' logged at 1699552813671 (18:00:13 GMT+0000 (Greenwich Mean Time))
[Appium] Attempting to find matching driver for automationName 'espresso' and platformName 'Android'
[Appium] The 'espresso' driver was installed and matched caps.
[Appium] Will require it at /Users/ruizhengu/.appium/node_modules/appium-espresso-driver
[Appium] Requiring driver at /Users/ruizhengu/.appium/node_modules/appium-espresso-driver
[AppiumDriver@b6d0] Appium v2.2.1 creating new EspressoDriver (v2.29.2) session
[AppiumDriver@b6d0] Checking BaseDriver versions for Appium and EspressoDriver
[AppiumDriver@b6d0] Appium's BaseDriver version is 9.4.1
[AppiumDriver@b6d0] EspressoDriver's BaseDriver version is 9.4.1
[EspressoDriver@9f70] Creating session with W3C capabilities: {
[EspressoDriver@9f70]   "alwaysMatch": {
[EspressoDriver@9f70]     "platformName": "Android",
[EspressoDriver@9f70]     "appium:automationName": "espresso",
[EspressoDriver@9f70]     "appium:deviceName": "emulator-5554",
[EspressoDriver@9f70]     "appium:appPackage": "com.example.toyaut",
[EspressoDriver@9f70]     "appium:appActivity": ".MainActivity",
[EspressoDriver@9f70]     "appium:language": "en",
[EspressoDriver@9f70]     "appium:locale": "US"
[EspressoDriver@9f70]   },
[EspressoDriver@9f70]   "firstMatch": [
[EspressoDriver@9f70]     {}
[EspressoDriver@9f70]   ]
[EspressoDriver@9f70] }
[EspressoDriver@9f70 (a325502c)] Session created with session id: a325502c-a452-4b60-a111-65dd85e05e09
[ADB] Found 3 'build-tools' folders under '/Users/ruizhengu/Library/Android/sdk' (newest first):
[ADB]     /Users/ruizhengu/Library/Android/sdk/build-tools/34.0.0
[ADB]     /Users/ruizhengu/Library/Android/sdk/build-tools/33.0.2
[ADB]     /Users/ruizhengu/Library/Android/sdk/build-tools/33.0.1
[ADB] Using 'adb' from '/Users/ruizhengu/Library/Android/sdk/platform-tools/adb'
[ADB] Running '/Users/ruizhengu/Library/Android/sdk/platform-tools/adb -P 5037 start-server'
[AndroidDriver] Retrieving device list
[ADB] Trying to find connected Android devices
[ADB] Getting connected devices
[ADB] Connected devices: [{"udid":"emulator-5554","state":"device"}]
[AndroidDriver] Using device: emulator-5554
[ADB] Using 'adb' from '/Users/ruizhengu/Library/Android/sdk/platform-tools/adb'
[ADB] Running '/Users/ruizhengu/Library/Android/sdk/platform-tools/adb -P 5037 start-server'
[ADB] Setting device id to emulator-5554
[EspressoDriver@9f70 (a325502c)] App file was not listed, instead we're going to run com.example.toyaut directly on the device
[ADB] Getting install status for com.example.toyaut
[ADB] Running '/Users/ruizhengu/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell pm path com.example.toyaut'
[ADB] 'com.example.toyaut' is installed
[EspressoDriver@9f70 (a325502c)] EspressoDriver version: 2.29.2
[ADB] Running '/Users/ruizhengu/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell getprop ro.build.version.sdk'
[ADB] Current device property 'ro.build.version.sdk': 34
[ADB] Getting device platform version
[ADB] Running '/Users/ruizhengu/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell getprop ro.build.version.release'
[ADB] Current device property 'ro.build.version.release': 14
[ADB] Device API level: 34
[EspressoDriver@9f70 (a325502c)] Relaxing hidden api policy
[ADB] Running '/Users/ruizhengu/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell 'settings put global hidden_api_policy_pre_p_apps 1;settings put global hidden_api_policy_p_apps 1;settings put global hidden_api_policy 1''
[AndroidDriver] No app sent in, not parsing package/activity
[ADB] Running '/Users/ruizhengu/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 wait-for-device'
[ADB] Running '/Users/ruizhengu/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell echo ping'
[AndroidDriver] Pushing settings apk to device...
[ADB] Getting package info for 'io.appium.settings'
[ADB] Running '/Users/ruizhengu/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys package io.appium.settings'
[ADB] The version name of the installed 'io.appium.settings' is greater or equal to the application version name ('5.2.0' >= '5.2.0')
[ADB] There is no need to install/upgrade '/Users/ruizhengu/.appium/node_modules/appium-espresso-driver/node_modules/io.appium.settings/apks/settings_apk-debug.apk'
[ADB] Getting IDs of all 'io.appium.settings' processes
[ADB] Running '/Users/ruizhengu/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell 'pgrep --help; echo $?''
[ADB] Running '/Users/ruizhengu/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell pgrep -f \(\[\[:blank:\]\]\|\^\)io\.appium\.settings\(\[\[:blank:\]\]\|\$\)'
[AndroidDriver] io.appium.settings is already running. There is no need to reset its permissions.
[ADB] Running '/Users/ruizhengu/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell getprop persist.sys.locale'
[ADB] Current device property 'persist.sys.locale':
[ADB] Running '/Users/ruizhengu/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell getprop ro.product.locale'
[ADB] Current device property 'ro.product.locale': en-US
[ADB] Current locale: 'en-US'; requested locale: 'en-US'
[ADB] Running '/Users/ruizhengu/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell getprop persist.sys.locale'
[ADB] Current device property 'persist.sys.locale':
[ADB] Running '/Users/ruizhengu/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell getprop ro.product.locale'
[ADB] Current device property 'ro.product.locale': en-US
[ADB] Requested locale is equal to current locale: 'en-us'
[Logcat] Starting logs capture with command: /Users/ruizhengu/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 logcat -v threadtime
[ADB] Running '/Users/ruizhengu/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell settings get global animator_duration_scale'
[ADB] Running '/Users/ruizhengu/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell settings get global transition_animation_scale'
[ADB] Running '/Users/ruizhengu/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell settings get global window_animation_scale'
[EspressoDriver@9f70 (a325502c)] Disabling window animation as "disableWindowAnimation" capability is set to true/fallback to default value "true"
[ADB] Running '/Users/ruizhengu/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am broadcast -a io.appium.settings.animation -n io.appium.settings/.receivers.AnimationSettingReceiver --es setstatus disable'
[EspressoDriver@9f70 (a325502c)] Forwarding Espresso Server port 6791 to 8300
[ADB] Forwarding system: 8300 to device: 6791
[ADB] Running '/Users/ruizhengu/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 forward tcp:8300 tcp:6791'
[ADB] Running '/Users/ruizhengu/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys window'
[AndroidDriver] Screen already unlocked, doing nothing
[EspressoDriver@9f70 (a325502c)] No app capability. Assuming it is already on the device
[ADB] Getting install status for com.example.toyaut
[ADB] Running '/Users/ruizhengu/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell pm path com.example.toyaut'
[ADB] 'com.example.toyaut' is installed
[ADB] Running '/Users/ruizhengu/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am force-stop com.example.toyaut'
[ADB] Running '/Users/ruizhengu/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell pm clear com.example.toyaut'
[AndroidDriver] Performed fast reset on the installed 'com.example.toyaut' application (stop and clear)
[ADB] Running '/Users/ruizhengu/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell "[ -e '/data/local/tmp/espresso.apppackage' ] && echo __PASS__"'
[EspressoDriver@9f70 (a325502c)] The previous target application package is unknown
[EspressoDriver@9f70 (a325502c)] Forcing Espresso server rebuild because of changed application package
[EspressoDriver@9f70 (a325502c)] Building espresso server in '/var/folders/md/ghkjmxg95czdj95l1_tf9zxr0000gp/T/espresso-server-emulator-5554'
[EspressoDriver@9f70 (a325502c)] The build folder root could be customized by changing the 'tmpDir' capability
[EspressoDriver@9f70 (a325502c)] Copying espresso server template from ('/Users/ruizhengu/.appium/node_modules/appium-espresso-driver/espresso-server' to '/var/folders/md/ghkjmxg95czdj95l1_tf9zxr0000gp/T/espresso-server-emulator-5554')
[Support] Traversed 52 directories and 283 files in 281ms
[EspressoDriver@9f70 (a325502c)] Bulding espresso server
[EspressoDriver@9f70 (a325502c)] Beginning build with command '/var/folders/md/ghkjmxg95czdj95l1_tf9zxr0000gp/T/espresso-server-emulator-5554/gradlew -PappiumTargetPackage=com.example.toyaut app:assembleAndroidTest' in directory '/var/folders/md/ghkjmxg95czdj95l1_tf9zxr0000gp/T/espresso-server-emulator-5554'
[EspressoDriver@9f70 (a325502c)] Output from Gradle will not be logged. To change this, use 'showGradleLog' desired capability
[EspressoDriver@9f70 (a325502c)] Unable to build Espresso server - Process ended with exitcode 1 (cmd: '/var/folders/md/ghkjmxg95czdj95l1_tf9zxr0000gp/T/espresso-server-emulator-5554/gradlew -PappiumTargetPackage\=com.example.toyaut app\:assembleAndroidTest')
[EspressoDriver@9f70 (a325502c)] Gradle error message:
[EspressoDriver@9f70 (a325502c)]
[EspressoDriver@9f70 (a325502c)] [STDERR]           - Variant 'sourcesElements' capability com.android.tools.build:gradle:7.4.2 declares a runtime of a component, and its dependencies declared externally:,
[EspressoDriver@9f70 (a325502c)] [STDERR]               - Incompatible because this component declares documentation and the consumer needed a library,
[EspressoDriver@9f70 (a325502c)] [STDERR]               - Other compatible attributes:,
[EspressoDriver@9f70 (a325502c)] [STDERR]                   - Doesn't say anything about its target Java version (required compatibility with Java 8),
[EspressoDriver@9f70 (a325502c)] [STDERR]                   - Doesn't say anything about its elements (required them packaged as a jar),
[EspressoDriver@9f70 (a325502c)] [STDERR]                   - Doesn't say anything about org.gradle.plugin.api-version (required '7.5'),
[EspressoDriver@9f70 (a325502c)] [STDERR] ,
[EspressoDriver@9f70 (a325502c)] [STDERR] * Try:,
[EspressoDriver@9f70 (a325502c)] [STDERR] > Run with --stacktrace option to get the stack trace.,
[EspressoDriver@9f70 (a325502c)] [STDERR] > Run with --info or --debug option to get more log output.,
[EspressoDriver@9f70 (a325502c)] [STDERR] > Run with --scan to get full insights.,
[EspressoDriver@9f70 (a325502c)] [STDERR] ,
[EspressoDriver@9f70 (a325502c)] [STDERR] * Get more help at https://help.gradle.org,
[EspressoDriver@9f70 (a325502c)] [STDERR] ,
[EspressoDriver@9f70 (a325502c)] [STDERR] BUILD FAILED in 642ms
[EspressoDriver@9f70 (a325502c)] Deleting espresso session
[ADB] Running '/Users/ruizhengu/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys activity services io.appium.settings/.recorder.RecorderService'
[ADB] Running '/Users/ruizhengu/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am broadcast -a io.appium.settings.animation -n io.appium.settings/.receivers.AnimationSettingReceiver --es setstatus enable'
[ADB] Running '/Users/ruizhengu/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am force-stop com.example.toyaut'
[Logcat] Stopping logcat capture
[EspressoDriver@9f70 (a325502c)] Restoring hidden api policy to the device default configuration
[ADB] Running '/Users/ruizhengu/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy''
[ADB] Removing forwarded port socket connection: 8300
[ADB] Running '/Users/ruizhengu/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 forward --remove tcp:8300'
[AppiumDriver@b6d0] Event 'newSessionStarted' logged at 1699552818333 (18:00:18 GMT+0000 (Greenwich Mean Time))
[AppiumDriver@b6d0] Encountered internal error running command: A new session could not be created. Details: Unable to build Espresso server - Process ended with exitcode 1 (cmd: '/var/folders/md/ghkjmxg95czdj95l1_tf9zxr0000gp/T/espresso-server-emulator-5554/gradlew -PappiumTargetPackage\=com.example.toyaut app\:assembleAndroidTest')
[AppiumDriver@b6d0] Gradle error message:
[AppiumDriver@b6d0]
[AppiumDriver@b6d0] [STDERR]           - Variant 'sourcesElements' capability com.android.tools.build:gradle:7.4.2 declares a runtime of a component, and its dependencies declared externally:,
[AppiumDriver@b6d0] [STDERR]               - Incompatible because this component declares documentation and the consumer needed a library,
[AppiumDriver@b6d0] [STDERR]               - Other compatible attributes:,
[AppiumDriver@b6d0] [STDERR]                   - Doesn't say anything about its target Java version (required compatibility with Java 8),
[AppiumDriver@b6d0] [STDERR]                   - Doesn't say anything about its elements (required them packaged as a jar),
[AppiumDriver@b6d0] [STDERR]                   - Doesn't say anything about org.gradle.plugin.api-version (required '7.5'),
[AppiumDriver@b6d0] [STDERR] ,
[AppiumDriver@b6d0] [STDERR] * Try:,
[AppiumDriver@b6d0] [STDERR] > Run with --stacktrace option to get the stack trace.,
[AppiumDriver@b6d0] [STDERR] > Run with --info or --debug option to get more log output.,
[AppiumDriver@b6d0] [STDERR] > Run with --scan to get full insights.,
[AppiumDriver@b6d0] [STDERR] ,
[AppiumDriver@b6d0] [STDERR] * Get more help at https://help.gradle.org,
[AppiumDriver@b6d0] [STDERR] ,
[AppiumDriver@b6d0] [STDERR] BUILD FAILED in 642ms. Check https://github.com/appium/appium-espresso-driver#troubleshooting regarding advanced session startup troubleshooting.
[AppiumDriver@b6d0] Error: Unable to build Espresso server - Process ended with exitcode 1 (cmd: '/var/folders/md/ghkjmxg95czdj95l1_tf9zxr0000gp/T/espresso-server-emulator-5554/gradlew -PappiumTargetPackage\=com.example.toyaut app\:assembleAndroidTest')
[AppiumDriver@b6d0] Gradle error message:
[AppiumDriver@b6d0]
[AppiumDriver@b6d0] [STDERR]           - Variant 'sourcesElements' capability com.android.tools.build:gradle:7.4.2 declares a runtime of a component, and its dependencies declared externally:,
[AppiumDriver@b6d0] [STDERR]               - Incompatible because this component declares documentation and the consumer needed a library,
[AppiumDriver@b6d0] [STDERR]               - Other compatible attributes:,
[AppiumDriver@b6d0] [STDERR]                   - Doesn't say anything about its target Java version (required compatibility with Java 8),
[AppiumDriver@b6d0] [STDERR]                   - Doesn't say anything about its elements (required them packaged as a jar),
[AppiumDriver@b6d0] [STDERR]                   - Doesn't say anything about org.gradle.plugin.api-version (required '7.5'),
[AppiumDriver@b6d0] [STDERR] ,
[AppiumDriver@b6d0] [STDERR] * Try:,
[AppiumDriver@b6d0] [STDERR] > Run with --stacktrace option to get the stack trace.,
[AppiumDriver@b6d0] [STDERR] > Run with --info or --debug option to get more log output.,
[AppiumDriver@b6d0] [STDERR] > Run with --scan to get full insights.,
[AppiumDriver@b6d0] [STDERR] ,
[AppiumDriver@b6d0] [STDERR] * Get more help at https://help.gradle.org,
[AppiumDriver@b6d0] [STDERR] ,
[AppiumDriver@b6d0] [STDERR] BUILD FAILED in 642ms. Check https://github.com/appium/appium-espresso-driver#troubleshooting regarding advanced session startup troubleshooting.
[AppiumDriver@b6d0]     at Object.wrappedLogger.errorAndThrow (/usr/local/lib/node_modules/appium/node_modules/@appium/support/lib/logging.js:115:34)
[AppiumDriver@b6d0]     at ServerBuilder.runBuildProcess (/Users/ruizhengu/.appium/node_modules/appium-espresso-driver/lib/server-builder.js:200:16)
[AppiumDriver@b6d0]     at ServerBuilder.build (/Users/ruizhengu/.appium/node_modules/appium-espresso-driver/lib/server-builder.js:73:5)
[AppiumDriver@b6d0]     at EspressoRunner.buildNewModServer (/Users/ruizhengu/.appium/node_modules/appium-espresso-driver/lib/espresso-runner.js:215:5)
[AppiumDriver@b6d0]     at EspressoRunner.installTestApk (/Users/ruizhengu/.appium/node_modules/appium-espresso-driver/lib/espresso-runner.js:173:7)
[AppiumDriver@b6d0]     at EspressoDriver.initAUT (/Users/ruizhengu/.appium/node_modules/appium-espresso-driver/lib/driver.js:566:7)
[AppiumDriver@b6d0]     at EspressoDriver.startEspressoSession (/Users/ruizhengu/.appium/node_modules/appium-espresso-driver/lib/driver.js:414:5)
[AppiumDriver@b6d0]     at EspressoDriver.createSession (/Users/ruizhengu/.appium/node_modules/appium-espresso-driver/lib/driver.js:248:7)
[AppiumDriver@b6d0]     at AppiumDriver.createSession (/usr/local/lib/node_modules/appium/lib/appium.js:374:35)
[HTTP] <-- POST /session 500 4667 ms - 3986
[HTTP]
[HTTP] --> GET /session/4e587998-5626-4fb7-8c8d-48fa1b8dfab7/timeouts
[HTTP] {}
[AppiumDriver@b6d0] Encountered internal error running command: NoSuchDriverError: A session is either terminated or not started
[AppiumDriver@b6d0]     at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:315:15)
[AppiumDriver@b6d0]     at /usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:518:15
[AppiumDriver@b6d0]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[AppiumDriver@b6d0]     at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:144:13)
[AppiumDriver@b6d0]     at Route.dispatch (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:114:3)
[AppiumDriver@b6d0]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[AppiumDriver@b6d0]     at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:284:15
[AppiumDriver@b6d0]     at param (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:365:14)
[AppiumDriver@b6d0]     at param (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:376:14)
[AppiumDriver@b6d0]     at Function.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:421:3)
[AppiumDriver@b6d0]     at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:280:10)
[AppiumDriver@b6d0]     at logger (/usr/local/lib/node_modules/appium/node_modules/morgan/index.js:144:5)
[AppiumDriver@b6d0]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[AppiumDriver@b6d0]     at trim_prefix (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:328:13)
[AppiumDriver@b6d0]     at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:286:9
[AppiumDriver@b6d0]     at Function.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:346:12)
[AppiumDriver@b6d0]     at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:280:10)
[AppiumDriver@b6d0]     at jsonParser (/usr/local/lib/node_modules/appium/node_modules/body-parser/lib/types/json.js:113:7)
[AppiumDriver@b6d0]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[AppiumDriver@b6d0]     at trim_prefix (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:328:13)
[AppiumDriver@b6d0]     at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:286:9
[AppiumDriver@b6d0]     at Function.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:346:12)
[AppiumDriver@b6d0]     at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:280:10)
[AppiumDriver@b6d0]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:91:12)
[AppiumDriver@b6d0]     at trim_prefix (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:328:13)
[AppiumDriver@b6d0]     at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:286:9
[AppiumDriver@b6d0]     at Function.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:346:12)
[AppiumDriver@b6d0]     at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:280:10)
[HTTP] <-- GET /session/4e587998-5626-4fb7-8c8d-48fa1b8dfab7/timeouts 404 13 ms - 3160
[HTTP]
```

When I manually execute the command `/var/folders/md/ghkjmxg95czdj95l1_tf9zxr0000gp/T/espresso-server-emulator-5554/gradlew -PappiumTargetPackage\=com.example.toyaut app\:assembleAndroidTest`, there is no issue.

**Comment by KazuCocoa** [comment]
`showGradleLog` capability might help to check for more details.

```
[EspressoDriver@9f70 (a325502c)] The previous target application package is unknown
[EspressoDriver@9f70 (a325502c)] Forcing Espresso server rebuild because of changed application package
[EspressoDriver@9f70 (a325502c)] Building espresso server in '/var/folders/md/ghkjmxg95czdj95l1_tf9zxr0000gp/T/espresso-server-emulator-5554'
[EspressoDriver@9f70 (a325502c)] The build folder root could be customized by changing the 'tmpDir' capability
[EspressoDriver@9f70 (a325502c)] Copying espresso server template from ('/Users/ruizhengu/.appium/node_modules/appium-espresso-driver/espresso-server' to '/var/folders/md/ghkjmxg95czdj95l1_tf9zxr0000gp/T/espresso-server-emulator-5554')
[Support] Traversed 52 directories and 283 files in 281ms
[EspressoDriver@9f70 (a325502c)] Bulding espresso server
[EspressoDriver@9f70 (a325502c)] Beginning build with command '/var/folders/md/ghkjmxg95czdj95l1_tf9zxr0000gp/T/espresso-server-emulator-5554/gradlew -PappiumTargetPackage=com.example.toyaut app:assembleAndroidTest' in directory '/var/folders/md/ghkjmxg95czdj95l1_tf9zxr0000gp/T/espresso-server-emulator-5554'
[EspressoDriver@9f70 (a325502c)] Output from Gradle will not be logged. To change this, use 'showGradleLog' desired capability
[EspressoDriver@9f70 (a325502c)] Unable to build Espresso server - Process ended with exitcode 1 (cmd: '/var/folders/md/ghkjmxg95czdj95l1_tf9zxr0000gp/T/espresso-server-emulator-5554/gradlew -PappiumTargetPackage\=com.example.toyaut app\:assembleAndroidTest')
[EspressoDriver@9f70 (a325502c)] Gradle error message:
[EspressoDriver@9f70 (a325502c)]
[EspressoDriver@9f70 (a325502c)] [STDERR]           - Variant 'sourcesElements' capability com.android.tools.build:gradle:7.4.2 declares a runtime of a component, and its dependencies declared externally:,
[EspressoDriver@9f70 (a325502c)] [STDERR]               - Incompatible because this component declares documentation and the consumer needed a library,
[EspressoDriver@9f70 (a325502c)] [STDERR]               - Other compatible attributes:,
[EspressoDriver@9f70 (a325502c)] [STDERR]                   - Doesn't say anything about its target Java version (required compatibility with Java 8),
[EspressoDriver@9f70 (a325502c)] [STDERR]                   - Doesn't say anything about its elements (required them packaged as a jar),
[EspressoDriver@9f70 (a325502c)] [STDERR]                   - Doesn't say anything about org.gradle.plugin.api-version (required '7.5'),
[EspressoDriver@9f70 (a325502c)] [STDERR] ,
[EspressoDriver@9f70 (a325502c)] [STDERR] * Try:,
[EspressoDriver@9f70 (a325502c)] [STDERR] > Run with --stacktrace option to get the stack trace.,
[EspressoDriver@9f70 (a325502c)] [STDERR] > Run with --info or --debug option to get more log output.,
[EspressoDriver@9f70 (a325502c)] [STDERR] > Run with --scan to get full insights.,
[EspressoDriver@9f70 (a325502c)] [STDERR] ,
[EspressoDriver@9f70 (a325502c)] [STDERR] * Get more help at https://help.gradle.org,
[EspressoDriver@9f70 (a325502c)] [STDERR] ,
[EspressoDriver@9f70 (a325502c)] [STDERR] BUILD FAILED in 642ms
```

**Comment by ruizhengu** [comment]
Thanks, I fixed that.

**Comment by alanou2023** [comment]
Hi， I meet a similar problem, how can i fix this problem?
