### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/view/ScrollingView;

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium-espresso-driver#96]
When I updated `appium-espresso-driver` to beta9 from beta8, `GET /status` was timeouts and failed to continue the create session process. 
(Based on Appium master add9cfe6add22211f5a5f0596bcbc7131705ef26 and modified `package.json`)

I'd like to investigate more when I can get a time.

## beta9
```
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8080/status] with no body
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/kazuaki/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","am","instrument","-w","-e","debug","false","io.appium.espressoserver.test/android.support.test.runner.AndroidJUnitRunner"]
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8080/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8080/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8080/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8080/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8080/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8080/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8080/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8080/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8080/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8080/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8080/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8080/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8080/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8080/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8080/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8080/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8080/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8080/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8080/status] with no body
[debug] [Espresso] Deleting espresso session
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/kazuaki/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","am","force-stop","io.appium.android.apis"]
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Removing forwarded port socket connection: 8080
[debug] [ADB] Running '/Users/kazuaki/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","forward","--remove","tcp:8080"]
[HTTP] <-- POST /wd/hub/session 400 31127 ms - 992
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"android","automationName":"espresso","app":"/Users/kazuaki/GitHub/ruby_lib_core/test/functional/app/api.apk","platformVersion":"8.1.0","deviceName":"Android Emulator","appPackage":"io.appium.android.apis","appActivity":".ApiDemos","someCapability":"some_capability","unicodeKeyboard":true,"resetKeyboard":true,"forceEspressoRebuild":true},"capabilities":{"alwaysMatch":{"platformName":"android","appium:automationName":"espresso","appium:app":"/Users/kazuaki/GitHub/ruby_lib_core/test/functional/app/api.apk","appium:platformVersion":"8.1.0","appium:deviceName":"Android Emulator","appium:appPackage":"io.appium.android.apis","appium:appActivity":".ApiDemos","appium:someCapability":"some_capability","appium:unicodeKeyboard":true,"appium:resetKeyboard":true,"appium:forceEspressoRebuild":true},"firstMatch":[{}]}}
[debug] [W3C] Calling AppiumDriver.createSession() with args: [{"platformName":"android","automationName":"espresso","app":"/Users/kazuaki/GitHub/ruby_lib_core/test/functional/app/api.apk","platformVersion":"8.1.0","deviceName":"Android Emulator","appPackage":"io.appium.android.apis","appActivity":".ApiDemos","someCapability":"some_capability","unicodeKeyboard":true,"resetKeyboard":true,"forceEspressoRebuild":true},null,{"alwaysMatch":{"platformName":"android","appium:automationName":"espresso","appium:app":"/Users/kazuaki/GitHub/ruby_lib_core/test/functional/app/api.apk","appium:platformVersion":"8.1.0","appium:deviceName":"Android Emulator","appium:appPackage":"io.appium.android.apis","appium:appActivity":".ApiDemos","appium:someCapability":"some_capability","appium:unicodeKeyboard":true,"appium:resetKeyboard":true,"appium:forceEspressoRebuild":true},"firstMatch":[{}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1520646331915 (10:45:31 GMT+0900 (JST))
[Appium] The Appium Espresso driver is currently in early beta and meant only for experimental usage. I
```

- client
```
$ adb -P 5037 -s emulator-5554 shell am instrument -w -e debug false io.appium.espressoserver.test/android.support.test.runner.AndroidJUnitRunner
INSTRUMENTATION_RESULT: shortMsg=Process crashed.
INSTRUMENTATION_CODE: 0
```

```
03-10 10:55:28.855 27161-27177/io.appium.android.apis E/AndroidRuntime: FATAL EXCEPTION: Instr: android.support.test.runner.AndroidJUnitRunner
                                                                        Process: io.appium.android.apis, PID: 27161
                                                                        java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/view/ScrollingView;
                                                                            at java.lang.Class.classForName(Native Method)
                                                                            at java.lang.Class.forName(Class.java:453)
                                                                            at android.support.test.internal.runner.TestLoader.doCreateRunner(TestLoader.java:76)
                                                                            at android.support.test.internal.runner.TestLoader.getRunnersFor(TestLoader.java:110)
                                                                            at android.support.test.internal.runner.TestRequestBuilder.build(TestRequestBuilder.java:809)
                                                                            at android.support.test.runner.AndroidJUnitRunner.buildRequest(AndroidJUnitRunner.java:487)
                                                                            at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:373)
                                                                            at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2075)
                                                                         Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.view.ScrollingView" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/system/framework/android.test.mock.jar", zip file "/data/app/io.appium.espressoserver.test-F80T1oJn9Fy2W0W2PAs2zA==/base.apk", zip file "/data/app/io.appium.android.apis-LSsitJC6M2jDQYYxFm-uCA==/base.apk"],nativeLibraryDirectories=[/data/app/io.appium.espressoserver.test-F80T1oJn9Fy2W0W2PAs2zA==/lib/x86, /data/app/io.appium.android.apis-LSsitJC6M2jDQYYxFm-uCA==/lib/x86, /system/lib, /vendor/lib]]
                                                                            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
                                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                            at java.lang.Class.classForName(Native Method) 
                                                                            at java.lang.Class.forName(Class.java:453) 
                                                                            at android.support.test.internal.runner.TestLoader.doCreateRunner(TestLoader.java:76) 
                                                                            at android.support.test.internal.runner.TestLoader.getRunnersFor(TestLoader.java:110) 
                                                                            at android.support.test.internal.runner.TestRequestBuilder.build(TestRequestBuilder.java:809) 
                                                                            at android.support.test.runner.AndroidJUnitRunner.buildRequest(AndroidJUnitRunner.java:487) 
                                                                            at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:373) 
                                                                            at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2075) 
03-10 10:55:28.857 27161-27177/io.appium.android.apis I/Process: Sending signal. PID: 27161 SIG: 9
```

Get the following when run zipalign.

```
'Error: Command '/Users/kazuaki/Library/Android/sdk/build-tools/27.0.1/zipalign -f 4 /var/folders/y6/524wp8fx0xj5q1rf6fktjrb00000gn/T/io.appium.espressoserver.test_1.0.0-beta.9_io.appium.android.apis.apk /var/folders/y6/524wp8fx0xj5q1rf6fktjrb00000gn/T/2018211-31864-bpdo0r.svx8w/appium.tmp' exited with code 1'
```

## beta8
```
[debug] [ADB] Getting connected devices...
[Espresso] Waiting for Espresso to be online...
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8080/status] with no body
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/kazuaki/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","am","instrument","-w","-e","debug","false","io.appium.espressoserver.test/android.support.test.runner.AndroidJUnitRunner"]
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8080/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8080/status] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\"id\":\"73cb668d-dd53-41d1-b8a7-79b75e478b70\",\"sessionId\":null,\"status\":0,\"value\":null}"
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8080/session] with body: {"desiredCapabilities":{"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"platformName":"android","automationName":"espresso","app":"/Users/kazuaki/GitHub/ruby_lib_core/test/functional/app/api.apk","platformVersion":"7.1.1","deviceName":"Android Emulator","appPackage":"io.appium.android.apis","appActivity":"io.appium.android.apis.ApiDemos","someCapability":"some_capability","unicodeKeyboard":true,"resetKeyboard":true,"forceEspressoRebuild":true},"platformName":"android","automationName":"espresso","app":"/Users/kazuaki/GitHub/ruby_lib_core/test/functional/app/api.apk","platformVersion":"7.1.1","deviceName":"emulator-5554","appPackage":"io.appium.android.apis","appActivity":"io.appium.android.apis.ApiDemos","someCapability":"some_capability","unicodeKeyboard":true,"resetKeyboard":true,"forceEspressoRebuild":true,"deviceUDID":"emulator-5554","deviceScreen...
[debug] [JSONWP Proxy] Got response with status 200: {"id":"2b767710-aaff-445f-8385-f1e662f75752","sessionId":"3987e4b7-6d07-4fec-ab62-5e2515e4bd27","status":0,"value":{"desiredCapabilities":{"appActivity":"io.appium.android.apis.ApiDemos"},"id":"3987e4b7-6d07-4fec-ab62-5e2515e4bd27"}}
[Appium] New EspressoDriver session created successfully, session 7a72d9f4-7f35-414a-bf5d-66299d4b4c06 added to master session list
```

**Comment by dpgraham** [comment]
@mykola-mokhnach Do you know what the issue is? `java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/view/ScrollingView;`

It seems like I need to build the Java prior to doing publishes.

**Comment by mykola-mokhnach** [comment]
I had the same issue in the log. https://github.com/appium/appium-espresso-driver/pull/95 was a try to fix it

**Comment by KazuCocoa** [comment]
renamed(title)

I tried the latest master, but it reproduced on my machine. I'll try again later.

**Comment by dpgraham** [comment]
I'm having the same issue. I looked at it today and saw that zipAlign isn't working.

**Comment by dpgraham** [comment]
Is this still happening for anyone? Seems to be working fine now.

**Comment by KazuCocoa** [comment]
Let me try the latest driver.
